### ISSUE TITLE
how to calculate VAF for SV ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#100]
HI, 
@jvhaarst 
 how to calculate VAF for SV  from Delly2 result ?

thanks !

**Comment by tobiasrausch** [comment]
This question has been answered on the delly-users list:

https://groups.google.com/forum/#!searchin/delly-users/allele$20frequency%7Csort:date/delly-users/2voDbPk2HcE/gXPkVDhoAAAJ
