### ISSUE TITLE
Delly misreads sample names with spaces

### ISSUE THREAD

**Issue by chapplec** [dellytools/delly#102]
If a bam file has a sample whose name contains a space, like this:

```
$ samtools view -h sample.bam | grep -oP 'SM:[^\t]+'
SM:test spaces 27-03-18
```

Delly will stop reading the sample name at the first space:

```
$ delly call -n -x 'excludeTemplates/human.hg19.excl.tsv' -g 'hg19.fa' -o aa.bcf sample.bam 2>&1 | grep Sample
Sample: test
```

I fixed this by changing line 238 of `util.h` from:

	std::string delim("\t ");

to 

	std::string delim("\t");

Since the BAM file specification sets tabs as the separator, it might be a good idea to change this. Will this change affect anything else I don't see? I haven't even looked at the source apart from that line.

**Comment by tobiasrausch** [comment]
Thanks.
