### ISSUE TITLE
why  'filter' of delly2 remove this  record  marked by 

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#105]
HI,
command  ： 
/home/wangjf/bin/delly filter -f germline  -o  filter.bcf   test1.bcf

I found the following record is  filtered , why ?

chr22	23634672	BND00005559	A	]chr9:133729677]A	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr9;END=133729677;PE=759;MAPQ=60;CT=5to3;CIPOS=-3,3;CIEND=-3,3;INSLEN=0;HOMLEN=2;SR=10;SRQ=1;CONSENSUS=AAAAGGGTTGTGGGCAGCTAGTGGTGGTTGCAGGAGATAGAAATCTGGGAAATGTGGGTGATGTGGAAAAGACCTGTGACCTTCTCCATGTCCACTTCTCCC;CE=1.96819	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-1000,0,-1000:10000:PASS:10:3068:942:6:970:762:870:893

**Comment by tobiasrausch** [comment]
You applied the germline filter which requires at least 20 unrelated samples to work properly (the more samples the better).  This was mentioned in the delly-users group previously but I agree this is not clear from the Delly README. I have changed this now, thanks.
