### ISSUE TITLE
Delly creates unmergeable files ("The REF prefixes differ: T vs A (1, 1)")

### ISSUE THREAD

**Issue by holtgrewe** [dellytools/delly#107]
After working around #106 by removing calls with position 0 for now and regenotyping, I am now facing the problem of Delly generating the following lines:

```
bwa.delly2.genotype.1008-N1-DNA1-WGS1.vcf.gz:1	38575845	INS00033503	T	TATATATATATATATATATA	.	PASS	PRECISE;SVTYPE=INS;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=1;END=38575846;PE=0;MAPQ=60;CT=NtoN;CIPOS=-24,24;CIEND=-24,24;INSLEN=19;HOMLEN=25;SR=6;SRQ=0.972789;CONSENSUS=TAAATTTGACTATATGAAAATTAAACATTTAAGTACCTTAAAGAACATTATAAGAAAATTTTAAAAGAGGGGTATATACATATGTATGTGTATATATATATATATATATATATATATATATATATATATATAATACAACATTTTAATTTTATTTTTAATGTATAA;CE=1.55777	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-115.493,-9.62643,0:96:PASS:20452:41077:20630:2:0:0:0:32
bwa.delly2.genotype.1008-N1-DNA1-WGS1.vcf.gz:1	38575846	INS00033504	A	ATATATATATATATATATG	.	PASS	PRECISE;SVTYPE=INS;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=1;END=38575847;PE=0;MAPQ=60;CT=NtoN;CIPOS=-24,24;CIEND=-24,24;INSLEN=18;HOMLEN=24;SR=10;SRQ=0.977012;CONSENSUS=AGAAAAGATTGATAAATTTGACTATATGAAAATTAAACATTTAAGTACCTTAAAGAACATTATAAGAAAATTTTAAAAGAGGGGTATATACATATGTATGTGTATATATATATATATATATATATATATATATATATATATATGTGAACAACAGTTTTATTTTATTTATAATGTACAAAGAGCTCTTACACA;CE=1.67088	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-81.7944,-6.91811,0:69:PASS:20443:41073:20635:2:0:0:0:23
```

`bcftools merge` (rightfully) refuses to merge these:

```
The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at 1:38575846 in bwa.delly2.genotype.1008-N1-DNA1-WGS1.vcf.gz
```

Please advise. I'm using Delly v0.7.8.

**Comment by holtgrewe** [comment]
That worked well.

**Comment by Yixiangzhang1996** [comment]
> I think bcftools tries to create a multi-allelic record. Merging by ID should be fine:
> 
> bcftools merge -m id -O b -o merged.bcf s1.geno.bcf s2.geno.bcf ... sN.geno.bcf

The REF prefixes differ: A vs N (1,1)
Failed to merge alleles at scaf_138282:562 in Delly.geno.bcf

**Comment by tobiasrausch** [comment]
What version of bcftools are you using?

**Comment by grzadr** [comment]
I have similar problem with bcftools 1.9. My command:
```
bcftools merge -m id -O b -o /data/results_cnvs/delly/delly.genotypes.bcf/data/samples/CFA_242/cnvs/delly/CFA_242.delly.genotyped.bcf /data/samples/CFA_246/cnvs/delly/CFA_246.delly.genotyped.bcf
```

This command is invoked after genotyping with first merged SV (delly merge).

Line that seems to cause problems:
```
JH373363.1      65988   BND00074084     C       C]JH373323.1:383]       .       LowQual IMPRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=JH373323.1;END=383;PE=3;MAPQ=20;CT=3to3;CIPOS=-50,50;CIEND=-50,50 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV 0/0:0,-10.2973,-141.761:103:PASS:110:110:152:1:35:0:0:0
```

**Comment by Yixiangzhang1996** [comment]
> I have similar problem with bcftools 1.9. My command:
> 
> ```
> bcftools merge -m id -O b -o /data/results_cnvs/delly/delly.genotypes.bcf/data/samples/CFA_242/cnvs/delly/CFA_242.delly.genotyped.bcf /data/samples/CFA_246/cnvs/delly/CFA_246.delly.genotyped.bcf
> ```
> 
> Error message:
> 
> ```
> The REF prefixes differ: C vs N (1,1)
> ```
> 
> This command is invoked after genotyping with first merged SV (delly merge).
> 
> Line that seems to cause problems:
> 
> ```
> JH373363.1      65988   BND00074084     C       C]JH373323.1:383]       .       LowQual IMPRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=JH373323.1;END=383;PE=3;MAPQ=20;CT=3to3;CIPOS=-50,50;CIEND=-50,50 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV 0/0:0,-10.2973,-141.761:103:PASS:110:110:152:1:35:0:0:0
> ```
Have you solved this problem? Have you seen any problems with individual files?

**Comment by grzadr** [comment]
Sorry for my late response. I solved my problem by splitting analysis into 5 parts by specifying different SV types with -t flag.

**Comment by tobiasrausch** [comment]
Thanks for getting back to me. That's indeed a good suggestion because for the same SV type these errors should not happen. Thanks.
