### ISSUE TITLE
better filter method for tumor only sample ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#108]
HI,
   I just have one only tumor sample , not paired .  what's best filtering method for delly2 ?
   I think "delly filter  -f germlie  ' is not a good method . 
   So could you please give me some suggestions ?
   I check the single tumor sample result ,,, somebody said that  GT: 0/0 and GT:1/1 should be filtered ,, Is it right ??  I think GT: 1/1 is possible for somatic mutation  . 

thank you in advance !

**Comment by tobiasrausch** [comment]
Delly does not support somatic filtering for unpaired samples, sorry.
