### ISSUE TITLE
how to get breakpoint position range from CIPOS and CIEND 

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#110]
HI,
    ##INFO=<ID=CIEND,Number=2,Type=Integer,Description="PE confidence interval around END">
    ##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="PE confidence interval around POS">
   for the next record : 
   chrY	28780768	BND00006132	C	[chr13:19949154[C	.	PASS	PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr13;END=19949154;PE=26;MAPQ=25;CT=5to5;CIPOS=-58,58;CIEND=-58,58;
  I wanna convert this translocation into  two breakpoints format , it's right ? 
   A breakpoint position range  --  chrY :  [28780768-58,28780768+58 ] 
   B  breakpoint position range --  chr14 : [19949154-58,19949154+58]

**Comment by WinterLi1993** [comment]
@tobiasrausch  
for current issue ,any information ?

**Comment by tobiasrausch** [comment]
Sorry I don't know this two breakpoints format.
