### ISSUE TITLE
one breakpoint is not included by  probe bed region  

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#111]
HI,
    for  target panel sequencing  sample , I find  that many breakpoints position in not included by the panel bed range .  I think  all variants position should be included at known probe panel bed position range .
but I find delly2  breakpoints position is not like that ... 
  why ?

thank you in advance !

**Comment by tobiasrausch** [comment]
All target panel sequencing approaches usually suffer from a certain number of off-target reads. What's the on-target rate in your experiment? These off-target reads create variants but of course, you can filter these out downstream or by adapting Delly's exclude map.

**Comment by WinterLi1993** [comment]
@tobiasrausch 
on-target rate is  61.31% . 
what is the meaning of  filtering  these out downstream  ?? you mean that  if  one breakpoint position is not in our panel region ... this SV(one line record in vcf)   should be filtered  ?
