### ISSUE TITLE
delly2 can not detect intra-chromosomes translocation ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#112]
Hi,
    delly2 can not detect intra-chromosomes translocation ? 
    https://github.com/dellytools/delly/issues/72 
   
   but gene fusion will occur  with intra-chromosomes translocation .

**Comment by tobiasrausch** [comment]
Delly detects intra-chromosomal translocations but they show up as deletion-type, inversion-type and duplication-type paired-end clusters. For instance, the TMPRSS2-ERG gene fusions from the below paper have been identified by Delly.

https://www.ncbi.nlm.nih.gov/pubmed/23410972

I am working to improve this further by having a mode that can additionally use RNA-Seq to confirm gene fusions but it's not ready yet.
