### ISSUE TITLE
how to filter breakpoint position by the panel bed region ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#113]
HI,
   I have a panel bed file , I wanna filter  SV breakpoints position via the panel .
   For precise  sv breakpoints ,  like the next  record ,
**chr22**	**41573221**	DEL00005853	C	<DEL>	.	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.8;**CHR2=chr22;END=41573516**;PE=3;MAPQ=60;CT=3to5;CIPOS=-4,4;CIEND=-4,4;
   I should check  whether the breakpoint (chr22:41573221) and another breakpoint (chr22:41573516) is both included at the panel bed region , if not , remove it .

  but for  imprecise sv  breakpoints , also  like the next  record ,
  chr1    10355258        INV00000015     T       <INV>   .       PASS    IMPRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=10355374;PE=3;MAPQ=60;CT=3to3;CIPOS=-178,178;CIEND=-178,178
   I should check  whether **the breakpoint (chr22:[41573221-178,41573221+178])** and another **breakpoint (chr22:[41573516-178,41573516+178])** is **both** included at the panel bed region , if not , remove it .

  So  that filtering method is right ??

Thank you in advance .

**Comment by tobiasrausch** [comment]
Yes, indeed. If you are for instance looking for exon-intersecting SVs you can use estimated breakpoint +/- confidence interval and then intersect with a list of exons. However, even the imprecise SVs are often really close to the estimated breakpoint so we frankly always just use POS and INFO:END to infer functional consequences of SVs.
