### ISSUE TITLE
What does a CN value of -1 represent?

### ISSUE THREAD

**Issue by jjfarrell** [dellytools/delly#114]
The following are the copy number counts for a chromosome for one sample. There are a 5 sites with a  CN value of -1. What does the -1 represent? 

### Number                  CN

 ```
        5 -1
      513 0
     4015 1
    37603 2
     1351 3
      251 4
      133 5
       67 6
       45 7
       30 8
       22 9
       20 10
        9 11
        3 12
        8 13
        4 14
        6 15
        7 16
        2 17
        2 18
        1 19
        2 20
        1 22
        1 24
        1 27
        1 28
        3 30
        1 35
        1 43
        2 46
        1 56
        1 57
        1 60
        1 225
```

**Comment by tobiasrausch** [comment]
Hi,

The CN field is estimated by normalizing the read-depth inside the SV by the surrounding read depth. If there is no data outside the SV locus it is set to -1. In short, for CN == -1 the copy-number could not be estimated. In general, the CN estimation works best for large SVs >1kbp and high-coverage samples.

Best, Tobias
