### ISSUE TITLE
Run delly on multiple samples

### ISSUE THREAD

**Issue by woodoo46** [dellytools/delly#117]
Hi Delly developers,

I assume we can run delly on trio data? For example, for mom/dad/kid in a family. If so, does each sample have to be in a single bam file? For example, can we delly as:

delly call -o out.vcf -g genome.fasta sample1_chr1.bam sample1_chr2.bam ... sample2_chr1.bam sample2_chr2 ... sample3_chr1.bam sample3_chr2 ...

Thanks!

George

**Comment by tobiasrausch** [comment]
Hi,

The BAM files shouldn't be split by chromosome. This will miss inter-chromosomal translocations. You can call a trio jointly with Delly.

delly call -o out.vcf -g hg19.fa -x hg19.excl mother.bam father.bam child.bam

For high-coverage data it is also fine to run the samples individually and then merge the BCFs and possibly re-genotype de novo calls in the child.
