### ISSUE TITLE
Delly hangs on a specific WGS sample (running for a week already)

### ISSUE THREAD

**Issue by chapplec** [dellytools/delly#119]
I have run delly on other WGS samples with no problem, but this particular one has been running for a week now and is still stuck here:

```
2018-May-25 11:32:49] delly call -n -x excludeTemplates/human.hg19.excl.tsv -g hg19.fa -o delly/variants.bcf sample.bam 
[2018-May-25 11:32:56] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2018-May-25 12:08:43] Split-read alignment

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***
```

The sample bam file is large, 110G, but the progress bar hasn't moved in a week. It's using 100% of a cpu, so it does seem to be working, but feels like the algortihm has entered a loop somewhere. Are there any known issues that can cause such a loop? I am already using `-n` to avoid calling small variants, what else can I do here? I am afraid that I cannot share the bam file, it is confidential, but please let me know if I can provide any more information to investigate this.

Thanks

**Comment by tobiasrausch** [comment]
Usually long running BAMs have either a large fraction of inter-chromosomal paired-ends or a non-Gaussian insert size distribution. You can check both with [Alfred](https://github.com/tobiasrausch/alfred). Such issues have been reported before (i.e., https://github.com/dellytools/delly/issues/115) but they are often a problem of the library prep or input DNA.

**Comment by chapplec** [comment]
Thanks! I searched the mailing list but didn't think to check the issues. Sorry. I am running alfred now and will check to see if I have too many interchromosomal pairs. If so, I'll close this as a dupe.

**Comment by chapplec** [comment]
```
$ alfred qc -r hg19.fa -o stats.tsv.gz prod/sample.bam
$ zcat stats.tsv.gz | head | awk '/^ME/{print $26,$28,$29}' OFS="\t"
#MappedPairs    #MappedSameChr  MappedSameChrFraction
330035994       294249265       0.860153
```
If I understand correctly, that means ~14% of pairs map to different chromosomes. If so, that does seem excessive. Would that be enough to cause delly to run for so long (still no change today, just at the third `*` of Split-read alignment, 8 days later)? Also, is it worth letting it run, will it ever finish or should I just give up?

The insert size distribution seems to be OK:
![image](https://user-images.githubusercontent.com/16101661/40881948-33a67778-66cc-11e8-8d19-5b2669ced6a0.png)

Thanks!

**Comment by Guoshuai1314** [comment]
I have the same problem as you when I run delly. Therefore, I would like to known whether you have solved this problem. If so, how did you solve it? Thank you very much.

**Comment by tobiasrausch** [comment]
If ~14% map to different chromosomes that is literally millions of pairs. The header of the insert size distribution in addition states that >11% of your paired-ends have an insert size >28,000bp. To be honest, this library is useless for paired-end mapping approaches.  In general, for libraries with non-Gaussian insert size distributions you can set -s higher, i.e.  -s 15. For libraries with lots of inter-chromosomal paired-ends you probably want to exclude most and thus, set -r higher, i.e. -r 50 or to exclude all translocation calls -r 200. In short, 

./delly call -s 15 -r 200 -q 20 -n ...

should work for most poor quality libraries but in your case I suppose even these parameters are not working. That library looks like a failure to me.

**Comment by chapplec** [comment]
Agreed. 14% of a WGS run is a ridiculous amount of pairs. I will contact the person who sent me this sample and tell them to go back to their sequencing providers. Thank you.
