### ISSUE TITLE
delly read orientation error

### ISSUE THREAD

**Issue by alishka1988** [dellytools/delly#120]
This is a follow up of (https://github.com/dellytools/delly/issues/97) since I'm still having the same issue after taking recommended corrective steps. 

I have re-aligned my Nextera samples with BWA-mem to rule out aligner issues and ran nxtrim to remove Nextera adapters and convert RF reads to FR. I then  ran Delly delly_v0.7.8 and I'm still  getting the same error for all the samples:
Error: One library has a non-default paired-end layout! Read-group: 4
The expected paired-end orientation is ---Read1---> <---Read2--- which is the default illumina paired-end layout.

I ran alfred on a Nextera sample and a Truseq PCR-free sample (which Delly ran fine on). I noticed that the Nextera sample had a much larger library insert size reported (~400bp) than the Truseq sample(~200bp). Would the larger insert size cause issues for Delly?

**Comment by tobiasrausch** [comment]
How did you run nxtrim? For a mate-pair library the insert size reported by alfred should be >2,000bp so I suspect you have all the short-insert chimera pairs.

**Comment by alishka1988** [comment]
This is the command I used:
nxtrim -1  R1.fastq -2  R2.fastq --stdout > clipped_sample.fastq

**Comment by tobiasrausch** [comment]
Try to output first only the MP reads

nxtrim -1 R1.fastq -2 R2.fastq --preserve-mp --stdout-mp

Then map and compute the insert size using alfred. This should yield a fragment size >2,000bp otherwise this is not a mate-pair library (or it failed).

**Comment by tobiasrausch** [comment]
As far as I can recollect this is not a delly error. I will close this issue for the time being, please reopen if you still have a problem.
