### ISSUE TITLE
docker image error: bash: delly: command not found

### ISSUE THREAD

**Issue by arkyl** [dellytools/delly#121]
hi,
I pulled the delly docker image and it succeeded. I ran the following command:
 docker run -it -v tmp_data:/data dellytools/delly /bin/bash
and it succeeded.

but when i ran the delly command:
delly
I got the error "bash: delly: command not found".

Any thoughts on what may be the problem? Thanks a lot!
Yue

**Comment by tobiasrausch** [comment]
Sorry, I haven't added delly to the PATH in the Docker container. This should work

/opt/delly/src/delly

-Tobias

**Comment by arkyl** [comment]
Thanks, it works!
