### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by arkyl** [dellytools/delly#123]
Hi,
I tried to compile delly from src , and got the following error:

src/delly.h:51:26: fatal error: htslib/faidx.h: No such file or directory. 

It seemed that there was no htslib/faidx.h. Any thoughts about what is the problem? Thanks a lot!

Yue

**Comment by tobiasrausch** [comment]
Looks like you didn't do a recursive checkout?

git clone --recursive https://github.com/dellytools/delly.git

**Comment by arkyl** [comment]
You are right. Thanks!
