### ISSUE TITLE
Error installing 0.7.7

### ISSUE THREAD

**Issue by maribuon** [dellytools/delly#124]
Dear Tobias,

I need to install version 0.7.7, but both tar.gz or zip versions give me the same error:
$ make all
cd src/htslib && make && make lib-static && cd ../../ && touch .htslib
make[1]: Entering directory `$HOME/bin/delly-0.7.7/src/htslib'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `$HOME/bin/delly-0.7.7/src/htslib'

when I check the files, it seems the folder src/htslib is empty, which isn't the case in 0.7.8 version.

Can you help me installing the old version, please?

Kind regards,
Mariana

**Comment by tobiasrausch** [comment]
Please note that you can find static binaries for all versions [here](https://github.com/dellytools/delly/releases). Delly v0.7.7 is also still available on [Bioconda](http://bioconda.github.io/recipes/delly/README.html). If you still need to compile this should work for v0.7.7:

git clone --recursive git@github.com:dellytools/delly.git
cd delly
git checkout v0.7.7
git submodule update --init --recursive
make all

The zip and tar.gz files from github unfortunately lack the submodules.
