### ISSUE TITLE
Delly does not return error when supplied (potentially) invalid exclude file

### ISSUE THREAD

**Issue by fpbarthel** [dellytools/delly#127]
I accidentally supplied a JSON file with excluded regions to Delly and it does not error. I cannot find any documentation that this should be allowed, so it should error?

**Comment by tobiasrausch** [comment]
Indeed I should check the format more carefully. The expected input is a tab-delimited file with chromosome, start, end, and an arbitrary id. Additionally, I do allow lines with just one column to exclude an entire chromosome.

**Comment by tobiasrausch** [comment]
Added a range of checks for the exclude file. I still ignore empty lines and lines starting with a chromosome that is not present in the BAM file. That's on purpose so one can have a single exclude file with all the different chromosome naming conventions. For instance, to exclude the mitochondrial chromosome this is fine:

chrM
M
chrMT
MT
