### ISSUE TITLE
Delly shows weird error when searching for "INV"

### ISSUE THREAD

**Issue by priyasma** [dellytools/delly#128]
Dear Tobias,

I am running 20 dog bam files and have been able to generate output for Del and Dup, but not Inversion since I get the following error message. Can somebody please help?

/usr/prog/bin/delly -t INV -o del4.vcf -g /PATH/canFam3.fa PATH/abc.bam

[2018-Aug-01 22:33:34] Paired-end clustering
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*[2018-Aug-01 22:33:34] Paired-end clustering
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> >'what():  the argument ('/PATH/canFam3.fa') for option '--split' is invalid
*******

Thank you..

**Comment by tobiasrausch** [comment]
Please let me know if this issue is still present or if it was a temporary issue in your compute environment. I will close this issue for the time being but please re-open if there is still a problem.
