### ISSUE TITLE
DELLY slow on paired whole genome

### ISSUE THREAD

**Issue by fpbarthel** [dellytools/delly#129]
Hi @tobiasrausch, I am experiencing similar performance issues as reported before [here](https://github.com/dellytools/delly/issues/36).My delly analyses on 30x tumor-normal WGS bam files are suffering from very long run times. I am using the following command to run delly:

```
delly call -n -x human_g1k_v37_decoy_svmask_delly.bed -o out.bcf -g human_g1k_v37_decoy.fasta tumor.bam normal.bam 
```

More than half (of ~20) tumor/normal pairs ran out of walltime (72 hours) using 2 cores and 12 GB of memory (without the `-n` parameter). I have now re-started all processes (with the `-n` parameter, 12 cores, 160 hours runtime and 72 GB mem) and so far (24h later) only one is finished so far. My exclude bed file has 441 regions (including full mask for any extra contigs). Any other suggestions? What wall time is normal for 30x whole genomes? (On 12x Intel Xeon E5 @ 2.60 Ghz and 72 gigs of mem)

**Comment by tobiasrausch** [comment]
If you already tried -n and that didn't help then it's often due to library prep problems. Have you checked your BAM file for excessive amounts of inter-chromosomal pairs or a weird insert size distribution with multiple peaks or a very long tail? If you haven't done this yet you can run [alfred](https://github.com/tobiasrausch/alfred) and then me the qc output file or just post the key metrics here using 

`zgrep ^ME qc.tsv.gz`

**Comment by fpbarthel** [comment]
Well, interestingly `alfred` is having trouble with a sample that belongs to this category.

After 4 hours of processing there isn't really much happening:

```
[2018-Aug-24 15:19:14] alfred qc -r human_g1k_v37_decoy.fasta TCGA-FG-A4MT-02.realn.mdup.bqsr.bam
[2018-Aug-24 15:19:14] BAM file parsing

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*
```

This is one of the TCGA whole genomes (potentially on ICGC as well).

I do have insert sizes from the `libstat` R script that comes with LUMPY/svtyper. Look pretty normal (to me)

![screen shot 2018-08-24 at 4 45 45 pm](https://user-images.githubusercontent.com/9220167/44607123-54503400-a7bd-11e8-859a-fc5c70b9dd01.png)

![screen shot 2018-08-24 at 4 45 37 pm](https://user-images.githubusercontent.com/9220167/44607131-59ad7e80-a7bd-11e8-8085-43ba75c0a79f.png)

**Comment by tobiasrausch** [comment]
How many read-groups does this sample have?

samtools view -H TCGA-FG-A4MT-02.realn.mdup.bqsr.bam | grep "^@RG"

Delly and Alfred are read-group aware and if there are several dozens then this would explain why both are slow. Alfred already has a flag to ignore read-groups:

./src/alfred qc -i ...

If that's the problem I should also add this to Delly.

**Comment by tobiasrausch** [comment]
Delly now assumes that only one library was used to sequence the sample. In the old days, often multiple libraries were sequenced to achieve 30x human coverage but that's over I think. You can still enable the read-group aware calling with -e. Also small indel calling is now deactivated by default, -i activates small indel calling. If you still experience speed issues please re-open that issue. Thanks.

**Comment by fpbarthel** [comment]
That's likely the issue then! Thanks for the clarification
