### ISSUE TITLE
Empty BCF Output

### ISSUE THREAD

**Issue by waqasuddinkhan** [dellytools/delly#130]
Hi,

I run delly on WGS bam file and found some SVs. But when I re-run delly on a sub-set of same bam file (encompassing that region), the bcf is empty. Altohugh, I already knew that there are some SVs so why bcf is empty.

delly call -g hs37d5.fa -o mybigbam.bcf mybigbam.bam -x human.hg19.excl.tsv 
(my successful command with complete bam file)

delly call -g hs37d5.fa -o mysubet.bcf mysubset.bam -x human.hg19.excl.tsv 
(now my bcf has header only)

Thanks in advance,

Waqas.

**Comment by tobiasrausch** [comment]
Delly needs a "normal" genomic region to estimate the coverage and insert size distribution. In short, if you are interested in subsetting a BAM to a deletion from chr1:5000000-6000000 then you need to slice the BAM +/-1Mbp (depending on the coverage) so something like:

samtools view -b input.bam chr1:4000000-7000000 > subset.bam

**Comment by waqasuddinkhan** [comment]
Thanks, I also upgraded my bcftools, all is working well now!!!!!!!

**Comment by tobiasrausch** [comment]
Yes, you need a recent bcftools version. Thanks for the update.
