### ISSUE TITLE
Error abou Reference file is missing ?

### ISSUE THREAD

**Issue by lss1227** [dellytools/delly#133]
Hi, I download and installed newest (0.7.8) Delly as instructions. I believe it has been installed correctly because  ` ./delly call --help`  can run. Then I extracted chr21 from a bam file to make a test bam. The test bam is sorted, indexed and duplicate marked. Reference file is indexed using `samtools faidx hg19.fa`.  Calling germline command is `delly call -g /my/path/to/hg19.fa -o test.bcf -x hg19.excl test.bam`. However it shows that `Reference file is missing: Segmentation fault (core dumped)`. The reference fasta file does exist. I also tried GRCH37 but still the same error. 
Do I miss something ?
Thank you very much for helping me.

**Comment by tobiasrausch** [comment]
Delly crashes on the line where it just outputs the path to the genome file. This is strange. Is this maybe a dead symbolic link or some kind of weird path with spaces or non-alphanumeric characters? You can try once to copy the reference to the local directory just to see if that is really the error.

**Comment by lss1227** [comment]
Hi, I have copied reference to local directory and made a new fai file. The error is still there. I wonder if there are some test files ? Thanks.

**Comment by lss1227** [comment]
Hi, it seems that I can use Delly now. At first I installed Delly using 
`git clone --recursive https://github.com/dellytools/delly.git
cd delly/
make all`
Everything is ok except reporting 'reference file is missing' no matter how I change my reference. Though I don't know what the exact problem is, statically linked binary fixed it. Thanks.

**Comment by tobiasrausch** [comment]
I suspect it's some problem with an outdated Boost version but I am glad the static binary is working.

**Comment by Qiuming1986** [comment]
Hi，I have the same problem "Reference file is missing: Segmentation fault (core dumped)". I would like to known what is  the static binary and how to fix the problem.

**Comment by lgmgeo** [comment]
Hi, same problem...

I have a Boost version = 1.74

> statically linked binary fixed it
Can you explain more this solution?

Thank you,
Véronique

**Comment by lgmgeo** [comment]
Found it.
Complete path does not work with singularity, relative path do.

**Comment by lgmgeo** [comment]
Got it, thank you :o)
