### ISSUE TITLE
How to install in in CentOS 6?

### ISSUE THREAD

**Issue by billzt** [dellytools/delly#138]
First I try to run the pre-compiled binary directly. However it says:
```
FATAL: kernel too old
```
It is impossible for me to upgrade the kernel. Therefore I try to compile from the source code. However I don't know the dependent libraries. The `Dockerfile` is based on Ubuntu. Many components are not available from CentOS.

**Comment by tobiasrausch** [comment]
Have you tried the Bioconda version [http://bioconda.github.io/recipes/delly/README.html](http://bioconda.github.io/recipes/delly/README.html)? CentOS 6 is very old, I don't think I have computers around here that still run it but I will check.

**Comment by tobiasrausch** [comment]
You can still use the docker container on CentOS 6, right?

[Delly Docker Container](https://hub.docker.com/r/dellytools/delly/)

Please note that Bioconda is also generating docker containers for delly.

[Biocontainer for Delly](https://quay.io/repository/biocontainers/delly)

I guess both should work on CentOS 6.
