### ISSUE TITLE
delly call question: strutural variant missing or imprecise

### ISSUE THREAD

**Issue by rayliu0115** [dellytools/delly#139]
Hi there,

I have one question about the delly call result: there was a cell line sample with a known structural variant( SCL34A2-ROS1) and I used delly v0.7.8 to call its bam ( average deep:1800X, big target panel), but I didn't find this SV in my first test. I also checked igv and found the splitting reads at SCL34A2 and ROS1. Then, I downsampled this bam to 1200X and re-run SV calling with the same parameters. The SV appeared in this test.

I also found sometimes a "IMPRECISE" result could change to "PRECISE" if I reduced the average coverage of a bam. 
![image](https://user-images.githubusercontent.com/34330507/48463475-1b9d8500-e817-11e8-8872-ef050e20bd33.png)

I have tested many SV softwares, and each of them has different drawbacks. For now, delly is the best one. This "IMPRECISE/PRECISE" problem has confused me for a long time, so I have to ask what would affect the delly result. I knew the library operation should be one, but I have no idea how it affect the detection. Do you have any suggestion?

Thanks so much!
Rui

**Comment by tobiasrausch** [comment]
Thanks for trying Delly. For the paired-end discovery (imprecise SVs) very deep coverage shouldn't create big issues. That's different for the consensus computation required for precise SVs. At very deep coverage a set of mis-mapped or error-prone reads might destroy the consensus, that's essentially boiling down to limitations of progressive alignment for hundreds of sequences. If you are looking for clonal SVs (>20% allele frequency) at deep coverage then I would suggest to play a bit with the mapping quality cutoffs (-r 30, or -r 40). This might help in getting this SV at nucleotide resolution all the time.

**Comment by rayliu0115** [comment]
Hi Tobias,

Thanks for your reply. The parameters I used in all of my tests are : delly_v0.7.8 call -g hg19.fa -q 30 -r 30 -n -o test.vcf test.bam. I will keep working on it.

Cheers,
Rui
