### ISSUE TITLE
adjacency_list.hpp installation error

### ISSUE THREAD

**Issue by nirvana693** [dellytools/delly#142]
i am getting following error. how to solve

In file included from src/delly.cpp:40:0:
src/delly.h:31:42: fatal error: boost/graph/adjacency_list.hpp: No such file or directory
compilation terminated.
Makefile:61: recipe for target 'src/delly' failed
make: *** [src/delly] Error 1

**Comment by tobiasrausch** [comment]
You lack the Boost development libraries. If you are using Ubuntu you need to install them using:

apt install libboost-all-dev

There are static binaries for Delly and it's also available on Bioconda so in general there is no need to compile from source.
