### ISSUE TITLE
The REF prefixes differ when merging delly VCFs 

### ISSUE THREAD

**Issue by ffavila** [dellytools/delly#143]
Hello Tobias,
I am running Delly v0.7.8, and when trying to merge VCFs by ID using bcftools merge, I get the message: 
The REF prefixes differ: CATG(...)TTTT vs CATG(...)TTTT (393,447)
Failed to merge alleles at chr1:182691223 in delly2.vcf.gz

My bcftools command is: 
bcftools merge -m id -O z delly1.vcf.gz delly2.vcf.gz delly3.vcf.gz delly4.vcf.gz -o delly_merged.vcf.gz

The BAM files were generated using the same pipeline. What can be causing this? Thanks in advance!

**Comment by tobiasrausch** [comment]
Sorry for my late reply. Delly merge should handle these cases correctly:

delly merge -o sites.bcf delly1.vcf.gz delly2.vcf.gz delly3.vcf.gz delly4.vcf.gz

Then you can re-genotype this site list and merge with bcftools merge afterwards as explained in the [README](https://github.com/dellytools/delly/blob/master/README.md)

Best, Tobias

**Comment by tobiasrausch** [comment]
Please let me know if this is still an issue for you. I will close this issue for the time being. In Delly v0.8.1, you should not encounter these kind of REF prefix errors anymore.
