### ISSUE TITLE
How is somatic mode filtered?

### ISSUE THREAD

**Issue by sky-peng** [dellytools/delly#145]
Hello
    I'm sorry to bother you, but i have a trouble that requires you to answer.
    My delly pipeline is:
 ```
  delly filter -f somatic -o tumor.filter.bcf -s sample.tsv tumor.bcf
   ```
 And i found that there is a inversion to be filtered, which i think it's a positive inversion. The below is the detail information:
```
chr10   32311365        INV00042495     A       <INV>   .       PASS    PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.7.9;CHR2=chr10;END=43609713;PE=129;MAPQ=60;CT=5to5;CIPOS=-2,2;CIEND=-2,2;INSLEN=0;HOMLEN=1;SR=10;SRQ=1;CONSENSUS=TCTGTAAAATTAGTATTTCATATTTGAGTCTTCAGTGCCTTAGTTTGCAAGTATCTGTAAGAGGGCAATAGTGGTCTAGGAGGGGGCAGTAAATGGCAGTACC;CE=1.93912 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV0/1:-1000,0,-1000:10000:PASS:55111:215483:6164:7:2509:233:2242:304      0/0:0,-631.56,-1000:10000:PASS:43978:172307:4911:7:2346:7:2098:0
```  
Looking forward to your reply, thanks!

**Comment by tobiasrausch** [comment]
Looks like a sub-clonal inversion at ~11% variant allele frequency. You need to lower the default AF threshold:

delly filter -f somatic -a 0.05 ...

**Comment by dongjuleem** [comment]
Sorry for the basic question. 
Are somatic mutations and sub-clonal mutations not the same thing? 
If it's 11%, shouldn't it be considered a somatic mutation?
