### ISSUE TITLE
How to calculate AF from Delly vcf ?

### ISSUE THREAD

**Issue by unique379r** [dellytools/delly#146]
Hi,
I have the vcf generated from Delly, can you guide me, how to calculate Allele Frequency along with homo and heterozygous?  I am slightly confused whether i should use RR and RV or DR and DV in order to calculate AF. 
```
Allele freq (AF) = alt read/ref reads+alt reads.
I am sure, GT is associated with home/heterozygous information.

Example:
GT	GL	GQ	FT	RCL	RC	RCR	CN	DR	DV	RR	RV
1/1:-91.0986,-0.0263747,0	3	LowQual	8770	21159	12390	2	0	0	2	25

AF = (25/2+25)/100
      = 0.37

is that correct ?
```
Thanks

**Comment by tyyiyi** [comment]
Maybe you can see:
https://groups.google.com/forum/#!searchin/delly-users/AF%7Csort:date/delly-users/2voDbPk2HcE/gXPkVDhoAAAJ

It will give you answer.

**Comment by tobiasrausch** [comment]
Thanks, that's right:

VAF (variant allele frequency) = DV/(DR+DV) for imprecise variants and

VAF = RV/(RR+RV) for precise variants
