### ISSUE TITLE
somatic filtering ? 

### ISSUE THREAD

**Issue by tyyiyi** [dellytools/delly#147]
Hi,
I have run delly 0.7.6 call for del,dup,inv,tra and ins. And I meet the following trouble.

this is my line of script:
delly call -g hg38.fa -o 229del.bcf 229T_S2.bqsr.bam 229N_S1.bqsr.bam
delly filter -f somatic -o 229del.pre.bcf -s 229samples.tsv 229del.bcf

My samples.tsv file looks like this:
229T_S2 tumor
229N_S1 control

I use 
bcftools view 229del.bcf | grep -m 1 "^#CHROM"
show the header in my 229del.bcf file. It is:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  229T_S2 229N_S1

However ,I am getting an error message:
Sample type for 229T_S2 is neither tumor nor control
Is this caused by my use of BQSR files?

Can you help me solve this problem?

Thanks,
Tang

**Comment by tyyiyi** [comment]
I am sorry that I use the veision of delly is v0.7.6

**Comment by tobiasrausch** [comment]
Is that maybe a Windows/Linux line-ending issue. Can you try dos2unix samples.tsv ?

**Comment by tyyiyi** [comment]
Thank you for your help, I have solved it.

tang
