### ISSUE TITLE
delly 0.8.1 small indel calling

### ISSUE THREAD

**Issue by andurill** [dellytools/delly#148]
Hi @tobiasrausch ,
Thank you for releasing version 0.8.1. I noticed that small indel calling (-i) is not an option in this release. Will it no longer be a supported option in delly going forward? Thank you.

**Comment by tobiasrausch** [comment]
With v0.8.1 Delly always calls small deletions but only those that are flanked by soft-clipped reads. The main reason was improved speed. The former split-read refinement caused on some samples long runtimes, especially when I/O was slow.
