### ISSUE TITLE
Delly on bioconda for osx?

### ISSUE THREAD

**Issue by jodyphelan** [dellytools/delly#149]
Hi,

I was wondering if it was possilble or any plan to updae the recipe on bioconda to include osx? At the moment only linux is supported.

Jody

**Comment by tobiasrausch** [comment]
As far as I know people have successfully compiled delly on osx using brew to install boost.

**Comment by jodyphelan** [comment]
Yes I have been able to compile it on mac but I have a package which relies on delly in the bioconda recipe, however this won't work for mac as the dependancy is only satisfied for linux at the moment.

**Comment by tobiasrausch** [comment]
I see, I tried once to enable osx in the delly recipe on bioconda but that failed, which really might be due to my limited understanding of the bioconda build process.

**Comment by jodyphelan** [comment]
I've updated the recipe now and it should work for osx

**Comment by tobiasrausch** [comment]
@jodyphelan thanks a lot for updating the recipe for osx.
