### ISSUE TITLE
Locating these columns from output

### ISSUE THREAD

**Issue by beginner984** [dellytools/delly#152]
Sorry, I have called SV by delly and I converted the output to .vcf, is this any way to locate this information from output?

```
> head(sv_data)
     Sample Type CHROM_1    POS_1 CHROM_2     POS_2 Tumor_Varcount Tumor_Depth Normal_Depth Driver
1   CHC018T  BND    chr1   753734    chr8    327403             22          52          101   <NA>
2   CHC018T  BND    chr1   753747    chr8    327385             17          37          104   <NA>
3   CHC018T  BND    chr1 20344587    chr7   8707723             24         163           63   <NA>
```

Thank you so much

**Comment by tobiasrausch** [comment]
If you just want a tab-delimited table of all called delly SVs you can use [svprops](https://github.com/dellytools/svprops)

`svprops delly.output.bcf  > sv.table`

**Comment by beginner984** [comment]
Thank you I am on a public cluster system not my personal computer so how could I install svprops by this error

```
/usr/bin/ld: cannot find -llzma
collect2: ld returned 1 exit status
make: *** [src/svprops] Error 1
(/home/fi1d18/.conda/onco) [fi1d18@cyan01 svprops]$
```

**Comment by tobiasrausch** [comment]
As for delly, you need a couple system libraries to compile from source. Using Ubuntu:

`apt-get install -y build-essential g++ cmake zlib1g-dev libbz2-dev liblzma-dev libboost-all-dev`

**Comment by tobiasrausch** [comment]
Please re-open this issue if you still have installation problems. There is also a pre-installed [docker container](https://hub.docker.com/r/dellytools/delly/) for delly.
