### ISSUE TITLE
Unable to detect Tandem Duplications 

### ISSUE THREAD

**Issue by nkakkargit** [dellytools/delly#153]
Hello,

I have been using delly in conjunction with pindel and was a bit surprised to discover that delly was not able to call tandem duplications in any of the samples. These are true positive calls as we have verified them already and I wonder if you have any thoughts on what could be going on?

**Comment by tobiasrausch** [comment]
Are these maybe small tandem duplications <200bp? Delly is primarily for large somatic and germline SVs (>200bp) because it is using paired-end mapping.

**Comment by nkakkargit** [comment]
Hey Tobias,

Those are indeed small (~100)tandem duplications. Thanks for your prompt reply.
