### ISSUE TITLE
Delly finds identical deletions with different consensus sequences

### ISSUE THREAD

**Issue by chapplec** [dellytools/delly#154]
I am using delly to call structural variants on a human WGS sample. I noticed that it finds certain variants that are essentially duplicates. For example:

    chr4    177594033       DEL00005339     G       <DEL>   .       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr4;END=177594095;PE=0;MAPQ=0;CT=3to5;CIPOS=-3,3;CIEND=-3,3;SRMAPQ=60;INSLEN=0;HOMLEN=3;SR=5;SRQ=0.993243;CONSENSUS=GACAAAAACATATAAACAAATACAAATTATTATTATATGAAGGGTGAAAAATTATGTTCAGCTTTAATATTATGTGGCCTGAAACAAATTTGTATAAGTCATATGATCCGTTTTGTATATTCATTAAAATAGTCATAAAAATATAAAC;CE=1.75466     GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-51.3797,0,-42.791:10000:PASS:1115:1821:1820:1:0:0:23:27
    chr4    177594033       DEL00005340     G       <DEL>   .       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr4;END=177594095;PE=0;MAPQ=0;CT=3to5;CIPOS=-3,3;CIEND=-3,3;SRMAPQ=60;INSLEN=0;HOMLEN=3;SR=12;SRQ=0.994186;CONSENSUS=ATATAAACAAATACAAATTATTATTATATGAAGGGTGAAAAATTATGTTCAGCTTTAATATTATGTGGCCTGAAACAAATTTGTATAAGTCATATGATCCGTTTTGTATATTCATTAAAATAGTCATAAAAATATAAACAATGTAATAAGTATGTTTGAATAGTATTATGAT;CE=1.72637    GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-51.3797,0,-42.791:10000:PASS:1115:1821:1820:1:0:0:23:27
    
The two variants above have the same start position and the same end position (`END=177594095`). However, they differ in the `SR`, `SRQ` and `CONSENSUS` fields. These are defined in the VCF header as:

    ##INFO=<ID=SR,Number=1,Type=Integer,Description="Split-read support">
    ##INFO=<ID=SRQ,Number=1,Type=Float,Description="Split-read consensus alignment quality">
    ##INFO=<ID=CONSENSUS,Number=1,Type=String,Description="Split-read consensus sequence">
    
Of course, the consensus sequences are quite similar, but they aren't identical (I have simply added some spaces to the beginning of the 2nd sequence here to align them):

    GACAAAAACATATAAACAAATACAAATTATTATTATATGAAGGGTGAAAAATTATGTTCAGCTTTAATATTATGTGGCCTGAAACAAATTTGTATAAGTCATATGATCCGTTTTGTATATTCATTAAAATAGTCATAAAAATATAAAC
             ATATAAACAAATACAAATTATTATTATATGAAGGGTGAAAAATTATGTTCAGCTTTAATATTATGTGGCCTGAAACAAATTTGTATAAGTCATATGATCCGTTTTGTATATTCATTAAAATAGTCATAAAAATATAAACAATGTAATAAGTATGTTTGAATAGTATTATGAT

So what am I looking at here, exactly? If this is a deletion on chromosome 4 from position 177594033 to position 177594095, then how can the length of the consensus sequence be different? This is the "split read consensus", so presumably the sequence that appears to have been deleted based on how the reads covering that region are split. As I understand it, this means that these reads align to the genome with a gap and this gap indicates the deletion.

Therefore, if the start and end position are the same, the consensus should also be identical. And, in any case, if the start and end positions are the same, then this should be the same structural variant, so why is it being reported twice? How can I interpret this result?

  [1]: https://github.com/dellytools/delly/
  [2]: https://www.researchgate.net/figure/Five-approaches-to-detect-CNVs-from-NGS-short-reads-A-Paired-end-mapping-PEM-strategy_fig1_260376412
  [3]: https://i.stack.imgur.com/kodIq.png

**Comment by tobiasrausch** [comment]
Thanks for catching this subtle bug. I just fixed this in the latest [commit](https://github.com/dellytools/delly/commit/0fed1a17d0df1a085bdc9af73ae768bd74aab10a). These 2 calls are indeed the same SV which is evident from the genotyping where RR and RV are identical. delly merge takes care of such duplicates in v0.8.1 or you re-run with the latest code. Thanks.

**Comment by chapplec** [comment]
Great! Thanks for the quick fix. I am afraid I can't use delly merge since I am using delly to call SVs on single WGS samples. I will move to the next version then. 

Thanks again for the quick response.

**Comment by chapplec** [comment]
Yep, your fix seems to have sorted it out. Thanks!
