### ISSUE TITLE
explanation of different steps

### ISSUE THREAD

**Issue by Sames-Jtudd** [dellytools/delly#156]
Hi, 
Im using Delly2 for somatic SV calling all seems to be working fine. Nice tool. 

I just had a quick question or two regarding the third stage of the process;

"Genotype pre-filtered somatic sites across a larger panel of control samples to efficiently filter false postives and germline SVs. For performance reasons, this can be run in parallel for each sample of the control panel and you may want to combine multiple pre-filtered somatic site lists from multiple tumor samples.
delly call -g hg19.fa -v t1.pre.bcf -o geno.bcf -x hg19.excl tumor1.bam control1.bam ... controlN.bam"

It seems that this generates a combined bcf for the bam files provided, genotyped at the sites provided in the t1.pre.bcf file? Therefore this process is creating a panel of normals? 

Is it necessary to provide the tumour.bam? The program runs with just one input bam file. I ask because if you are providing multiple prefiltered somatic bcfs which one would you provide, surely not all?
If you parallelise the process and generate one geno.bcf for each control sample these must be merged, Im guessing Delly merge is the tool for the job?

best 

Jamie

Hope that all makes sense.

**Comment by tobiasrausch** [comment]
Delly merge is only for creating site lists that you then want to genotype with 

`delly call -v sites.bcf ...`

If you do the genotyping in parallel on multiple samples then you need to use 

`bcftools merge -m id ...`

afterwards to merge all the genotypes into a single BCF file. The somatic filtering against multiple control samples can then be achieved by specifying all control samples in the sample sheet using 

`delly filter -f somatic -s samples.tsv  ...`

**Comment by Sames-Jtudd** [comment]
thanks for the reply.
right I think I understand. Sorry one more question. 
Can you call the tumour and the normal samples separately. Given that Delly calls SVs naive to tumour normal status (that could conceivably influence assumptions about ploidy) could you do this? For cloud computing cost issues this would save me a lot of money.
 
delly call  -o tumour.bcf -g ref_genome.fa tumour.bam
delly call -g ref_genome.fa -v tumour.bcf -o normal.bcf normal_bam
bcftools merge tumour.bam normal_bam > merge.bcf
delly filter -f somatic -o somatic.bcf -s samples.tsv merge.bcf

would you expect the results to be different from calling the tumour/normals together?
I have done this on one sample and after filtering for PASS variants there were 181 SVs (joint call) vs 185 SVs (separate call) where there were +5 SVs in the separate call and one SV in the joint call that was not  in the separate call. 
thanks 
Jamie

**Comment by tobiasrausch** [comment]
Hi Jamie,

You can call only the tumor BAM file and then genotype the SVs in the control genome. That should be fine as long as you are only interested in somatic SVs.

Best, Tobias
