### ISSUE TITLE
how to make a XXX.excl.tsv from gff or other files for non-model animal which genomes is unable at chromosome level？

### ISSUE THREAD

**Issue by Yixiangzhang1996** [dellytools/delly#157]
how to make a XXX.excl.tsv from gff or other files for non-model animal which genomes is unable at chromosome level？

**Comment by tobiasrausch** [comment]
The exclude file is optional so you can run Delly without such an exclude file.

If your genome is present in UCSC you can download centromere and telomere regions using

[https://genome.ucsc.edu/FAQ/FAQtracks.html#tracks20](https://genome.ucsc.edu/FAQ/FAQtracks.html#tracks20)

These regions you should exclude for SV calling. 

If you are working on a draft genome assembly you should exclude all small contigs, possibly <10,000bp.

**Comment by Yixiangzhang1996** [comment]
> The exclude file is optional so you can run Delly without such an exclude file.
> 
> If your genome is present in UCSC you can download centromere and telomere regions using
> 
> https://genome.ucsc.edu/FAQ/FAQtracks.html#tracks20
> 
> These regions you should exclude for SV calling.
> 
> If you are working on a draft genome assembly you should exclude all small contigs, possibly <10,000bp.

Yep，thank u for your reply, I have run Delly without such an exclude file, and it works. I am searching a new genome's mutation. And thanks again,hhhhh......
