### ISSUE TITLE
delly merge argmax problem

### ISSUE THREAD

**Issue by holtgrewe** [dellytools/delly#158]
I'm running into an issue similar to but distinct from #94.

My command line is getting too long for the compiled-in command line length limit of the Linux kernel. Would it be possible to pass in a file that contains paths to BCF files for `delly merge`?

**Comment by tobiasrausch** [comment]
I agree, `delly merge` really needs a simple file with the list of all input BCF files to merge. I will work on this and that hopefully handles the command-line length problems and the ulimit problems with open file descriptors.

**Comment by tobiasrausch** [comment]
You can now use a list of files.

`delly merge foo/*.bcf`

or

`ls foo/*.bcf > list.tsv`
`delly merge list.tsv`

I am still working on the problem with too many open files.

**Comment by tobiasrausch** [comment]
Merging is now happening in groups of files for situations with more than 500 BCF input files.
