### ISSUE TITLE
Parallelize by chromosome

### ISSUE THREAD

**Issue by zamaudio** [dellytools/delly#161]
For WGS samples especially, it would be ideal to parallelise this program by chromosome.  Unfortunately, htslib does not allow you to pipe in a bam file without an index, so you can't just stream in a bam file restricted by chromosome to multiple instances of delly very easily.  That was the motivation for this idea.

**Comment by tobiasrausch** [comment]
Thanks for your code suggestions. I am currently traveling but I will try to review your code changes in the next ~2 weeks.

**Comment by tobiasrausch** [comment]
This does not work for inter-chromosomal translocations. It's fine for intra-chromosomal SVs but Delly is one of the few tools that tracks the paired-end qualities of the first and second read because many false positive translocations are due to repeats. If you stream a BAM the [first observed read of a paired-end](https://github.com/dellytools/delly/blob/master/src/tags.h#L243-L248) is always the one with smaller reference index but if you parallelize by chromosome you don't know if the other read of a paired-end has been observed already or not and hence, the quality information may be incorrect.

**Comment by zamaudio** [comment]
@tobiasrausch I now see that parallelising by chromosome would not work for a bam streamed in with no index.  However, in pull request #160  I do not change the process to use streaming, in fact I simply open the bam and index multiple times - 1x for each chromosome.  Since the threads are all sharing the memory for storing the intermediate results, it can be merged at the end without losing quality information.  The trick is to wrap the stdlib calls in `#pragma omp critical` sections so that the non-thread-safe memory operations are serialised across the threads.  By serialising these calls, the boost gained by parallelising is reduced, but still seems worth it if you time the whole process.  Please review the code again in case I missed something.

**Comment by tobiasrausch** [comment]
I fully understand but now each thread runs independently so you cannot control whether read1 or read2 is observed first for a translocation pair involving 2 different chromosomes and that changes the downstream results. If read2 is observed first, read1 will fall back to a default quality of 0. If read1 is observed first the actual quality of read1 will be taken into account to calculate the quality of the paired-end.

**Comment by zamaudio** [comment]
@tobiasrausch I don't fully understand the delly code, but can we perhaps pre-populate the quality of reads into a hash table in one parallel pass first (by chromosome), and then do another parallel pass to do the regular computation you describe above so that if read2 is observed first by one of the threads, the read1 data will already be populated and the quality of read1 will be taken into account in these cases.

**Comment by tobiasrausch** [comment]
Indeed, one would need additional code and data structures to handle these race conditions.
