### ISSUE TITLE
deletion called by delly without obvious drop in depth in graph

### ISSUE THREAD

**Issue by shannjiang** [dellytools/delly#162]
Hi,

I used delly to call structural variants on my WGS data. There is one deletion detected by delly interested me and I did cnv graphs by lowresbam2raster (http://lindenb.github.io/jvarkit/LowResBam2Raster.html) to visually check it:
![s1329_trio1_F_DNcnv_chr13_21736017-21742126](https://user-images.githubusercontent.com/31867080/60534072-a360d280-9cc6-11e9-835b-0dedef8ac822.png)
![s1329_trio1_C_DNcnv_chr13_21736017-21742126](https://user-images.githubusercontent.com/31867080/60534090-ae1b6780-9cc6-11e9-8587-c27aeb970140.png)

As shown in the two cnv graphs above, both of them are from the same region, and the second sample was identified to have a deletion here by DELLY with SR (supportive reads) value equal to 10 (WGS converage for these samples is 30X). Red arch lines are those split reads. But I didn't see an obvious coverage drop of the depth in the second graph when compared to the depth of the first graph (without deletion in the region).

My question is can I still consider it as a deletion even though without obvious drop in depth for the second graph? Attached please find the result by delly for the second sample.
[s1329_trio1_child_delly.txt](https://github.com/dellytools/delly/files/3351647/s1329_trio1_child_delly.txt)

thanks,

Shan

**Comment by tobiasrausch** [comment]
Delly calls paired-end/split-read clusters and it is true that many clusters will not necessarily represent simple deletions, simple duplications or simple inversions. A deletion-type paired-end cluster simply means that there is a deletion-type connection in the genome but especially in cancer these connections can span millions of bases without a drop in coverage, i.e. see [this paper](https://www.sciencedirect.com/science/article/pii/S0092867411015169) for some examples of complex deletion-type alterations.

**Comment by shannjiang** [comment]
@tobiasrausch Thanks for your immediate response. Can I think the deletion-type paired-end cluster a weak kind of deletion because there are still many reads span the area? Sorry for my bad description by weak deletion.

**Comment by tobiasrausch** [comment]
Paired-end/split-read clusters define how two double-strand breaks are repaired. If the segment in-between the breakpoints is lost, it's a classical deletion otherwise it's a more complex rearrangement.

**Comment by klbatcher** [comment]
I could be wrong but that could indicate a retrocopy insertion; It looks like a deletion because the introns have been removed/'deleted' in the retrocopy. No loss in coverage because there is no structural rearrangement at the endogenous gene (in fact you would see an increase in coverage over the exons)

I say this because if that data is alligned to hg19, the split reads seem to match up perfectly with SKA3 exons.
