### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kaji331** [dellytools/delly#163]
I used delly 0.8.1 to call SV from three bams separately. Then, I merged those three bcf files by delly. Finally, I can't filter merged bcf by delly. It told me segmentation fault (core dumped). I tried debug mode, but nothing else. I can filter one of three bcf files separately, but I can't find any SV even I know it has some. I have a small merged bcf file (< 200k) and I can't use dropbox or google. How can I send bcf to you or solve this? Thank you very much!

**Comment by tobiasrausch** [comment]
Can you please send me an email using the [EMBL web form](https://www-db.embl.de/EMBLPersonGroup-PersonPicture/MailForm/?recipient=CP-60010497). I can then arrange the file transfer and see if that is a bug. Thanks.

**Comment by kaji331** [comment]
> Can you please send me an email using the [EMBL web form](https://www-db.embl.de/EMBLPersonGroup-PersonPicture/MailForm/?recipient=CP-60010497). I can then arrange the file transfer and see if that is a bug. Thanks.

[delly_test_chd001_merged_filtered.zip](https://github.com/dellytools/delly/files/3367526/delly_test_chd001_merged_filtered.zip)
I can't find how to add an attachment in the [EMBL web form](https://www-db.embl.de/EMBLPersonGroup-PersonPicture/MailForm/?recipient=CP-60010497). I just find I can attach it in github. Thank you.

**Comment by tobiasrausch** [comment]
That's a corrupted BCF file. If you do

bcftools view delly_test_chd001_merged_filtered.bcf 

you can see that EOF marker is missing and BCF header cannot be read.

**Comment by kaji331** [comment]
> That's a corrupted BCF file. If you do
> 
> bcftools view delly_test_chd001_merged_filtered.bcf
> 
> you can see that EOF marker is missing and BCF header cannot be read.

I am very sorry to attach a wrong file. That file is the corrupted file resulted by "delly filter" segmentation fault. 
[delly_test_chd001_merged.zip](https://github.com/dellytools/delly/files/3390919/delly_test_chd001_merged.zip)
This attachment is the real bcf file after "delly call" and "delly merge".

**Comment by tobiasrausch** [comment]
As explained in the [README](https://github.com/dellytools/delly), `delly merge` creates a unified site list without genotypes. This site list you need to re-genotype across all your samples and then you merge all genotypes using bcftools merge. You cannot filter a site list with `delly filter` because there are no genotypes. I added now a more telling error message to `delly filter` if it used with a VCF without genotypes.
