### ISSUE TITLE
problem for ultra-low coverage wgs data

### ISSUE THREAD

**Issue by N-damo** [dellytools/delly#167]
Hi,
I ran 100 ultra-low coverage whole-genome sequences (average 3x) together using Delly to find ***germline sv***. The pipeline is clear for high-coverage wgs data in readme.md, but I not sure with low coverage data.
Is correct if I use the following pipeline ?
`delly call -g hg38.fa -x hg38.tsv -o sv.bcf s1.bam s2.bam ...s100.bam`
`delly filter -f germline -p -o germline.bcf sv.bcf`
best regards
LianLin

**Comment by tobiasrausch** [comment]
Yes, that should be fine for very low coverage data. If it takes too long to compute you can also run in 2 or 3 batches of files.
