### ISSUE TITLE
filter unable open bam file(bcftools merge)

### ISSUE THREAD

**Issue by luben007** [dellytools/delly#168]
Dear developers:
Hi
This is my first time to do sv analysis. I have three normal genomes and three patient genomes, and each genome data is about 40G. I hope to find out the specific sv results (somatic cells) of patients.
The first time I followed the instructions and ran delly:
`delly call -x hg38.excl -o all.bcf -g hg38.fa tumor1.bam tumor2.bam tumor3.bam control1.bam control2.bam control3.bam`
Delly stopped at the SV annotation step for 50 hour, so I stopped delly.

The second time I run single sample:
```
delly call -x hg38.excl -o tumor1.bcf -g hg38.fa tumor1.bam
delly call -x hg38.excl -o tumor2.bcf -g hg38.fa tumor2.bam
delly call -x hg38.excl -o tumor3.bcf -g hg38.fa tumor3.bam
delly call -x hg38.excl -o control1.bcf -g hg38.fa control1.bam
delly call -x hg38.excl -o control2.bcf -g hg38.fa control2.bam
delly call -x hg38.excl -o control3.bcf -g hg38.fa control3.bam
```

I'm going to merge and run filter step in the instructions, such as "`delly filter -f somatic -o t1.somatic.bcf -s samples.tsv geno.bcf`":
`bcftools merge -m id -O b -o all.merge.vcf tumor1.bcf tumor2.bcf tumor3.bcf control1.bcf control2.bcf control3.bcf`

"all.bcf" file is generated by merging ,but I did not find "all.bcf.csi"
`delly filter -f somatic -o all.somatic.bcf -s samples.tsv all.merge.vcf`

samples.tsv：
tumor1 tumor
tumor2 tumor
tumor3 tumor
control1 control
control2 control
control3 control

Appear error：
`Fail to open index file for all.merge.vcf`

I don't know what's wrong, could you give me some advice?
Thank you very  much.  @jvhaarst @smoe @mhyfritz @meiers @tobiasrausch 

Guan Xiaoyu

**Comment by tobiasrausch** [comment]
If you have 3 patients you should run the tumor and normal together, i.e.:

`delly call -x hg38.excl -o tumor1.bcf -g hg38.fa patient1_tumor1.bam patient1_control1.bam`

`delly call -x hg38.excl -o tumor1.bcf -g hg38.fa patient2_tumor2.bam patient2_control2.bam`

**Comment by luben007** [comment]
> If you have 3 patients you should run the tumor and normal together, i.e.:
> 
> `delly call -x hg38.excl -o tumor1.bcf -g hg38.fa patient1_tumor1.bam patient1_control1.bam`
> 
> `delly call -x hg38.excl -o tumor2.bcf -g hg38.fa patient2_tumor2.bam patient2_control2.bam`
> 
> `delly call -x hg38.excl -o tumor3.bcf -g hg38.fa patient3_tumor3.bam patient3_control3.bam`

Thank you for your reply, but I don't think A and three B can be analyzed together in this way.
I saw the standard 4 steps in the "Somatic SV calling" part of the README.md for a more accurate analysis.
I happen to have three normal controls, so I intend to run the standard four steps for each patient:

> ```
> delly call -x hg38.excl -o t1.bcf -g hg38.fa tumor1.bam control1.bam
> delly filter -f somatic -o t1.pre.bcf -s samples.tsv t1.bcf
> delly call -g hg38.fa -v t1.pre.bcf -o geno.bcf -x hg38.excl tumor1.bam control1.bam control2.bam control3.bam
> delly filter -f somatic -o t1.somatic.bcf -s samples.tsv geno.bcf
> ```

Do you think I need to do that?If the difference is not big, I prefer the step you gave me, because the running time is short.
Thank you again :-) @tobiasrausch

**Comment by tobiasrausch** [comment]
If you have only 3 controls you can just do the pairwise setup with tumor against matched control.
