### ISSUE TITLE
Deletion-calling abnormality in  chr 2 of human

### ISSUE THREAD

**Issue by Biolixue** [dellytools/delly#171]
Hi 
    There is a series of abnormal deletion on chromosome 2 for all my samples,  many DEL share same start position and determined to Lowquality, and the length is almost 170M+,This phenomenon occurs specifically on human chromosome 2, I think this is abnormal.
![image](https://user-images.githubusercontent.com/41618134/66378433-0361c600-e9e6-11e9-9730-dde011d2f8f3.png)
    My command is : 
DELLY_v0.7.3 call \
-g human_g1k_v37_decoy.fasta \
-t DEL \
-q 30 \
-n \
-i 50 \
-u 20 \
-o test.delly.del.bcf \
test.final.bam
    What are some of the potential problems and how to fix it please?
I really hope to get your help!

Thanks

**Comment by tobiasrausch** [comment]
Is this still an issue with the latest Delly version v0.8.1?

**Comment by Biolixue** [comment]
Hi，
    This still an issue with the latest Delly version v0.8.1.
![image](https://user-images.githubusercontent.com/41618134/66564509-bcfd9a00-eb92-11e9-9ad4-58d89369156b.png)

**Comment by Biolixue** [comment]
Hi,
    Is there any update?

**Comment by tobiasrausch** [comment]
We haven't seen this in other samples so I would assume there is some true biology going on there. Probably a repetitive region and that's why there are so many SVs. Have you checked if there is a decrease or increase in read-depth at the location or maybe a mobile element that got somatically transposed?

**Comment by tobiasrausch** [comment]
Hi,

Sorry for my late reply. I looked at this across a larger number of samples and it indeed seems to be a problematic region for short-read SV calling. I added it to the default exclude file. Thanks for pointing out that region.

[Low complexity region](https://github.com/dellytools/delly/blob/master/excludeTemplates/human.hg19.excl.tsv#L33-L33)

Best, Tobias
