### ISSUE TITLE
Delly crashing when running multiple delly processes in parallel

### ISSUE THREAD

**Issue by gevro** [dellytools/delly#172]
Hi, Delly is crashing strangely (with just a linux kernel "killed" indication) when running a few or more delly processes in parallel.

For example this will lead one of the processes to sometimes (though not always) to be killed spontaneously.
delly call -x human.hg38.delly.excl.tsv -t INV -o blah.delly.inversion.bcf -g ref.fa chr.2.bam & delly call -x human.hg38.delly.excl.tsv -t DEL -o blah2.delly.inversion.bcf -g ref.fa chr.2.bam & delly call -x human.hg38.delly.excl.tsv -t DUP -o blah3.delly.inversion.bcf -g ref.fa chr.2.bam &

But running them serially has no issues at all.

I suspect it is some strange conflict between the multi-threading that delly does with the kernel. Also note, I'm running this within a docker shell, but that shouldn't affect things.

**Comment by tobiasrausch** [comment]
"killed" messages from the linux kernel often happen if the memory is exhausted. Each single CPU Delly job needs ~8G RAM so you should have at least n * 8G RAM for n parallel jobs.

**Comment by tobiasrausch** [comment]
I assume this was a memory issue, please re-open the ticket if that's still a problem.
