### ISSUE TITLE
problems with dellytools/delly image 

### ISSUE THREAD

**Issue by zzygyx9119** [dellytools/delly#174]
when I did "docker pull dellytools/delly", the image I got apparently doesn't work since the command "docker run -it dellytools/delly ls -al" failed to show any contents in this image.

so, I download the Dockerfile, and tried to build the image from beginning. Then I got the following error:

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/b/bzip2/bzip2_1.0.6-5ubuntu0.1~esm2_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/b/bzip2/libbz2-1.0_1.0.6-5ubuntu0.1~esm2_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/liba/libarchive/libarchive13_3.1.2-7ubuntu2.8+esm1_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3_7.35.0-1ubuntu2.20+esm3_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/h/hdf5/libhdf5-7_1.8.11-5ubuntu7.1+esm1_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/p/patch/patch_2.7.1-4ubuntu2.4+esm1_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-175.226_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/h/hdf5/hdf5-helpers_1.8.11-5ubuntu7.1+esm1_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/h/hdf5/hdf5-tools_1.8.11-5ubuntu7.1+esm1_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/b/bzip2/libbz2-dev_1.0.6-5ubuntu0.1~esm2_amd64.deb  HttpError401

E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/h/hdf5/libhdf5-dev_1.8.11-5ubuntu7.1+esm1_amd64.deb  HttpError401

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 76.3 MB in 52s (1454 kB/s)
The command '/bin/sh -c apt-get update && apt-get install -y     build-essential     cmake     g++     gfortran     git     hdf5-tools     libboost-date-time-dev     libboost-program-options-dev     libboost-system-dev     libboost-filesystem-dev     libboost-iostreams-dev     libbz2-dev     libhdf5-dev     libncurses-dev     liblzma-dev     zlib1g-dev     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

Would you please let me know how to solve the issue? Thank you!

Jeff

**Comment by tobiasrausch** [comment]
Hi Jeff,

The container starts by default a shell

`docker run -it dellytools/delly`

Inside the container you can then execute delly as explained in the [README](https://github.com/dellytools/delly/blob/master/docker/README.md)

**Comment by zzygyx9119** [comment]
Hi Tobias,

Thank you for your quick response. I haven't done test run of "delly", however, I noticed that the size of the delly image is very small (12.2M). Is this normal? I am also interested in inspecting what's inside this image, that's why I was surprised to find that there is nothing inside.

Best,

Jeff

**Comment by tobiasrausch** [comment]
Yes, that's fine. We use the very small alpine image and copy a static binary of delly inside the container. That's all but a simple `delly` should work inside the container.

**Comment by tobiasrausch** [comment]
We can also provide a singularity container if that is more convenient for you?

**Comment by zzygyx9119** [comment]
Hi Tobias,

Thank you so much for detailed explanation! It would be great if you can provide a singularity container.

Best,

Jeff

**Comment by tobiasrausch** [comment]
Hi Jeff,

Added a singularity container (*.sif file) to the [latest delly release](https://github.com/dellytools/delly/releases/tag/v0.8.1).

The [README](https://github.com/dellytools/delly/tree/master/singularity) explains how to run the singularity container.

Best, Tobias

**Comment by zzygyx9119** [comment]
Hi Tobias,

Thank you so much for your great help!

Best, 

Jeff
