### ISSUE TITLE
Somatic SV Calling in step3

### ISSUE THREAD

**Issue by tyyiyi** [dellytools/delly#175]
Hi,tobiasrausch
I have nearly 50 groups of tumor-normal paired samples, all of which have WES depths averaged around 500X.I have run delly 0.8.1 call for all([DEL, INS, DUP, INV, BND). And I meet the following trouble.
this is my line of script:
delly call -g hg38.fa -x  hg38.excl  -o t1.bcf tumor1.MarkDuplicates.bam normal1.MarkDuplicates.bam
delly filter -f somatic -a 0.05 -o t1.pre.bcf -s samples1.tsv t1.bcf

According to the Somatic SV calling in README, the next step needs to be:
Genotype pre-filtered somatic sites across a larger panel of control samples to efficiently filter false postives and germline SVs. For performance reasons, this can be run in parallel for each sample of the control panel and you may want to combine multiple pre-filtered somatic site lists from multiple tumor samples.
However, I don't understand the significance of this step well. Is he trying to build a large panel of normal samples? Do I need to do the following for each tumor sample? such as:
delly call -g hg38.fa -v t1.pre.bcf -o geno1.bcf -x hg38.excl tumor1.bam control1.bam ... controlN.bam
delly call -g hg38.fa -v t2.pre.bcf -o geno2.bcf -x hg38.excl tumor2.bam control1.bam ... controlN.bam
delly call -g hg38.fa -v t3.pre.bcf -o geno3.bcf -x hg38.excl tumor3.bam control1.bam ... controlN.bam
……

Is there any way to complete this step at once? Without having to run this step almost 50 times?And can I not do the next two steps? If I only run to pre-filter, will this affect me a lot? Will there be too many false positives and germline SVs?

Thanks,
Tang

**Comment by tyyiyi** [comment]
what is ontrol1.bam ... controlN.bam? All normal samples?

**Comment by tobiasrausch** [comment]
You can stop after the somatic filtering against the matched control because for WES data you anyway only catch SVs in genic regions which are less repetitive. For WES data, I would rather recommend to filter for somatic INFO/PRECISE variants only and then you can check by coordinate if these have been called in any of the other control samples. So no need to run the re-genotyping against all controls for WES, I think.
