### ISSUE TITLE
SV genotyping

### ISSUE THREAD

**Issue by zhiquanyang** [dellytools/delly#176]
Hello!
I want to use vcf file from Sniffies to do genotyping using delly. But I didn't get any insertion. I think there are some problems in Sniffies vcf format. So could tell me which infomation is necessary in vcf file? The following is vcf files of Sniffies and delly.
Sniffies:
C09     68326871        182205  N       CTCACTCTCCTCTATATCTCGTATGGGTTTTTTTTAAGAATACATATATATATATAGTTATATAGAAATGTGAA      .       PASS    SUPP=9;SUPP_VEC=111111111;SVLEN=74;SVTYPE=INS;SVMETHOD=SURVIVOR1.0.7;CHR2=scaffoldC09;END=68326944;CIPOS=0,0;CIEND=0,0;STRANDS=+-      GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO    1/1:NA:74:6,55:+-:.:INS:182205:N:CTAACTCTCTCTATATATCGTAAAGTTTTTTAAGAATACATATTTATATATAAATATATATATATGTGAA

delly:
C09     12141876        INS00000042     A       <INS>   .       PASS    PRECISE;SVTYPE=INS;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=scaffoldC09;END=12141877;PE=0;MAPQ=0;CT=NtoN;CIPOS=-5,5;CIEND=-5,5;SRMAPQ=60;INSLEN=53;HOMLEN=4;SR=5;SRQ=0.979381;CONSENSUS=GAGTTCAAGTGTGAAGGTGAGGAAAGCCTACAACGAGTCTTGGACAACAGACCGTATCACTTTGAGTACTGGATGGTGATACTCCGGGAACCGGTCATATCAGACACCTTCCCTGCAATGATACCCTTCTGGATACTCATAAAATGGCTA;CE=1.99266       GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV  0/0:0,-3.00925,-37.699:30:PASS:6159:13031:6867:2:0:0:10:0
yangzhiquan

**Comment by tobiasrausch** [comment]
I am sorry but I simply do lack time to implement support in delly for genotyping the output of other SV calling tools. For insertions, delly is very limited because I do require reads to span the entire insertion.
