### ISSUE TITLE
Reference file is missing: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JINPENG-WANG** [dellytools/delly#179]
I got the error message "Reference file is missing: Segmentation fault (core dumped)" when run delly with the command: "delly call -o Sample.bcf -g Ref.fa Sort.bam". 
 Can anybody help ?

**Comment by tobiasrausch** [comment]
Looks like your reference does not exist or is empty. Try:

`ls Ref.fa`

**Comment by JINPENG-WANG** [comment]
> Looks like your reference does not exist or is empty. Try:
> 
> `ls Ref.fa`

The reference exists and is indexed with "bwa index".

**Comment by tobiasrausch** [comment]
Hmm, not clear to me. This error message is simply thrown when the filesystem check fails. I basically check for file exists, file is a regular file (not a directory) and the file size is non-zero. Even more strange is that you then get a segfault which would mean the variable has not been initialized. Have you compiled yourself from source?

**Comment by JINPENG-WANG** [comment]
I installed delly with the following command: 

git clone --recursive https://github.com/dellytools/delly.git
cd delly/
make all

**Comment by JINPENG-WANG** [comment]
I got the following warnings when install delly:  
In file included from src/delly.h:61:0,
                 from src/delly.cpp:38:
src/modvcf.h: In function ‘void torali::vcfOutput(const TConfig&, const std::vector<Property>&, const TJunctionCountMap&, const TReadCountMap&, const TCountMap&) [with TConfig = torali::Config; TStructuralVariantRecord = torali::StructuralVariantRecord; TJunctionCountMap = std::vector<std::vector<torali::JunctionCount> >; TReadCountMap = std::vector<std::vector<torali::ReadCount> >; TCountMap = std::vector<std::vector<torali::SpanningCount> >]’:
src/modvcf.h:477:3: warning: ignoring return value of ‘int bcf_hdr_write(htsFile*, bcf_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   bcf_hdr_write(fp, hdr);
   ^
In file included from src/delly.cpp:39:0:
src/filter.h: In function ‘int torali::filterRun(const TFilterConfig&) [with TFilterConfig = torali::FilterConfig]’:
src/filter.h:108:3: warning: ignoring return value of ‘int bcf_hdr_write(htsFile*, bcf_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   bcf_hdr_write(ofile, hdr_out);
   ^
In file included from src/delly.cpp:40:0:
src/merge.h: In function ‘void torali::_outputSelectedIntervals(torali::MergeConfig&, const TGenomeIntervals&, TContigMap&, int32_t) [with TGenomeIntervals = std::vector<std::vector<torali::IntervalScore> >; TContigMap = std::map<std::basic_string<char>, unsigned int>; int32_t = int ’:
src/merge.h:308:3: warning: ignoring return value of ‘int bcf_hdr_write(htsFile*, bcf_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   bcf_hdr_write(fp, hdr_out);
   ^
src/merge.h:330:5: warning: ignoring return value of ‘int bcf_hdr_set_samples(bcf_hdr_t*, const char*, int)’, declared with attribute warn_unused_result [-Wunused-result]
     bcf_hdr_set_samples(hdr[file_c], NULL, false); // Do not read the sample information
     ^
In file included from src/delly.cpp:40:0:
src/merge.h: In function ‘void torali::mergeBCFs(torali::MergeConfig&, const std::vector<boost::filesystem::path>&)’:
src/merge.h:592:29: warning: ignoring return value of ‘int bcf_hdr_write(htsFile*, bcf_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   bcf_hdr_write(fp, hdr_out);
                             ^
src/merge.h:605:38: warning: ignoring return value of ‘int bcf_write(htsFile*, bcf_hdr_t*, bcf1_t*)’, declared with attribute warn_unused_result [-Wunused-result]
     bcf_write1(fp, hdr_out, rec[idx]);
                                      ^

**Comment by tobiasrausch** [comment]
I suspect an outdated system library for boost. Have you tried the static binary or bioconda?

**Comment by JINPENG-WANG** [comment]
> I suspect an outdated system library for boost. Have you tried the static binary or bioconda?

Thanks a lot. I installed it with bioconda and it works!

**Comment by tobiasrausch** [comment]
Great, thanks for letting me know.
