### ISSUE TITLE
0.8.2 does not compile with gcc 9.2.0

### ISSUE THREAD

**Issue by jbedo** [dellytools/delly#180]
Type errors are thrown around the use of std::max and std::min. Log attached, htslib version 1.10.2.

[delly.log](https://github.com/dellytools/delly/files/4175491/delly.log)

**Comment by tobiasrausch** [comment]
Thanks. Delly previously used htslib 1.9 as a submodule and apparently upgrading to 1.10.2 created these issues. We fixed these incompatibilities and also added gcc 9.2 to our CI testing.

[https://travis-ci.org/dellytools/delly](https://travis-ci.org/dellytools/delly)

Should be fine now, please let us know if you still run into compile issues.

**Comment by jbedo** [comment]
Confirmed 0e5c710 resolves this issue; thanks!
