### ISSUE TITLE
'-i ' option is not added in this version?

### ISSUE THREAD

**Issue by pyc1216** [dellytools/delly#181]
I saw **Delly also supports calling of small InDels using soft-clipped reads only (-i option). In this mode the smallest SV size called is 15bp.** in FAQ
my version is 0.8.2
my cmd is:
_export OMP_NUM_THREADS=2 && /data_sas/ypu/git_repository/delly/delly_v0.8.2_linux_x86_64bit call -q 20 -s 15 -x /home/ypu/4-Ref/bed/Med1CDx/excludeTemplates/human.hg19.excl.tsv -o call/sv.bcf -g /home/ypu/4-Ref/hg19/ucsc.hg19.fasta -i bam/tumor.sort.mkdup.bam bam/normal.sort.mkdup.bam_

the error is:
_terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '-i'
Aborted_

It seems '-i ' option is not added in this version?

**Comment by tobiasrausch** [comment]
'-i' is deprecated. Delly always calls small deletions now, you don't need to specify -i
