### ISSUE TITLE
Correct name of this software?

### ISSUE THREAD

**Issue by asp8200** [dellytools/delly#182]
Is this software to be referred to as "Delly" or "Delly2"? I only found it referred to as "Delly" in one place:

![image](https://user-images.githubusercontent.com/37172585/75029355-32af3600-54a2-11ea-9bf3-82afd6e3faae.png)

**Comment by tobiasrausch** [comment]
Just "Delly" is fine. We once had the plan to submit a follow-up publication describing all the new features that were added over the years but we so far didn't get to that.

[https://doi.org/10.1093/bioinformatics/bts378](https://doi.org/10.1093/bioinformatics/bts378)
