### ISSUE TITLE
Unable to detect any SVs

### ISSUE THREAD

**Issue by soungalo** [dellytools/delly#184]
Hello,
I am trying DELLY v0.8.2 for the first time, using ~x40 coverage data on a plant genome. The bam file was obtained by running bwa mem, then sorting and indexing the result.
I am using default params for DELLY. My run results in a bcf file with no data (i.e. header is present, but no variants detected) and prints the following message to stdout:
Sample:SRR1945819_map_to_pan.sort,ReadSize=51,Median=407,MAD=11,UniqueDiscordantPairs=230596
I find it very unlikely that there are no SVs between my sample and the reference, so I guess something is wrong with my data or the way I use DELLY.
Any ideas on what might be going wrong?
Thanks!

**Comment by soungalo** [comment]
OK, this is a bit embarrassing, but turns out the problem was not with DELLY, but rather with bcftools. Turns out I was using a very old version (0.1.19) that apparently can't read the new bcf. Once upgraded to 1.10.2, I am now able to read the output bcf, which is not empty at all.

**Comment by tobiasrausch** [comment]
No worries, thanks for letting me know.

**Comment by 18parkky** [comment]
I had an identical phenomenon but my bcftools version was up to date. I'm not sure why but switching from bowtie2 to minimap2 fixed it 👍
