### ISSUE TITLE
Metric for evaluating the confidence of CNV variants

### ISSUE THREAD

**Issue by HyunjunNam** [dellytools/delly#185]
Hi,

Can I use GQ score as a metric for evaluating the confidence of CNV variants? If I can, is there any minimum cutoff for it?

Thanks,

**Comment by tobiasrausch** [comment]
Delly calls structural variants using paired-end mapping and split-reads. The format CN field is useful for simple deletions and duplications but GQ has absolutely no relation to CN. GQ is derived from the genotype likelihoods (GLs) and the GLs are derived from the paired-end and split-read support for REF and ALT alleles of a structural variant prediction.
