### ISSUE TITLE
What version of boost does delly expect?

### ISSUE THREAD

**Issue by tseemann** [dellytools/delly#188]
```
boost/progress.hpp:23:136: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> or <boost/timer/progress_display.hpp> instead.
In file included from iinclude/boost/progress.hpp:25:0,
                 from src/delly.h:26,
                 from src/delly.cpp:17:
boost/timer.hpp:21:98: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
In file included from src/delly.h:36:0,
                 from src/delly.cpp:17:
```

quite a few of these warnings with boost 1.72

**Comment by tobiasrausch** [comment]
'-v' lists also the htslib and boost library versions for the [static binaries](https://github.com/dellytools/delly/releases) and bioconda package available for delly.

`delly_v0.8.2_linux_x86_64bit -v`
Delly version: v0.8.2
 using Boost: v1.65.1
 using HTSlib: v1.6

The bioconda version uses Boost v1.70.  

Many HPCs still use CentOS 7 (boost 1.53 as the default) which makes it difficult to update to the latest boost version. These are just deprecation warnings so the code should still be fine for the time being.

**Comment by tseemann** [comment]
Thanks - I am attempting to package it for Homebrew. Having some challenges. Will try 0.8.3
