### ISSUE TITLE
Question about somatic SV calling

### ISSUE THREAD

**Issue by lh12565** [dellytools/delly#190]
Hi, 

I'm a little confused about somatic SV calling. Does the result of somatic SV calling include both  true sv of  tumor sample and a matched control sample, or only true sv of tumor sample in tumor column and false sv in normal column. Thanks!

**Comment by tobiasrausch** [comment]
The [README](https://github.com/dellytools/delly/blob/master/README.md) includes a section on somatic SV calling.
