### ISSUE TITLE
Multiple questions about inversion

### ISSUE THREAD

**Issue by ptranvan** [dellytools/delly#191]
Hi @tobiasrausch, 

Thanks for your software. I am looking for inversions breakpoints between 2 haplotypes. I have a reference genome for haplotype 1 (homozygote) and WGS samples for haplotype 2 (homozygote) . 
I have used bwa-mem and I have mark duplicate my samples before using Delly. I have a few questions:

1) For now I am looking one by one the sample because I have 15 samples: it's not possible to run the somatic and/or germline pipeline with that amount of sample right ?

2) I am filtering the result by keeping `PASS`, `PRECISE` and `1/1`. Is it a good filtering or I might miss some inversions?
How are computed `PASS` and `PRECISE` ?

Based on this result:

`Scaffold03	7600386	INV00001054	T	<INV>	209	PASS	PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.8.3;END=9802651;PE=2;MAPQ=10;CT=5to5;CIPOS=-10,10;CIEND=-10,10;SRMAPQ=60;INSLEN=0;HOMLEN=9;SR=4;SRQ=0.98913;CONSENSUS=GGGTGCTCTTATTGCTACTTCTATCTTACAATATGGTTCGACAATAATATTTAGTAAAGTGAGAAATATATATCCTATAATATCAATCCTAT;CE=1.85587	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-18.132,-2.4413,0:24:PASS:25114:131670:78351:3:0:2:0:9`

3)  The 6th column (before PASS) is the score ?

4) I am not sure if my interpretation is right: here I found an inversion at the breakpoint position `7600386` and `9802651` in the reference genome right ?

5) What is the consensus sequence ?

Thanks a lot for your answers.

**Comment by tobiasrausch** [comment]
(1) For human, 15 WGS samples at deep coverage is indeed too much for a single run.
(2) If you expect hom. inversions that's fine.
(3) Yes.
(4) It's an inversion-type connection (CT=5to5) from 7600386 to 9802651.
(5) The assembled breakpoint sequence from all split-reads. If you BLAT that sequence you should recover an inversion-type alignment.

**Comment by ptranvan** [comment]
(1) I am confused, I would think the contrary because in your guide you said `Apply the germline SV filter which requires at least 20 unrelated samples` so 15 samples it's too low no ?

(2) What are the tresholds to say that a variant is `PASS` and `PRECISE` ?

(4) Could you explain `inversion-type connection (CT=5to5)` please ?

**Comment by tobiasrausch** [comment]
Sorry, (1) was a misunderstanding. I thought you are asking about running 15 samples jointly with delly (delly accepts multiple BAMs). That's a bit too much but for germline filtering more samples are indeed better. (2) and (3) have been answered previously in the delly user group.

[https://groups.google.com/forum/#!forum/delly-users](delly-user group)
