### ISSUE TITLE
BAM file chromosome chrEBV is NOT present in your reference file

### ISSUE THREAD

**Issue by Parsoa** [dellytools/delly#192]
I get the above error when trying to run Delly on a sample (NA19240 from 1KG). The sample has no reads mapped to chrEBV but some have secondary alignments to chrEBV. I have excluded chrEBV for Delly with the -x option however I'm still getting this error as my reference file (GRCh38) doesn't include the Epstein-Barr Virus. How can I fix this without remapping the file?

**Comment by tobiasrausch** [comment]
The 1000 Genomes GRCh38 reference file includes decoy sequences and chrEBV:

[ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/
](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/)
