### ISSUE TITLE
recommended aligner tool and settings

### ISSUE THREAD

**Issue by dcopetti** [dellytools/delly#196]
Hello,

I would like to run delly with long (ONT) and short (Illumina PE) reads to detect Svs.
I wonder if you have any recommended software (and parameters, in case) to use to generate the input bam for either dataset.
My reference is >4 Gb in size, is there any recommendation you have for repeat-rich plant genomes?
Thanks,
Dario

**Comment by tobiasrausch** [comment]
For illumina PE data we usually use bwa mem and for ONT minimap2.
