### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ghost** [dellytools/delly#2]
Hi

When I tried to run the latest version (cloned the git repo) of delly with 3 bacterial genomes, I got a segmentation fault. This isn't a very large genome ~ 6MB and the BAM files ~ 1GB

delly-0.1.2 -t DEL -o Exp6_LJF.del.vcf -g RefSeq-Pseudomonas_aeruginosa_PA01.genomic.fna Exp6_LJF_ampXPA01.merged.sorted.bam Exp6_LJF_B5a.merged.sorted.bam Exp6_LJF_A4a.merged.sorted.bam

[2013-Dec-07 14:54:19] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

---

Segmentation fault (core dumped)

Here's some specs on the machine running it..
RedHat 6.4, x86_64, 24 CPUs, 48 GB of RAM

cheers
steve

**Comment by jiangao** [comment]
Hi tobiasrausch,
    I am also getting the same problems titled"  segmentation fault(core dumped)" , I am not sure how to solve this problem, I get the Delly software from github! Thanks a lot

**Comment by tobiasrausch** [comment]
Hi,

Delly needs indexed and sorted bam files. The above usually happens if the index file is missing, still need to add a more telling error message for this.

-Tobias

**Comment by ariverosw** [comment]
Hi Tobias,

I'm facing the same problem. I ran the program with a 4 genomes (test run) and it worked, but then I tried with the 48 I have and got this error message.

line 24:  2680 Segmentation fault      (core dumped) delly

I then downsize to 40, 30, 25 and the result was the same. Segmentation fault. Do you think it might be memory? Since normally a segmentation error is often associated with ram ...

Thanks!!!

Alejandro

**Comment by tobiasrausch** [comment]
Could be indeed a memory problem. With Delly you can always call SVs in small batches (e.g., 5 samples), then merge all SV sites from all samples (48 in your case) and then re-genotype this merged site list across all samples.

-Tobias

**Comment by ariverosw** [comment]
I made some modifications in the bash script and now it works with all the
48 genomes at the same time. Unfortunately because of the way I made the
modification and the fact that two of my samples (bam files) did not have
the indexes , now I'm not completely sure of what was the issue.
Thanks Tobias for the reply!!!
Alejandro

**Comment by pliang64** [comment]
I am also running into the segmental fault issues.  In my case, I have a set of wgs file running all 5 types of SV detection. Most of the files were processed successfully. A few of the files had the segmental fault problems, mostly with the DUP program.  Just to be clear, for these few problematic files,  analysis with other program (DEL, TRA, INS, INV) finished fine with the same input files, but just DUP failed on segmental fault. So I don't think it is a problem associated with the index files.  I tried to run it on different systems, all with lots of memory (one with >1TB) and it is the same.  It generated the bcf file but not the csi file. Below are the content of the log file from &> for one of the run.  Any suggestions? It is safe to use the bcf file generated?

Thanks,
Ping

[2016-Jul-06 03:26:21] delly call -t DUP -g /work/lianglab/DB/genomeSeq/hg19.fa -x /home/pliang/DB/genomeSeq/hg19/human.hg19.excl.tsv -o dup.15492-26109.bcf 15492-26109.bam 
[2016-Jul-06 03:27:09] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************[2016-Jul-06 03:54:54] Split-read alignment

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************[2016-Jul-06 05:12:01] Junction read annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************[2016-Jul-06 05:18:16] Breakpoint spanning coverage annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2016-Jul-06 06:16:21] Read-depth annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2016-Jul-06 08:08:14] Genotyping

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

[pliang@cop33 ASD_Delly]$ -bash: line 11: 20446 Segmentation fault

**Comment by pliang64** [comment]
Further info to my above post, I can view the bcf file with bcftools, but when I tried to build the index for the bcf file, I got the following.

[pliang@cop33 ASD_Delly]$ bcftools index -c dup.1548-22146.bcf
Segmentation fault

**Comment by tobiasrausch** [comment]
You can run Delly in Debug mode using

make DEBUG=1 src/delly

This can be very slow if you have a large BAM file. If you can re-produce
the error on a small BAM slice this debug mode is much faster or if you can
share such an error-producing BAM slice I am also happy to debug it myself.

-Tobias

**Comment by pliang64** [comment]
Hi Tobias:  Thanks for getting back to me.  I would be happy to share with one of the problematic files. It's  a ~80GB BAM file. Do you have a ftp site for me to deposit the file?  I'll also try to make smaller sets of the BAM file and run the debug version as you suggested. Perhaps it's better to wait for the smaller file(s).  Thanks again. Ping

**Comment by tobiasrausch** [comment]
There is an open issue in htslib (https://github.com/samtools/htslib/issues/400) that could be the cause of your segmentation fault. I just switched to compiler optimization level O2 in the latest Delly code to prevent this error for the time being.

**Comment by drvenki** [comment]
Hi Tobias, 
I may be flogging a dead horse here but I happened to run into this problem today. 
Command:
`delly call -t INV -x hg19.excl -o //nfs/svdata/delly/XX02/XX002_INV.bcf -g /reference/human_g1k_v37_decoy.fasta /tumor/XX002-CFDNAnodups.bam /normal/XX002-Nnodups.bam`

Here's the error 
`Failed to open file /nfs/svdata/delly/XX02/XX002_INV.bcf
Segmentation fault`

Paired-end clustering, Split read alignment, junction read annotation, Breakpoint spanning coverage annotation, read depth annotation -- All these steps complete 100%.

I am using the latest version of delly. Any remedy or solution that I may not be aware of?

TIA,
Venki

**Comment by tobiasrausch** [comment]
The latest delly v0.7.8 has no -t option.  To get the version:

delly -v

**Comment by drvenki** [comment]
Good shout! I am running 0.7.7 && shall upgrade. 
Thanks. :)

**Comment by drvenki** [comment]
It worked. Thanks.
