### ISSUE TITLE
Segmentation fault error running 

### ISSUE THREAD

**Issue by Martaprf** [dellytools/delly#200]
Hello everyone,

I am trying delly with a WGS sample with a bam with 3 different lanes and I got a segmentation fault error, someone can help me understand what is the meaning of this error, 

I use this command line
delly call -o DG1295N_A46598_bwa_picardwithoutkduplicates_delly.bcf -g /home/mferreira/annotations/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa DG1295N_A46598_new_alignment_merged_3lanes_sorted_withoutduplicats.bam

Thank you!

**Comment by tobiasrausch** [comment]
Sorry for my late reply. Can you reproduce the error on a smaller BAM slice that can be shared? Alternatively, you can also try running it through [Alfred](https://github.com/tobiasrausch/alfred) because this tool usually picks up all kinds of problems with BAM files.

**Comment by tobiasrausch** [comment]
I think I need further data to reproduce this bug. Please open a new issue if that's still a problem.

**Comment by tobiasrausch** [comment]
I am not sure I fully understand the issue. Are you saying that
`delly call sample1.bam`
`delly call sample2.bam`

works but 

`delly call sample1.bam sample2.bam`

fails?
