### ISSUE TITLE
wes data to call cnv by split-read 

### ISSUE THREAD

**Issue by QuanLG** [dellytools/delly#201]
Hello
I have a germline wes data and want to call cnv by split-read,but I'm not sure DELLY can use the wes data.
so anyone had to try it and how about the result?

**Comment by tobiasrausch** [comment]
Delly is not ideally suited for WES data. It's able to detect split-reads and call SVs but usually the sensitivity is low because the capturing of these libraries selects against SVs.

**Comment by QuanLG** [comment]
Thanks for explaining it to me
