### ISSUE TITLE
Error while using human.hg19.excl.tsv - Differing number of BED fields encountered at line: 145.  Exiting...

### ISSUE THREAD

**Issue by bioinfo89** [dellytools/delly#203]
Hi,

I am using the hg19 exclusion .tsv file while running the sv calling script and I get the following error:

Differing number of BED fields encountered at line: 145.  Exiting...

Any help will be grateful. Thanks!

**Comment by tobiasrausch** [comment]
This is not a delly error message. Are you trying to use bedtools with the exclusion file? Delly's exclusion files are simple tab-delimited files but for entire chromosomes you do not need to specify start and end and thus, these files are no BED files.

**Comment by bioinfo89** [comment]
No, I am using the exclusion file with bedtools. But it makes sense now why I am getting the error! Thanks!
