### ISSUE TITLE
FILTER=LowQual?

### ISSUE THREAD

**Issue by tyyiyi** [dellytools/delly#205]
hi,please see the following record:
chr17   7675403 BND00001795     T       T[CHR12:104205657[      .       LowQual PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr12;END=104205657;PE=0;MAPQ=0;CT=3to5;CIPOS=-5,5;CIEND=-5,5;SRMAPQ=60;INSLEN=0;HOMLEN=8;SR=4;SRQ=1;CONSENSUS=GTAAGCACCTCCTGCAACCCACTAGCGAGCTAGAGAGAGTTGGCGTCTACACCTCAGGAGCTTTTCTTTTTTTTTTTTTTAGAGGCAGGGTCTGGCTCTGTCATGCAGGCTGGAGTACA;CE=1.98438;RDRATIO=0.850736;SOMATIC  GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-17.0817,0,-42.8809:10000:PASS:2371:2795:0:2:0:0:13:6       0/0:0,-4.51448,-58.099:45:PASS:4364:6047:0:3:0:0:15:0

  problem:
1. How is FILTER=LowQual judged? Why FT=PASS?
2. How does RDRATIO get it?
3. Is this mutation a credible record?

Thank you!
Tang

**Comment by tobiasrausch** [comment]
For BND, delly requires 5 SR for PASS. This one is SR=4. RD doesn't matter for inter-chromosomal translocations. SV looks good to me, except that there is no paired-end support. Is this single-end data?

**Comment by tyyiyi** [comment]
No,it is a pair_end data.
What do you think of the following record？
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  754T_S10_L002   256N_S7_L002
chr3    41224202        DEL00003749     T       <DEL>   .       PASS    IMPRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr3;END=41224930;PE=556;MAPQ=60;CT=3to5;CIPOS=-50,50;CIEND=-50,50;RDRATIO=0.457184;SOMATIC GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-1000,0,-1000:10000:PASS:1203:5089:5573:2:2063:2262:0:0     0/0:0,-1000,-1000:10000:PASS:975:8856:4416:3:3966:0:0:0

**Comment by tyyiyi** [comment]
My data is targeted sequencing data (partial genes). Do you think my parameter -x should use the provided exclude.GRCh38.bed, or should I construct an exclude file based on my own targeted sequencing bed file? If I use the provided exclude.GRCh38.bed, will it affect my results?

I have a record:
chrX 101538445 INV00007787 G <INV> .PASS PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chrX;END=119533041;PE=0;MAPQ=0;CT=3to3;CIPOS=-8,8; CIEND=-8,8;SRMAPQ=60;INSLEN=0;HOMLEN=7;SR=3;SRQ=1;CONSENSUS=TGCACCCAATCAATATCCTCATCATCATCATTAACAAGCTCTTTTTTCACAACTTTCATTGCATAAATACGATCTGTTTTTTCTATTTTTTGTAGAAAGAAATTCCTCCTTTCC;CE=1.81RC:RDQRATIO:GTOMATIC:GTCCTCCTTTCC;CE=1.81. RC:RCR:CN:DR:DV:RR:RV 0/1:-0.274712,0,-85.4733:5:LowQual:16126:7525:31609:0:0:0:24:2 0/0:0, -40.9261,-510.286:10000:PASS:57231:10671:103039:0:0:0:136:0

However, the part of my bed file (after sorting) is:
chrX 101390576 101390696
chrX 101390696 101390816
chrX 102154239 102154359
chrX 123860109 123860229
 Therefore, is this record credible?

**Comment by tobiasrausch** [comment]
Targeted data is rather poorly suited for SV calling. Paired-end mapping doesn't work and the split-read search is quite error-prone. The above is most likely a false positive and hence, the GT is LowQual. You can apply an exclude file, that's fine.

**Comment by dcf774967** [comment]
> For BND, delly requires 5 SR for PASS. This one is SR=4. RD doesn't matter for inter-chromosomal translocations. SV looks good to me, except that there is no paired-end support. Is this single-end data?

Hi! tobiasrausch! I have the same problem.
chr1A_part1	783880	DEL00000083	A	<DEL>	135	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.3;END=783962;PE=0;MAPQ=0;CT=3to5;CIPOS=-3,3;CIEND=-3,3;SRMAPQ=60;INSLEN=0;HOMLEN=2;SR=3;SRQ=1;CONSENSUS=GAAAATTTGGGATGTTACAAAGCGCGAACTTATATTGTCATCGTCCTTTTGGGGGGGGGGAGGGGGTGGGTGG;CE=1.85765	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-11.5854,-1.18954,0:12:LowQual:220:5:123:0:0:0:0:4

Why  the FILTER is PASS but the FT is LowQual? How to understand it? 
Could i filter it?

**Comment by tobiasrausch** [comment]
The FILTER field just assesses the support for a given SV. The genotype call also assesses how well het. and hom. ALT can be differentiated. That's why you can have situations of FILTER==PASS and FT==LowQual.
