### ISSUE TITLE
Some parameter issues

### ISSUE THREAD

**Issue by tyyiyi** [dellytools/delly#206]
In the result file of delly, there are such parameters:
INFO=<ID=PE,Number=1,Type=Integer,Description="Paired-end support of the structural variant">
INFO=<ID=SR,Number=1,Type=Integer,Description="Split-read support">
FORMAT=<ID=RC,Number=1,Type=Integer,Description="Raw high-quality read counts for the SV">
FORMAT=<ID=RCL,Number=1,Type=Integer,Description="Raw high-quality read counts for the left control region">
FORMAT=<ID=RCR,Number=1,Type=Integer,Description="Raw high-quality read counts for the right control region">
FORMAT=<ID=DR,Number=1,Type=Integer,Description="# high-quality reference pairs">
FORMAT=<ID=DV,Number=1,Type=Integer,Description="# high-quality variant pairs">
FORMAT=<ID=RR,Number=1,Type=Integer,Description="# high-quality reference junction reads">
FORMAT=<ID=RV,Number=1,Type=Integer,Description="# high-quality variant junction reads">

a record:
chr20 41135691 DUP00002441 G <DUP> .PASS PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr20;END=41203881;PE=81;MAPQ=60;CT=5to3;CIPOS=-6,6; CIEND = -6,6; SRMAPQ = 60; INSLEN = 0; HOMLEN = 5; SR = 20; SRQ = 1; CONSENSUS = CAATCTCCTCAGGGGACCAGCTGATCCCCTGCTTCAGCCTTTGGGCTGTGAACCAGATCTTGAGCTGTTCGGGCTTCTCACCTCTGAAATGCAGTAAGTTGTCCTGCTGTGCCTGGCAGCCGACCCACTGCCTGGCTCAACATGTCAGACAGGCTCCACCGCGACCGTGGGTGTCCTCAATTTTGGC; CE = 1.96637; RDRATIO = 1.4808; SOMATIC GT: GL: GQ: FT: RCL: RC:RCR:CN:DR:DV:RR:RV 0/1:-200.435,0,-717.319:10000:PASS:1333:13110:2001:8:273:82:206:73 0/0:0, -66.5015,-850.674:10000:PASS:1358:9241:2122:5:305:0:221:0

Shouldn't PE and DV, SR and RV be equal? Is DR+DV+RR+RV depth? Is it related to RC? If I want to require Variant Allele Frequency (VAF)>0.1, Split Reads>3, Depth>50, then how should I set the conditions?

**Comment by tobiasrausch** [comment]
The discovery phase (INFO fields) is not exhaustive to save compute time. For imprecise variants, depth is DR+DV; for precise variants RR + RV.

**Comment by tobiasrausch** [comment]
By the way, there is a [delly-user](https://groups.google.com/forum/#!forum/delly-users) group for these kind of questions.
