### ISSUE TITLE
WES 

### ISSUE THREAD

**Issue by tyyiyi** [dellytools/delly#207]
Hello, I am currently performing structural variation detection with respect to the whole exome data of lung cancer tissues. Do you think my -x parameter should use the bed file of the non-exon region when calling SV?

**Comment by tobiasrausch** [comment]
You could or you intersect the SV results with coding regions.

**Comment by tyyiyi** [comment]
Does it mean that the two breakpoints of structural variation are within the exon region? Or is there only one breakpoint in it?

**Comment by tobiasrausch** [comment]
Ideally both breakpoints are within the targeted regions (usually a bit larger than the coding regions)

**Comment by tyyiyi** [comment]
What if there is only one breakpoint in the area? Is it not credible? I have requested SR support. a bit larger than the coding regions? 500bp?

**Comment by tobiasrausch** [comment]
I don't think there is a general answer to that, depends on the target enrichment if regions outside the targets are covered or not.

**Comment by tyyiyi** [comment]
Please take a look at the following record:

chr1 182727451 DEL00000173 T <DEL>. PASS PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr1;END=182884459;PE=6;MAPQ=60;CT=3to5;CIPOS=-1,1; CIEND = -1,1; SRMAPQ = 60; INSLEN = 0; HOMLEN = 0; SR = 11; SRQ = 1; CONSENSUS = TCATAATAAGTATAATTTAAGTATTGGCTAATAATATGTCTGGAATGAAGACAATTTATGATGAATTTTGTTTTTTATGATTTGGAGTTTTTTAAGTTTGGGGCCATTATAAGTAGTTTTTTTTTTTAATATTAATGCTTAAGAAGTTAAATTTATTCTATAATGTGCCATGTGTGAAGTTGAGAGATAATGGTCTTTTT; CE = 1.71992; RDRATIO = 0.972111; SOMATIC GT: GL: GQ: FT: RCL: RC:RCR:CN:DR:DV:RR:RV 0/1:-39.5566,0,-103.455:10000:PASS:1611:11468:5515:3:33:6:31:14 0/0:0, -14.7425,-188.092:147:PASS:2099:15353:7175:3:54:0:49:0

The SV area here is **chr1:182727451-182884459**
And my target area is:
**chr1 182672761 182672881
chr1 182794345 182794465**
chr1 182803674 182803794
chr1 182806098 182806218
chr1 182806218 182806338
chr1 182806338 182806458
...
chr1 182881583 182881703
chr1 182883133 182883253
chr1 182883253 182883373
**chr1 182883517 182883637
chr1 182884592 182884712**
chr1 182884712 182884832
So it seems that these two breakpoints are not in my target area. Is this mutation credible? why?

**Comment by tobiasrausch** [comment]
As stated multiple times, delly has only limited applicability to WES or targeted data. It has been designed for WGS data.
