### ISSUE TITLE
Parameter -e deprecated?

### ISSUE THREAD

**Issue by stephanflemming** [dellytools/delly#208]
One entry in the FAQ is mentioning a parameter `-e`

```
Is Delly read-group aware?
Yes. If you want to estimate separate insert size distributions for every read-group then use the -e option.
```

Is there a reason why this is not mentioned in the --help? And should this option be integrated in a galaxy wrapper? (PR https://github.com/galaxyproject/tools-iuc/pull/3139)

Thank you,
Stephan

**Comment by tobiasrausch** [comment]
Thanks for pointing out the outdated delly FAQ. The -e option is deprecated for performance reasons, there is no need to include it in the wrapper. Thanks!
