### ISSUE TITLE
Delly 0.8.3 is time consuming

### ISSUE THREAD

**Issue by huangl-CAU** [dellytools/delly#210]
Hi ,I found Delly 0.8.3 is much time consuming than 0.8.2. The latter takes about 20min  performing the "Split-read assembly" , while 0.8.3 takes more than one day  on the same machine and for the same sample.

**Comment by tobiasrausch** [comment]
Have you tried with the latest version v0.8.5? I think I addressed this in v0.8.5 but please let me know if it is still slow.

**Comment by huangl-CAU** [comment]
Dear author ,I have tried the version 0.8.5 ,Although this job is not finished,but it may still suffer by this issue. 
![delly](https://user-images.githubusercontent.com/58922355/96583717-bcecba00-130f-11eb-8565-9a48400e4f5f.jpg)

**Comment by huangl-CAU** [comment]
In addition, I would like to ask for a professional advice . How about using 0.8.2 to perform SV calling instead of the version 0.8.3(+)

**Comment by tobiasrausch** [comment]
Sorry, this issue got lost in my work pile. I guess to pinpoint the source of the problem it would be helpful to run delly separately for each SV type. Sometimes NGS libraries have weird artefacts that only show up as inversion-type paired-ends or the insert size is heavily skewed which would cause DELs to take excessive amounts of time.
