### ISSUE TITLE
Delly Multiple GermlineSv calling mechanism

### ISSUE THREAD

**Issue by nitha26** [dellytools/delly#212]
Hi Tobias,

I'm not clear about the mechanism of how the multiple samples callset are merged into one single VCF file in Delly. I understand that bcftool merge is used to merge all the sample genotypes to a single file. How the duplication record is taken care of in delly. And how delly works splitting the jobs in different compute node  

Could you please explain in simple terms for bellow example   

For example, I have 5 samples and allocating to 5 nodes which have 72 cores (32x2)  

1. How the delly split the samples in different nodes and in one node how a single sample works in multiple cores? whether it junk into small sizes of a chromosome? if so, what is the minimum size of junking?  
2. After multiple sample genotype calling, how the callset of samples are merged into a single final VCF with all sample genotype call? (for example in the small variant calling (SNPs, small indels) the joint genotyping is based on chromosome wise in SV calling how the concept of sample final GermlineSV genotype merging in Delly is performed?

it will be very help full if you explain in simple.

Thank you for your help.

**Comment by tobiasrausch** [comment]
Merging imprecise SVs is often an issue and as far as I know this cannot be readily done with bcftools. Once a unified SV site list exists that has been genotyped in many samples then bcftools merge can be used to basically combine the sample genotypes.
