### ISSUE TITLE
-m min. reference separation -n max. read separation

### ISSUE THREAD

**Issue by viljabio** [dellytools/delly#214]
Hi!

I am posting a question for the first time on github, so I am sorry if I post this to wrong place or something like that.
Delly is running forever for some of my samples and I have been trying to speed it up by changing some options such as -q and -s options. It has helped a little bit. I don't understand what these two options are? Could you explain their purpose?

  -m [ --minrefsep ] arg (=25)      min. reference separation
  -n [ --maxreadsep ] arg (=40)     max. read separation

The problem with my samples might be that the data is not very good quality (FFPE samples). I made Alfred quality check as I read from another conversation that insert size distribution should be close to normal distribution. Here are alfred plots for two samples, one running on Delly forever and another running in about 3 days. I have also difficulties in interpreting these plots. I guess that F stands for forward and R for reverse, am I right? But what are these + and - with them? How should these plots look like with a good quality data? What does that R+ pairs span >= 65535 bp mean?

I am sorry that I am so lost with these tools, I am new with using them. Could you please help me? Thank you in advance!

![runningtimeok](https://user-images.githubusercontent.com/75069459/100335241-6ee96700-2fdd-11eb-9f8b-1037e5ddca27.PNG)
![runningforever](https://user-images.githubusercontent.com/75069459/100335244-6f81fd80-2fdd-11eb-9c18-ab1be1824abf.PNG)

**Comment by tobiasrausch** [comment]
You have rather short fragments, which is common for degraded FFPE samples. Besides `-q` and `-s` you can use `-z` to speed-up delly. For high-coverage data you can use `-z 5`.

**Comment by viljabio** [comment]
Thank you Tobias!
I will try that too. Also, I tried even higher values for -q and -s and it actually helped quite a lot too!
