### ISSUE TITLE
what filter is the "delly -merge" step applying?

### ISSUE THREAD

**Issue by YiBenqiu** [dellytools/delly#215]
Hi, I'm using Delly now, which is awesome software!
When I used the "merge" step, I do not understand what filtering criteria it applies. I was searching for an answer in the "delly-user" forum. Now I know "the default parameters merge all SVs that have a reciprocal overlap >80% and the absolute basepair difference in the SV breakpoints is <1000bp". but when I compare the output from step one (Germline SV calling workflow) with the merged file, I noticed some SVs were filtered. 

I used three samples for the test, my command followed:
- Step one:` parallel -j 3 -a $sample_id "delly call -g $reference -o origin_bcf/{}.bcf --exclude $exclude_region ${realign}/realign_file/{}.realign.bam"`
- Step two:`delly merge --pass -o sites.bcf s1.bcf s2.bcf s3.bcf`

and  Here are examples of SV in s1.bcf s2.bcf s3.bcf:
s1.bcf:`1	456034	DEL00000003	G	<DEL>	180	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.5;END=456108;PE=0;MAPQ=0;CT=3to5;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=1;SR=3;SRQ=0.959596;CONSENSUS=GAGCTGCTTCCGGGGCCTCAGTGAGCAGGGACATTGGAGAGCGGGAGTCTTCGGTCCGTGGTGAGCGTATGTGTGCGGGGGACACCAGCTGTCCCCGAG;CE=1.89185	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	1/1:-25.1992,-2.10643,0:21:PASS:309:133:76:1:0:0:0:7`

s2.bcf:`1	456034	DEL00000005	G	<DEL>	180	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.5;END=456108;PE=0;MAPQ=0;CT=3to5;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=1;SR=3;SRQ=0.957895;CONSENSUS=GGACATTGGAGAGCGGGAGTCTTCGGTCCGTGGTGAGCGTATGTGTGCGGGGGACACCAGCTGTCCCCGAGGACCAGAGGCCCTGTGGTTGGGAG;CE=1.87975	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	1/1:-27.5986,-2.40682,0:24:PASS:145:0:347:0:0:0:0:8`

s3.bcf:`1	456034	DEL00000004	G	<DEL>	300	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.5;END=456108;PE=0;MAPQ=0;CT=3to5;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=1;SR=5;SRQ=0.96;CONSENSUS=TTCCGGGGCCTCAGTGAGCAGGGACATTGGAGAGCGGGAGTCTTCGGTCCGTGGTGAGCGTATGTGTGCGGGGGACACCAGCTGTCCCCGAGGACCAGAG;CE=1.90141	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	1/1:-27.9988,-2.40709,0:24:PASS:231:74:281:0:0:0:0:8`

I noticed that this CNV did not exist in merged.vcf, which means it was filtered out.
It confused me. So, l really needs your help.

**Comment by tobiasrausch** [comment]
Hi,

There should be a deletion in the `sites.bcf` file that overlaps this deletion within the parameters `-b` and `-r` you specified using `delly merge`.

Best, Tobias
