### ISSUE TITLE
can delly2 run on multi-threading

### ISSUE THREAD

**Issue by masen0407** [dellytools/delly#216]
it really slow to run delly on NGS or longreads
delly call only take one thread to run and it take too long.
can Delly2 be like manta run on multi-threading? like add -P int to take   multi-threading.
Hope you consider this problem and it really important to take multi-threading (on one sample ,not a population combine analysis),time is really important.
Thanks

**Comment by tobiasrausch** [comment]
Sure, this is a good suggestion. We currently focus on extending delly for long reads, somatic and germline copy-number calling and SV/CNV annotation but afterwards that's a useful enhancement.

**Comment by masen0407** [comment]
Hello @tobiasrausch 
I highly recommend this.Because now graph base genotyping is really important ,and if delly take so much time to call SV,it can't use in the graph build.
Thanks
