### ISSUE TITLE
Alignment file is missing

### ISSUE THREAD

**Issue by AJ211** [dellytools/delly#218]
Hi,
 I faced a strange problem when I am using DELLY. I install it through singularity, and the version I'm using is the latest v0.8.7.
 I can obtain the correct help information when I run delly call --help. But it shows me **alignment file is missing** when I prepare for germline SV calling. I showed the command line below. Could you please let me know what's going on and how to fix it? Thanks.

Command line for your reference
**singularity exec delly_latest.sif delly call -o SV.bcf -g ${ref} input.bam**

I have tried to change different bam files, and I also change the v0.8.7 to the older one v0.8.6, but the error message is the same. 

Jiao

**Comment by tobiasrausch** [comment]
The singularity image is a container. Singularity usually binds your current working directory in the container. That is, the delly sif file, your BAM file and the reference should be all in the current working directory. More details are in the [singularity documentation](https://singularity.lbl.gov/image-environment).

**Comment by AJ211** [comment]
> The singularity image is a container. Singularity usually binds your current working directory in the container. That is, the delly sif file, your BAM file and the reference should be all in the current working directory. More details are in the [singularity documentation](https://singularity.lbl.gov/image-environment).

**Comment by AJ211** [comment]
Thanks for your quick reply. I am sure all files are in the same directory, but I get the same error message. I guess there are some other reasons as it only shows the bam file is missing, not the reference or others. So any other things maybe I have ignored? Thanks for your patience.
