### ISSUE TITLE
some question about Delly filter

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [dellytools/delly#219]
Hi,
    I'm using Delly now. I have a small problem about Delly filter. After I merge all genotyped bcf, I only used "Delly filter -f germline -o germline.bcf merged.bcf". But there were some sites filtered I think is a useful site for analysis . For example,
`" Chr14 1980174 DEL00025813     T       DEL   240     PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.3;END=1980229;PE=0;MAPQ=0;CT=3to5;CIPOS=-29,29;CIEND=-29,29;SRMAPQ=60;INSLEN=0;HOMLEN=29;SR=4;SRQ=0.98;CONSENSUS=GGGCACGTATGGCTTTGACATTGATCAAATGTGTTTATTTGTCTTGTAGATACAAATTCATCCTGACTGAAGATGATAGATTATGCTACCACAAGATT;CE=1.93209 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   1/1:-22.9996,-1.80577,0:18:PASS:333:173:156:1:0:0:0:6   1/1:-67.8981,-5.41668,0:54:PASS:454:317:662:1:0:0:0:18       1/1:-76.2986,-6.01916,0:60:PASS:394:385:519:1:0:0:0:20  1/1:-96.1984,-7.52413,0:75:PASS:423:335:487:1:0:0:0:25       1/1:-78.698,-6.31964,0:63:PASS:377:205:508:0:0:0:0:21   1/1:-110.399,-8.42742,0:84:PASS:634:515:637:1:0:0:0:28  0/1:-44.7779,0,-28.478:10000:PASS:806:1058:812:1:0:0:9:13    1/1:-51.298,-4.21241,0:42:PASS:392:284:302:1:0:0:0:14   0/1:-37.48,0,-24.0807:10000:PASS:507:445:636:1:0:0:8:12 1/1:-90.298,-7.22273,0:72:PASS:493:235:564:0:0:0:0:24        1/1:-79.9984,-6.32002,0:63:PASS:330:319:555:1:0:0:0:21  1/1:-116.396,-9.62917,0:96:PASS:1009:631:637:1:0:0:0:32      1/1:-55.6984,-4.51387,0:45:PASS:243:114:397:0:0:0:0:15  1/1:-72.9988,-5.71833,0:57:PASS:381:317:461:1:0:0:0:19  1/1:-25.5992,-2.1064,0:21:PASS:283:66:315:0:0:0:0:7  1/1:-36.1986,-3.00891,0:30:PASS:310:205:180:1:0:0:0:10  1/1:-54.7992,-4.21364,0:42:PASS:532:330:398:1:0:0:0:14       0/1:-16.5899,0,-16.89:10000:PASS:445:681:383:2:0:0:5:5  1/1:-71.7984,-5.71797,0:57:PASS:387:230:506:1:0:0:0:19  1/1:-71.9985,-5.71811,0:57:PASS:603:394:488:1:0:0:0:19       0/1:-26.9849,0,-23.385:10000:PASS:618:1121:555:2:0:0:7:8        0/1:-20.8834,0,-32.5832:10000:PASS:425:775:493:2:0:0:10:7    1/1:-29.7991,-2.4073,0:24:PASS:300:186:231:1:0:0:0:8    1/1:-98.1987,-7.52441,0:75:PASS:594:584:442:1:0:0:0:25  1/1:-71.7984,-5.71797,0:57:PASS:387:230:506:1:0:0:0:19       1/1:-69.1976,-5.7172,0:57:PASS:427:272:364:1:0:0:0:19"` 
`"Chr14   1980186 DEL00025814     T       DEL   610     PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.3;END=1980240;PE=0;MAPQ=0;CT=3to5;CIPOS=-15,15;CIEND=-15,15;SRMAPQ=60;INSLEN=0;HOMLEN=25;SR=10;SRQ=0.987421;CONSENSUS=TTATTGGCCATACCCTCCTCCCTCACCTCGTGGGCACGTATGGCTTTGACATTGATCAAATGTGTTTATTTGTCTTGTTGATACAAATTCATCCTGACTGAAGATGATAGATTATGCTACCACAAGATTGATGGATTTTGCTACCACAACATGCATAT;CE=1.9585 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   1/1:-30.5994,-2.40768,0:24:PASS:250:148:175:1:0:0:0:8        1/1:-71.9982,-5.71781,0:57:PASS:386:403:775:1:0:0:0:19  1/1:-72.9987,-5.71829,0:57:PASS:378:412:584:1:0:0:0:19       1/1:-92.0984,-7.22307,0:72:PASS:376:340:557:1:0:0:0:24  1/1:-82.8981,-6.62073,0:66:PASS:298:288:603:1:0:0:0:22  1/1:-110.299,-8.42741,0:84:PASS:574:521:698:1:0:0:0:28       0/1:-51.3759,0,-27.6762:10000:PASS:700:1127:820:1:0:0:9:15      1/1:-55.598,-4.51347,0:45:PASS:346:264:320:1:0:0:0:15        0/1:-40.5782,0,-26.4788:10000:PASS:317:631:676:1:0:0:9:13       1/1:-104.698,-8.42638,0:84:PASS:352:339:614:1:0:0:0:28  1/1:-75.4983,-6.01891,0:60:PASS:322:384:632:1:0:0:0:20       1/1:-136.695,-11.4339,0:114:PASS:835:572:680:1:0:0:0:38 1/1:-63.4983,-5.11582,0:51:PASS:192:214:405:1:0:0:0:17       1/1:-65.2989,-5.11639,0:51:PASS:344:334:573:1:0:0:0:17  1/1:-36.0987,-3.009,0:30:PASS:167:153:372:1:0:0:0:10    1/1:-36.1986,-3.00891,0:30:PASS:249:165:217:1:0:0:0:10       1/1:-46.8993,-3.61168,0:36:PASS:443:300:487:1:0:0:0:12  0/1:-16.59,0,-16.49:10000:PASS:402:671:387:2:0:0:5:51/1:-75.0981,-6.01873,0:60:PASS:291:316:606:1:0:0:0:20   1/1:-72.2986,-5.71817,0:57:PASS:514:377:539:1:0:0:0:19  0/1:-23.0857,0,-25.9849:10000:PASS:675:1038:523:2:0:0:8:7    0/1:-21.2834,0,-32.5831:10000:PASS:427:767:511:2:0:0:10:7       1/1:-33.499,-2.70825,0:27:PASS:258:181:256:1:0:0:0:9    1/1:-89.9987,-6.92241,0:69:PASS:594:484:482:1:0:0:0:23       1/1:-75.0981,-6.01873,0:60:PASS:291:316:606:1:0:0:0:20  
1/1:-61.4977,-5.11526,0:51:PASS:379:256:434:1:0:0:0:17"`
      Could you please give me some advice? 
      Thanks in advance.
Best wishes.

**Comment by tobiasrausch** [comment]
Hi,

that's a good point, I should have documented this somewhere. The delly germline filter primarily looks for a difference between SV carriers (het. or hom. ALT) and non-carriers (hom. REF). For SV sites where none of the samples supports the reference this fails (as in your example). What you can do is plot for each site FORMAT:GT (genotype) against FORMAT:CN (copy-number) if that shows the expected distribution the site is probably true.

Best, Tobias

**Comment by ggoodstudydaydayup** [comment]
I really appreciate it.
Liu
