### ISSUE TITLE
where to obtiain The Mappability Maps

### ISSUE THREAD

**Issue by ritianjiang** [dellytools/delly#221]
Hi,

i wanna perform the cnv calling, while i didnt see the mappability maps in the page(https://gear.embl.de/data/delly/).

where i can get the  mappability map or how to generate.

Thank you for your time

**Comment by tobiasrausch** [comment]
Hi,

Maybe the link was temporarily not working? I can see the maps for GRCh37 and GRCh38 here:

[https://gear.embl.de/data/delly/](https://gear.embl.de/data/delly/)

Best, Tobias

**Comment by ritianjiang** [comment]
Really appreciate the answer.
I thought the map file should be end with .map  -.-||

**Comment by tobiasrausch** [comment]
No, these are the correct files and you need all (including the index files).

**Comment by madzayasodara** [comment]
I have a related question. how to generate these maps for non-model organisms? I work with zebra finches (Taeniopygia guttata bTaeGut2.pat.W.v2). Thank you -mdz

**Comment by tobiasrausch** [comment]
Yes, that's a good point. At the moment I have these mappability maps only for human because there is a ton of data out there to model mappability properly (i.e., 1000 Genomes). Can you send me a link to the zebra finches reference please? I will think about how to best to this just with the reference sequence. thanks.

**Comment by madzayasodara** [comment]
Hi Tobias, 
thank you for the prompt help! Yes, the assembly I'm using is this one.
at https://www.ncbi.nlm.nih.gov/assembly/GCF_008822105.2
Let me know if you wanna me to send you a sample .bam from my birds. That should be doable too.
Thank you!
-madza

**Comment by tobiasrausch** [comment]
Hi Madza,

Here are the mappability maps for Taeniopygia guttata bTaeGut2.pat.W.v2

[https://gear.embl.de/data/delly/](https://gear.embl.de/data/delly/)

I hope that works.

Best, Tobias

**Comment by madzayasodara** [comment]
Hi Tobias
Thank you!
I noticed none of the files have the format (chr, start, end) as specified by delly. 
Is there an additional step I should be aware of?
-madza

**Comment by tobiasrausch** [comment]
These are the mappability maps for your genome. As a first test I would suggest to run:

`delly cnv -a -g GCF_008822105.2_bTaeGut2.pat.W.v2_genomic.fa -m GCF_008822105.2_bTaeGut2.pat.W.v2_genomic.fa.r101.s501.gz <input.bam>`

**Comment by tobiasrausch** [comment]
I added under FAQ in the [README](https://github.com/dellytools/delly) a short code snippet that shows how to generate these mappability maps.
