### ISSUE TITLE
Define germline CNVs

### ISSUE THREAD

**Issue by stellaoh** [dellytools/delly#222]
Dear @tobiasrausch, 

Hi I'm Oh. 

I have WGS data (aligned bam) of 200 samples derived from blood DNA.

I want to define a germline CNVs that differs between the two groups (group1 vs. group2).

In this case, can you please tell me which of the two methods below is the correct way to run "delly"?

-----------------------------------------------------------------------------------

**<<Method 1>>**

**1. SV calling**
delly cnv -o group1_sample1.bcf -g hg19.fa -m hg19.map group1_sample1.bam
delly cnv -o group1_sample2.bcf -g hg19.fa -m hg19.map group1_sample2.bam
...
delly cnv -o group1_sample100.bcf -g hg19.fa -m hg19.map group1_sample100.bam

delly cnv -o group2_sample1.bcf -g hg19.fa -m hg19.map group2_sample1.bam
delly cnv -o group2_sample2.bcf -g hg19.fa -m hg19.map group2_sample2.bam
...
delly cnv -o group2_sample100.bcf -g hg19.fa -m hg19.map group2_sample100.bam

**2. Merge CNVs into a unified site list**
delly merge -e -p -o sites.bcf -m 1000 -n 100000 group1_sample1.bcf  group1_sample2.bcf ... group2_sample99.bcf  group2_sample100.bcf

**3. Genotype CNVs for each sample**
delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group1_sample1.bcf group1_sample1.bam
delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group1_sample2.bcf group1_sample2.bam
...
delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group1_sample100.bcf group1_sample100.bam

delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group2_sample1.bcf group2_sample1.bam
delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group2_sample2.bcf group2_sample2.bam
...
delly cnv -u -v sites.bcf -g hg19.fa -m hg19.map -o group2_sample100.bcf group2_sample100.bam

**4. Merge genotypes using bcftools**
bcftools merge -m id -O b -o merged.bcf group1_sample1.bcf group1_sample2.bcf ... group2_sample99.bcf group2_sample100.bcf 

**5. Filter for germline CNVs**
delly classify -f germline -o filtered.bcf merged.bcf

**6. Compare two groups**

group1 vs. group2 in "filtered.bcf"

-----------------------------------------------------------------------------------

or **<<Method 2>>**

**1. SV calling (Same with Method1)** 
delly cnv -o group1_sample1.bcf -g hg19.fa -m hg19.map group1_sample1.bam
delly cnv -o group1_sample2.bcf -g hg19.fa -m hg19.map group1_sample2.bam
...
delly cnv -o group1_sample100.bcf -g hg19.fa -m hg19.map group1_sample100.bam

delly cnv -o group2_sample1.bcf -g hg19.fa -m hg19.map group2_sample1.bam
delly cnv -o group2_sample2.bcf -g hg19.fa -m hg19.map group2_sample2.bam
...
delly cnv -o group2_sample100.bcf -g hg19.fa -m hg19.map group2_sample100.bam

**2. Merge CNVs into a unified site list**
**1) For group1** 
delly merge -e -p -o group1_sites.bcf -m 1000 -n 100000 group1_sample1.bcf  ... group1_sample100.bcf

**2) For group2**
delly merge -e -p -o group2_sites.bcf -m 1000 -n 100000 group2_sample1.bcf  ... group2_sample100.bcf

**3. Genotype CNVs for each sample**
**1) For group1** 
delly cnv -u -v group1_sites.bcf -g hg19.fa -m hg19.map -o group1_sample1.bcf group1_sample1.bam
delly cnv -u -v group1_sites.bcf -g hg19.fa -m hg19.map -o group1_sample2.bcf group1_sample2.bam
...
delly cnv -u -v group1_sites.bcf -g hg19.fa -m hg19.map -o group1_sample100.bcf group1_sample100.bam

**2) For group2**
delly cnv -u -v group2_sites.bcf -g hg19.fa -m hg19.map -o group2_sample1.bcf group2_sample1.bam
delly cnv -u -v group2_sites.bcf -g hg19.fa -m hg19.map -o group2_sample2.bcf group2_sample2.bam
...
delly cnv -u -v group2_sites.bcf -g hg19.fa -m hg19.map -o group2_sample100.bcf group2_sample100.bam

**4. Merge genotypes using bcftools**
**1) For group1** 
bcftools merge -m id -O b -o group1_merged.bcf group1_sample1.bcf group1_sample2.bcf ... group1_sample99.bcf group1_sample100.bcf 

**2) For group2**
bcftools merge -m id -O b -o group2_merged.bcf group2_sample1.bcf group2_sample2.bcf ... group2_sample99.bcf group2_sample100.bcf 

**5. Filter for germline CNVs**
delly classify -f germline -o group1_filtered.bcf group1_merged.bcf
delly classify -f germline -o group2_filtered.bcf group2_merged.bcf

**6. Compare two groups**

group1_filtered.bcf vs. group2_filtered.bcf

-----------------------------------------------------------------------------------

**I think <<Method 1>> method might be more appropriate.**

I want to hear your opinion.

Many Thanks. 

Oh.

**Comment by tobiasrausch** [comment]
Hi Oh,

Method 1 looks good to me because you get all SV sites uniformly genotyped across all samples in both groups. You can then split the final filtered.bcf into the two groups and compare allele frequencies, and so on.

Best, Tobias

**Comment by stellaoh** [comment]
Dear @tobiasrausch 

Wow.

Thank you for your help. 

Oh.
