### ISSUE TITLE
Sample has not enough data to estimate library parameters

### ISSUE THREAD

**Issue by vivekruhela** [dellytools/delly#224]
I am trying to get somatic SVs from my WES data but I am getting an error message `Sample has not enough data to estimate library parameters` while giving both tumor and normal samples. I check one of the [previous post](https://github.com/dellytools/delly/issues/198) on the similar issue where you have mentioned that BAM file may have less then 10000 mapped reads but in my case there is  `99.77% ` alignment with `223138757` as total number of mapped reads. Will you please suggest me why delly is throwing an error message of `not enough data`. I am using the following  version:

`Delly version: v0.8.7`

`using Boost: v1.65.1`

`using HTSlib: v1.10.2`

Here is the screenshot for your reference:

![Screenshot from 2021-02-01 16-58-52](https://user-images.githubusercontent.com/13174913/106453107-d07ef380-64ae-11eb-8575-ce1c0a22af59.png)

Kindly suggest. Thannks.

**Comment by tobiasrausch** [comment]
Indeed strange, maybe an insert size problem? Have you checked if maybe all reads are completely overlapping?

`alfred qc -r <ref.fa> -j out.json.gz -o out.tsv.gz <input.bam>`

The JSON file produced by [alfred](https://github.com/tobiasrausch/alfred) you can upload here to visualise the QC parameters and insert size distribution: [https://www.gear-genomics.com/alfred/](https://www.gear-genomics.com/alfred/)

**Comment by tobiasrausch** [comment]
In general, WES data is not ideal for delly. It has really been designed for WGS data.

**Comment by vivekruhela** [comment]
Sorry for the late reply. This might be the system-specific issue because it was working fine when I tried it on a different server (and on the same sample). But you are right here that it works well for WGS data only, not for WES data, because I am not getting all the desired SVs previously reported in multiple myeloma. Thanks.

**Comment by tobiasrausch** [comment]
Thanks for letting me know.
