### ISSUE TITLE
delly filter generates empty file

### ISSUE THREAD

**Issue by madzayasodara** [dellytools/delly#225]
I have successfully followed the steps bellow up to the last step. 
`delly filter -f germline -o germline.bcf merged.bcf`

`delly filter` asks for an index of my merged bcf, which I generated using 
`bcftools index merged.bcf to generate a .csi index`

then when running `delly filter -f germline -o germline.bcf merged.bcf`, I get:

```
Filtering VCF/BCF file
[E::bgzf_close] File write failed
Done.
and an empty output is generated
```
I'm using 
```
Delly version: v0.8.7
 using Boost: v1.57.0
 using HTSlib: v1.10.2
 using gcc/7.2 
```
and 
```
bcftools 1.9
Using htslib 1.9
```

Thank you,
-mdz

Germline SV calling
SV calling is done by sample for high-coverage genomes or in small batches for low-coverage genomes
delly call -g hg19.fa -o s1.bcf -x hg19.excl sample1.bam

Merge SV sites into a unified site list
delly merge -o sites.bcf s1.bcf s2.bcf ... sN.bcf

Genotype this merged SV site list across all samples. This can be run in parallel for each sample.
delly call -g hg19.fa -v sites.bcf -o s1.geno.bcf -x hg19.excl s1.bam

delly call -g hg19.fa -v sites.bcf -o sN.geno.bcf -x hg19.excl sN.bam

Merge all genotyped samples to get a single VCF/BCF using bcftools merge
bcftools merge -m id -O b -o merged.bcf s1.geno.bcf s2.geno.bcf ... sN.geno.bcf

Apply the germline SV filter which requires at least 20 unrelated samples
delly filter -f germline -o germline.bcf merged.bcf

**Comment by tobiasrausch** [comment]
Looks like something went wrong in the SV merge. Can you please count the number of SVs in your site list and in the merged BCF:

`bcftools view merged.bcf | grep -v "^#" | wc -l`

`bcftools view sites.bcf | grep -v "^#" | wc -l`

**Comment by madzayasodara** [comment]
Hi Tobias, 
the outputs of `delly call -g genome.fa -o s1.bcf  sample1.bam`
have various sizes from 20000-30000 lines
the output of `delly merge -o sites.bcf s1.bcf s2.bcf ... sN.bcf`
has 74803 lines
outputs of `delly call -g genome.fa -v sites.bcf -o s1.geno.bcf s1.bam` 
have each the same 74803 lines
and the final `bcftools merge -m id -O b -o merged.bcf s1.geno.bcf s2.geno.bcf ... sN.geno.bcf`
also has 74803 lines

I forgot to include a key info that I'm not working with humans, as in the example. The genome I use is the zebra finch genome bTaeGut2.pat.W.v2  at https://www.ncbi.nlm.nih.gov/assembly/GCF_008822105.2 (so also not using a map file).
Thank you!
-madza

**Comment by tobiasrausch** [comment]
This problem is still not clear to me. Basically `delly filter -f germline -o germline.bcf merged.bcf` fails, right? Can you send me the merged.bcf file ? I don't think I can debug this remotely.

**Comment by madzayasodara** [comment]
Absolutely! Which address should I be sending it to? mine is madzayasodara@ucla.edu, if you wanna shoot me a message there. 
Thank you for the assistance -madza

**Comment by tobiasrausch** [comment]
Thanks for your message. That's resolved now.
