### ISSUE TITLE
 libboost_iostreams.so.1.58.0

### ISSUE THREAD

**Issue by s-zafari** [dellytools/delly#226]
Hi Tobias,
I have just started using Ubuntu 18.04.5 and having trouble building delly although in Ubuntu 16 everything worked fine.
It seems there is a boost version issue. please find below the error that I get:
**./delly: error while loading shared libraries: libboost_iostreams.so.1.58.0: cannot open shared object file: No such file or directory**
unfortunately, I cannot install this package in Ubuntu 18 anymore because the newer version of it exists and it seems delly cannot work with the newer version.
 Would you please help with this error and let me know if there is a solution?

Thanks in advance & best,
Sachli

**Comment by tobiasrausch** [comment]
Just build against the new boost library. In the delly folder:

`make clean && make distclean && make all && make install`

**Comment by s-zafari** [comment]
Thanks Tobias, I did what you said and it works
