### ISSUE TITLE
Delly CNV has ./. (SV files look normal)

### ISSUE THREAD

**Issue by kvn95ss** [dellytools/delly#227]
Hello,

I have ran germline delly SV and CNV for 8 genome samples and have a few queries / issues.

1. The SV step (as illustrated in the readme) ran without any problems. I could filter the variants and I extracted my sample SVs from the germline bcf using GATK SelectVariants. I just wanted to know if using this extraction method was okay, or if there's a better or "correct" way to extract per-sample variants from the merged files.
```
delly call -g grch38.fasta -o s1.bcf -x hg38.excl sample1.bam # all samples, USED IN GERMLINE CNV CALLING
delly call -g grch38.fasta -v sites.bcf -o s1.geno.bcf -x hg19.excl s1.bam # all samples
bcftools merge -m id -O b -o merged.bcf s1.geno.bcf s2.geno.bcf ... sN.geno.bcf
delly filter -f germline -o germline.bcf merged.bcf
gatk SelectVariants -R grch38.fasta -V germline.vcf -O s1.vcf -sn s1 # Extract sample from germline.vcf
```

2. In Germline CNV calling step, it is optional to use SV files for clearer breakpoints. Since I had generated all SV files, I thought I would use them here. However, upon using the files from first step, I got ./. in the final filtered file.

```
delly cnv -o s1.cnv.bcf -g grch38.fasta  -m map/grch38.blacklist.gz -l ../s1.bcf s1.bam #the s1.bcf is generated from first step of SV calling.
delly merge -e -p -o sites.bcf -m 1000 -n 100000 $(ls *bcf)
tabix -p bcf sites.bcf
delly cnv -u -v sites.bcf -g grch38.fasta  -m map/grch38.blacklist.gz -o s1.geno.bcf s1.bam
bcftools merge -m id -O b -o merged.bcf $(ls *geno*bcf)
tabix -p bcf merged.bcf
delly classify -f germline -o filtered.bcf merged.bcf
```
All entries of filtered.bcf are ```./.```

As indicated, I have used the bcf output from first step of SV calling for germline CNV calling. Am I using the correct file? Should I instead be using the extracted, fitlered SV file (indicated in the last line of SV calling step) or use the genotype file generated during the SV step? Any inputs would be helpful. Do let me know if my error was understandable or not.

3. Just a question, after extracting the file (if my method is actually appropriate), what would be the best way to annotate the SV/CNV events?

**Comment by tobiasrausch** [comment]
For copy-number variants delly is currently not using the GT field because that's commonly used for hom. ALT (1/1), het. (0/1) and hom. REF (0/0). For copy-number variants I do not know the allelic distribution. For instance if the total copy-number of a segment is 8 the allelic copy-numbers could be 4 and 4, or 8 and 0, or 1 and 7, ...

Because of that issue delly only outputs the total copy-number in FORMAT:CN and the copy-number likelihoods for each copy-number state (FORMAT:CNL).

**Comment by tobiasrausch** [comment]
Regarding your (3) question: The first thing we usually do after classifying CNVs in the germline mode is to plot the copy-number distribution. For highly polymorphic loci this should look like [this Figure](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4405206/figure/F2/)

The [delly README](https://github.com/dellytools/delly#germline-cnv-calling) shows how to do the plots.

**Comment by kvn95ss** [comment]
Hello, 

Thanks for the reply. So rather than looking at GT field, I should have paid attention to the CN and CNL values, though I don't believe I yet understand the interpretation for CN and CNL entirely at this moment. I thought the plotting would work only for larger samples, hence haven't tried it out. But now that you've mentioned it, I will definitely try it out.

**Comment by tobiasrausch** [comment]
Indeed, 8 samples is not much but at least you can check if they cluster around integer copy-numbers.
