### ISSUE TITLE
what does RR ("# high-quality reference junction reads") mean?

### ISSUE THREAD

**Issue by cxue** [dellytools/delly#228]
Hi, I am confused of this term -- RR ("# high-quality reference junction reads"). It is the total non-split reads# covered on two breaks of SV. Corresponding to RR, RV  ("# high-quality variant junction reads") is the total split read# on two breaks. is this right? thanks in advance.

**Comment by tobiasrausch** [comment]
Hi,

Yes, that's correct. RR is the support for the reference and RV for the variant.

Best, Tobias
