### ISSUE TITLE
Error in boost::math::pdf

### ISSUE THREAD

**Issue by peterfrommolt** [dellytools/delly#230]
Hi Tobias,

we have run into a problem when using DELLY-CNV for tumor/normal analyses using 60x/30x sequencing depth.

This is the command that we are using:
delly classify --pass --filter somatic --samples delly_samples.tsv --outfile delly_cnv-somatic.bcf delly_cnv-merged.bcf

And this is the error message:
terminate called after throwing an instance of 'boost::wrapexcept<std::domain_error>'
  what():  Error in function boost::math::pdf(const normal_distribution<double>&, double): Random variate x is nan, but must be finite!
Aborted (core dumped)

Any idea?

Best,
Peter

**Comment by tobiasrausch** [comment]
Hi Peter,

Thanks, this should be fixed now in the latest code on github.

Best, Tobias
