### ISSUE TITLE
Reference index error

### ISSUE THREAD

**Issue by aditya-sarkar441** [dellytools/delly#233]
I tried running Delly on bam files and got an error which I am not able to debug. Here is the exact error : 

/u/home/m/mdistler/project-jflint/DELLY/delly_v0.7.3_linux_x86_64bit
Wed Mar 24 09:52:58 PDT 2021 --- RUNNING delly
 /u/home/m/mdistler/project-jflint/DELLY/delly_v0.7.3_linux_x86_64bit call -t DEL -g /u/flashscratch/p/pelin/DNASeqTools/indexing_times/genome.fa -o          /u/home/m/mdistler/scratch/aditya-snap/delly_out/dell$
Reference chromosome names disagree with bam header for ERR009308_g_snap.sorted.bam
Wed Mar 24 09:52:58 PDT 2021 --- TOTAL RUNTIME: 0:00:00:0.0000
Wed Mar 24 09:52:58 PDT 2021 --- FINISHED RUNNING delly
DONE

Can you please help me out with this ?

**Comment by tobiasrausch** [comment]
This error is happening if the genome file uses different chromosome notations as the BAM file. For instance, the BAM file may use "chr1" and your genome file ">1" which delly cannot match. Please always use the same genome file for mapping and delly structural variant calling. This should prevent this error.
