### ISSUE TITLE
Calling options

### ISSUE THREAD

**Issue by viljabio** [dellytools/delly#234]
Hi!

Are these options for delly call explained somewhere more detailed? If not, would it be possible to get some kind of explanations for dummies? I think many of these are pretty clear, but many of these are not (i.e. -s, -c, -m, -n), at least for me. 

Generic options:
  -? [ --help ]                      show help message
  -t [ --svtype ] arg (=ALL)         SV type to compute [DEL, INS, DUP, INV,
                                     BND, ALL]
  -g [ --genome ] arg                genome fasta file
  -x [ --exclude ] arg               file with regions to exclude
  -o [ --outfile ] arg (="sv.bcf")   SV BCF output file

Discovery options:
  -q [ --map-qual ] arg (=1)         min. paired-end (PE) mapping quality
  -r [ --qual-tra ] arg (=20)        min. PE quality for translocation
  -s [ --mad-cutoff ] arg (=9)       insert size cutoff, median+s*MAD
                                     (deletions only)
  -c [ --minclip ] arg (=25)         min. clipping length
  -z [ --min-clique-size ] arg (=2)  min. PE/SR clique size
  -m [ --minrefsep ] arg (=25)       min. reference separation
  -n [ --maxreadsep ] arg (=40)      max. read separation

Genotyping options:
  -v [ --vcffile ] arg               input VCF/BCF file for genotyping
  -u [ --geno-qual ] arg (=5)        min. mapping quality for genotyping
  -d [ --dump ] arg                  gzipped output file for SV-reads
                                     (optional)

Thank you in advance, if you have time to give a bit more detailed explanations!

BR Vilja

**Comment by tobiasrausch** [comment]
Hi,

There is a [delly-users](https://groups.google.com/g/delly-users) discussion group which explains some of these options I believe. In short, '-c' is simply the min. clipped length for a soft-clipped read, '-m' is how far these split-reads need to be apart in reference space and '-n' is the opposite for the read space. '-s' only applies for deletions and specifies when an observed paired-end distance is too large to be a normal paired-end.

Best, Tobias
