### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by assane-mbodj** [dellytools/delly#235]
Hi 
Is it possible to apply Delly on rice or Aabidopsis thaliana data.
And I have this error while installing Delly:

In file included from src/delly.cpp:17:
src/delly.h:8:10: fatal error: boost/graph/adjacency_list.hpp: Aucun fichier ou dossier de ce type
    8 | #include <boost/graph/adjacency_list.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:61 : src/delly] Erreur 1

**Comment by tobiasrausch** [comment]
You need to have the boost libraries installed. Alternatively you can use the static binaries, bioconda or docker/singularity versions of delly.

**Comment by assane-mbodj** [comment]
je viens d'installer le binaire statistique mais j'ai eu les même erreur:

assane@gwas:~/delly-0.8.7$ make PARALLEL=1 -B src/delly
if [ -r src/htslib/Makefile ]; then cd src/htslib && autoheader && autoconf && ./configure --disable-s3 --disable-gcs --disable-libcurl --disable-plugins && make && make lib-static && cd ../../ && touch .htslib; fi
g++ -isystem /home/assane/delly-0.8.7/src/htslib/ -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive -fopenmp -DOPENMP -O3 -fno-tree-vectorize -DNDEBUG src/delly.cpp -o src/delly -L/home/assane/delly-0.8.7/src/htslib/ -L/home/assane/delly-0.8.7/src/htslib//lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time  -lhts -lz -llzma -lbz2 -Wl,-rpath,/home/assane/delly-0.8.7/src/htslib/
In file included from src/delly.cpp:17:
src/delly.h:8:10: fatal error: boost/graph/adjacency_list.hpp: Aucun fichier ou dossier de ce type
    8 | #include <boost/graph/adjacency_list.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:61 : src/delly] Erreur 1

**Comment by tobiasrausch** [comment]
According to the other issue this should be solved. Please re-open if that's not the case.
