### ISSUE TITLE
Can Delly detect tandem vs interspersed duplications? (Low-pass genome data)

### ISSUE THREAD

**Issue by kvn95ss** [dellytools/delly#236]
Hello,

I have low pass genome data and have called duplications using the command 

```
delly call -g /mnt/exome/Softwares/GRCh38/REF/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta input_LPGS.bam -t DUP -o Duplication.bcf
```

My region of interest is called as follows - 

```
chr1    155096839       DUP00000169     T       <DUP>   300     PASS    PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.8.7;END=156624688;PE=2;MAPQ=60;CT=5to3;CIPOS=-1,1;CIEND=-1,1;SRMAPQ=60;INSLEN=0;HOMLEN=0;SR=3;SRQ=0.989691;CONSENSUS=CACCGCACGCGCCCCGTGTAGGCATGATGGCGGGTGCCTGTAATCCCAGCTACTCAGGAGGCTGAGACAGGAGAATTGCTTGAACTGGGGAGGGCAG;CE=1.94156      GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-8.49111,0,-20.4893:85:PASS:20312:75017:20155:4:5:2:8:4
```

From the output, I could not discern if the duplication is in tandem or interspersed. Is Delly capable of calling this?

**Comment by tobiasrausch** [comment]
For interspersed duplications one usually observes 2 paired-end clusters. The duplication looks very credible, read-depth support is good (RDCN=4).

**Comment by kvn95ss** [comment]
> For interspersed duplications one usually observes 2 paired-end clusters. 

How would that look like in the delly file?

Since the genotype is 0/1, would it be correct to assume that the duplication is heterozygous? i.e 1 extra copy of the region is present in the sample?

Also, turns out there are 3 duplications called in my region of interest, 1 imprecise and 2 precise calls, but I think the one I mentioned before seems like better call.

```
chr1    790444  224015475       0       0       exonic  1q31.3-q21.1    0.5     125     .       chr1    790444  DUP00000000     A       <DUP>   125     PASS    IMPRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.8.7;END=224015475;PE=4;MAPQ=37;CT=5to3;CIPOS=-50,50;CIEND=-50,50       GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-10.6938,0,-10.3197:102:PASS:4369:4900400:587861:17:2:4:0:0
#mentioned before chr1    155096839       156624688       0       0       exonic  1q23.1-q21.3    0.5     300     .       chr1    155096839       DUP00000169     T       <DUP>   300     PASS    PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.8.7;END=156624688;PE=2;MAPQ=60;CT=5to3;CIPOS=-1,1;CIEND=-1,1;SRMAPQ=60;INSLEN=0;HOMLEN=0;SR=3;SRQ=0.989691;CONSENSUS=CACCGCACGCGCCCCGTGTAGGCATGATGGCGGGTGCCTGTAATCCCAGCTACTCAGGAGGCTGAGACAGGAGAATTGCTTGAACTGGGGAGGGCAG;CE=1.94156  GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-8.49111,0,-20.4893:85:PASS:20312:75017:20155:4:5:2:8:4
chr1    155137566       156623881       0       0       exonic  1q23.1-q22      0.5     300     .       chr1    155137566       DUP00000170     T       <DUP>   300     PASS    PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.8.7;END=156623881;PE=0;MAPQ=0;CT=5to3;CIPOS=-2,2;CIEND=-2,2;SRMAPQ=60;INSLEN=0;HOMLEN=1;SR=5;SRQ=0.986842;CONSENSUS=CCCATCCACGAGGTCATTCACTCTCATCGTGGGGCCACGGCATGATGCTCCTACAGACTGCAACCCTGCTAGGGGTCCTTCTCCTGGGTTATGGCTACTTTTGGCTCCTGGTACCCAACCCTGAGGCCCGGCTTCAGCAGTTGGGCCTCTT;CE=1.94776     GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-13.4886,0,-27.7846:135:PASS:20300:73419:19673:4:0:0:11:6
```

**Comment by tobiasrausch** [comment]
Delly's GT field is based on paired-ends. For large duplications (like the one from your first message) you can rely on the read-depth based copy-number estimate (FORMAT:RDCN) which leverages all mapped reads inside the duplication. As you can see in your example the estimated copy-number is 4 instead of the expected 2. Without phased data it's impossible to tell if it's a homozygous duplication or if one allele carries 3 copies and the other one only 1. 

DUP00000000 looks like a false positive, probably due to mis-mapping in sub-telomeric regions. DUP00000169 and  DUP00000170 could be the same event, duplications are sometimes embedded in repeats and then you get these kind of breakpoint inaccuracies. Something to look at in IGV I suppose.

**Comment by kvn95ss** [comment]
> As you can see in your example the estimated copy-number is 4 instead of the expected 2. Without phased data it's impossible to tell if it's a homozygous duplication or if one allele carries 3 copies and the other one only 1.

Thanks for the explanation! Guess this complicates things for me. I'm still working on figuring out if the duplication was in tandem or interspersed (trying other tools and going through literature). Since the data is Low-Pass Genome I'm not confident if phasing is possible, but will check it out.
