### ISSUE TITLE
SR, RR, RV in delly2 output

### ISSUE THREAD

**Issue by phdstudent-oje** [dellytools/delly#237]
Dear @tobiasrausch,

Hi, I'm delly2 user. 

Thank you very much for making a good program, delly.

I checked the comment that explains how to calculate VAF.

"VAF (variant allele frequency) = DV/(DR+DV) for imprecise variants and
VAF = RV/(RR+RV) for precise variants"

I have questions about above comment.

1. Why not calculate using all the reads supporting the SV (like as DV + RV / DR + DV + RR + RV), 
but divide the paired reads and split reads as in the above case?

2. Also, why do you calculate that difference between Precise and imprecise SV?

3. And the above calculation formula does not add up the read count of the corresponding position in normal tissue, is it correct to calculate only for the sample I want to see (ex. tumor sample)?

3. And is it correct to calculate the above calculations only for the samples I want to know (e.g. tumor samples) without adding the number of reads from normal tissue?

VAF = RV/(RR+RV) for precise variants in only tumor sample? 
or VAF = RV/(RR+RV) for precise variants in tumor sample + normal sample?

Many thanks. 

Oh.

**Comment by tobiasrausch** [comment]
Genotyping works differently for precise and imprecise variants. Usually the split-read genotyping (RR, RV) is more robust but it can only be applied to precise variants. VAF or B-Allele Frequency is only meaningful for one sample.

**Comment by stellaoh** [comment]
Dear @tobiasrausch, 

Thank you for answer.

Have a nice day. :)

Oh.
