### ISSUE TITLE
Multiple sample SV call

### ISSUE THREAD

**Issue by Giuseppe1995** [dellytools/delly#238]
Hi,
do you know how I should call SV on several samples? I mean, have I to give two txt files as input (one with the germline tissue and another with the tumor one for each individual)  or have I to specify it this way:
`delly call -g <REF> -o example.bcf SAMPLE1_T.bam SAMPLE1_N.bam SAMPLE2_T.bam SAMPLE2_N.bam ... SAMPLEn_T.bam 
 SAMPLEn_N.bam`. 
This is something not clear in the tutorial

**Comment by tobiasrausch** [comment]
Calling by donor should be fine.

`delly call -g <REF> -o sample1.bcf SAMPLE1_T.bam SAMPLE1_N.bam`

`delly call -g <REF> -o sample2.bcf SAMPLE2_T.bam SAMPLE2_N.bam`
