### ISSUE TITLE
delly for long reads

### ISSUE THREAD

**Issue by assane-mbodj** [dellytools/delly#239]
Hi 
I use delly on my long read data but I run the command line below. It does not recognize "lr". 

assane@gwas:~/delly$ delly lr -y ont -g /home/assane/hecaton/ref/TAIR10.fa /media/assane/DD-2To/NAS-NANOPORE/l9f6_nanopore.sorted.bam -o /media/assane/DD-2To/NAS-NANOPORE/l9f6_nanopore.bcf
Unrecognized command lr

Thank you for your help

**Comment by tobiasrausch** [comment]
Probably a version issue, just run:

`delly -v`

For the lr mode you need the latest version v0.8.7

**Comment by assane-mbodj** [comment]
Hi
I tried to install version 0.87 but I got this error when compiling the program


assane@gwas:~/delly-0.8.7$ make
if [ -r src/htslib/Makefile ]; then cd src/htslib && autoheader && autoconf && ./configure --disable-s3 --disable-gcs --disable-libcurl --disable-plugins && make && make lib-static && cd ../../ && touch .htslib; fi
g++ -isystem /home/assane/delly-0.8.7/src/htslib/ -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive -DNOPENMP -O3 -fno-tree-vectorize -DNDEBUG src/delly.cpp -o src/delly -L/home/assane/delly-0.8.7/src/htslib/ -L/home/assane/delly-0.8.7/src/htslib//lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time  -lhts -lz -llzma -lbz2 -Wl,-rpath,/home/assane/delly-0.8.7/src/htslib/
In file included from src/delly.cpp:17:
src/delly.h:8:10: fatal error: boost/graph/adjacency_list.hpp: Aucun fichier ou dossier de ce type
    8 | #include <boost/graph/adjacency_list.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:61 : src/delly] Erreur 1

Thanks

**Comment by tobiasrausch** [comment]
Delly is available via [bioconda](https://anaconda.org/bioconda/delly), as a [docker container](https://hub.docker.com/r/dellytools/delly/) or as a [static binary](https://github.com/dellytools/delly/releases). That's usually easier then compiling from source. Have you tried this?

**Comment by assane-mbodj** [comment]
Yes I used conda but it installs me the 0.76 version.
Apparently it's not up to date

**Comment by tobiasrausch** [comment]
The delly package is up-to-date in bioconda. You probably have other tools in your conda environment that require older library dependencies. You can force a specific version with

`conda install delly=0.8.7`

Sometimes channel priorities are also an issue with conda:

`conda install --strict-channel-priority --override-channels -c conda-forge -c bioconda -c defaults delly=0.8.7`

**Comment by assane-mbodj** [comment]
HI @tobiasrausch 
Thank you, I have installed the latest version.
I would like to know if Delly has been tested on plant data and does it perform beter. Also, can Delly take several Illumuna or Nanopore samples and is so, what type of command should be used ?

Thank you in advance.

**Comment by tobiasrausch** [comment]
Calling illumina and Oxford Nanopore data jointly does not work with delly. You have to use delly separately for the short-read data (delly call) and the long read data (delly lr).

Delly has been used in many plant studies. The SV discovery works fine but the genotyping assumes a ploidy of 2.

**Comment by assane-mbodj** [comment]
Hi @tobiasrausch 
Sorry again, I have another question
 I ran delly on my long read data but I have a problem with the mapping starting to work but then stopping. Here is my output.

(base) assane@gwas:~$ delly lr -y ont -g /home/assane/data_rice/IRGSP/ref/IRGSP-1.0_genome.fasta /home/assane/data_rice/data_nanopore/all_guppy_hac_taille_grain_127372_R9_R10.sorted.bam -o /home/assane/data_rice/data_nanopore/all_guppy_hac_taille_grain_127372_R9_R10.bcf
[2021-May-20 09:36:20] delly lr -y ont -g /home/assane/data_rice/IRGSP/ref/IRGSP-1.0_genome.fasta /home/assane/data_rice/data_nanopore/all_guppy_hac_taille_grain_127372_R9_R10.sorted.bam -o /home/assane/data_rice/data_nanopore/all_guppy_hac_taille_grain_127372_R9_R10.bcf 
[2021-May-20 09:36:20] Split-read scanning

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-May-20 09:36:40] Split-read assembly

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
****

Thank you very much for your availability

**Comment by tobiasrausch** [comment]
Did delly crash or is it taking a long time? I don't see an error message.

**Comment by assane-mbodj** [comment]
It keeps crashing on the split read assembly step and it doesn't display an error message. I've been running it for two days but it stops at this stage

Thanks

**Comment by tobiasrausch** [comment]
I have heavily revised the long-read calling in delly v1.0.3. Genome in a Bottle F1 scores are now at 94% for ONT UL and 95% for PacBio CCS. I hope this delly update solves this issue. If not please open a new issue.
