### ISSUE TITLE
No SVs reported by delly

### ISSUE THREAD

**Issue by carolynzy** [dellytools/delly#240]
Hi, 
I have been using delly on my more than 400 samples. For most of them, delly worked well. But for 4 samples delly reported no SVs.  I couldn't find out what is the problem. The bam files seem fine and other methods reported SVs on these 4 samples. I have included a slice of my bam file and the reference file [here](https://1drv.ms/u/s!Ahu3aHGoa85BhA4sgPBmxY-DyT2t?e=hkoGBU). I'm sure there is a one base deletion at position 373283. Would you please look into this issue? Thanks a lot!

**Comment by tobiasrausch** [comment]
Please note that Delly is an SV caller. One-base pair deletions are called by short-variant callers such as GATK, FreeBayes or Strelka.  Delly is used for larger variants and SVs are usually defined as >=50bp.
