### ISSUE TITLE
How to speed up "delly call -g hg19.fa -v sites.bcf -o s1.geno.bcf -x hg19.excl s1.bam" when sites.bcf is big

### ISSUE THREAD

**Issue by yupan-ucla** [dellytools/delly#242]
HI @tobiasrausch,

I'm trying to run "delly call -g hg19.fa -v sites.bcf -o s1.geno.bcf -x hg19.excl s1.bam". 
When the sites.bcf is relatively small, say 7MB, and the size of s1.bam is 90GB, the process takes about 5 hours.
However, when the size of the sites.bcf grows to 48MB (I merged more samples to get sites.bcf), the process takes about 52 hours.
Is there any way to speed up the process? 
https://github.com/dellytools/delly says "Delly primarily parallelizes on the sample level."
So it seems it impossible to do multi-threading against a single sample. Am I right?
Any suggestions would be greatly appreciated! 
Thanks.

**Comment by zhemingfan** [comment]
Hi @tobiasrausch , I have the same question on whether it would be possible to multi-thread on individual samples. For LR ONT, on a similar 90GB bam file - the runtime is 48+ hrs for me.

**Comment by tobiasrausch** [comment]
The long-read calling is indeed not very fast currently and I hope to have some time later this year to optimize this. For the time-being you can of course parallelize by chromosome but you need to split the BAM.

**Comment by tobiasrausch** [comment]
Delly v1.0.3 should be much faster for long-read SV calling. I hope this solves this issue.
