### ISSUE TITLE
Default minimum number of reads that support a SV for LR ONT mode 

### ISSUE THREAD

**Issue by zhemingfan** [dellytools/delly#243]
Hi @tobiasrausch, 

I was wondering what the default minimum number of reads for LR ONT SV discovery mode was, and whether this is configurable (or planned to be configurable in the future).

**Comment by tobiasrausch** [comment]
Hi,

The default is 2 and it is configurable:

`-z [ --min-clique-size ] arg (=2)     min. clique size`

Best, Tobias
