### ISSUE TITLE
Performing delly SV calling in conseqution

### ISSUE THREAD

**Issue by AlesMaver** [dellytools/delly#245]
Dear Tobias!
Firstly, many thanks for the DELLY2, which is awesome. 

I have a question - in our analyses, we are consecutively adding new WGS samples to our study. For example, when a patient has WGS analysis performed, we would like to perform an analysis against a reference of other samples sequenced in the past. We perform a lot of analyses on a compute cluster and as the numbers of WGS in our population grow, submitting 100WGS BAM-s for execution is becoming prohibitive. 

I wanted to ask if it would be possible to perform initial SV calling for, say, a reference set of 100 samples in the following manner:
```
# Perform reference genotyping for 100 reference samples
delly call -g hg19.fa -o s1.bcf -x hg19.excl sample1.bam # Loop through s1-s100
delly merge -o sites.bcf s1.bcf s2.bcf ... s100.bcf
delly call -g hg19.fa -v sites.bcf -o s1.geno.bcf -x hg19.excl s1.bam # Loop through s1-s100
bcftools merge -m id -O b -o reference_genotypes.bcf s1.geno.bcf s2.geno.bcf ... s100.geno.bcf
delly filter -f germline -o reference_genotypes_filtered.bcf reference_genotypes.bcf
```

And then perform re-calling for sample number 101, when the data is available. 
```
# Call the SVs in the sample number 101
delly call -g hg19.fa -o s101.bcf -x hg19.excl s101.bam
# Merge the SVs in the reference population with SVs detected in sample 101
delly merge -o sites.bcf reference_genotypes_filtered.bcf s101.bcf
# Call genotypes for the merged variant set
delly call -g hg19.fa -v sites.bcf -o s101.geno.bcf -x hg19.excl s1.bam
# Merge genotypes of the references set with genotypes in sample 101 
bcftools merge -m id -O b -o genotypes.bcf reference_genotypes_filtered.bcf s101.geno.bcf
# Perform filtration
delly filter -f germline -o genotypes_filtered.bcf genotypes.bcf
```
Do you think this strategy would work in samples that are sequenced consecutively? This would mean that only have to submit the reference_genotypes_filtered.bcf file to enable delly cohort calling on the compute cluster for the new sample. 
 
Thank you very much for any ideas or advice if this strategy would work. 
Many thanks!
Ales

**Comment by tobiasrausch** [comment]
Hi Ales,
I am sorry for my late reply. These n+1 problems are indeed becoming increasingly important in genomics. I don't have a good solution yet. One could indeed first check which SVs are present in the population call set (1-100) and then add the additional SVs of sample 101 but the problem is we don't know the genotypes of these new SVs for sample 1-100.  In practice, we currently indeed incrementally add SVs to a growing site list but every now and then we need to re-genotype this list across the whole cohort.
Best, Tobias

**Comment by AlesMaver** [comment]
Dear Tobias - many thanks for the reply - good to hear that you are using a similar approach! When looking at the rare variants in "individual 101", the genotypes if individuals 1-100 are not mandatory for our analyses, because we only need their genotypes to filter out common variants. 
We are also considering using SURVIVOR to merge genotypes of several individuals. 
Thanks again!
