### ISSUE TITLE
Delly -x with centromeric regions, seems to remove variants outside these regions

### ISSUE THREAD

**Issue by john-alexander** [dellytools/delly#264]
Hiya,

I've run my analysis using both -x and without -x to call somatic SVs. Comparing both VCF files on IGV, seems like some variants get excluded even though they aren't specified in the exclusion bed file.

See example 
[](url)
![Screenshot 2021-10-11 at 10 23 42](https://user-images.githubusercontent.com/33318427/136768822-555f53bb-f70f-4d60-8552-d9fc71664286.png)

#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | Sample_G73_0012 | BTBC183_germline | BTBC456_germline | BTBC517_germline | Sample_G73_0004 | G920009 | Sample_G73_0005
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr10 | 95395030 | INV00000015 | T | <INV> | 180 | PASS | PRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.8.5;END=95413813;PE=0;MAPQ=0;CT=5to5;CIPOS=-9,9;CIEND=-9,9;SRMAPQ=60;INSLEN=0;HOMLEN=10;SR=3;SRQ=1;CONSENSUS=AGACACTCCTGAAGAAAACCCTTATTTCCCTACGTACAAATTCCCTGAACTTCCTGTGACCACTGGGGCACTGTTTTGTCAC;CE=1.96142;RDRATIO=0.212037;SOMATIC | GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV | 0/1:-9.48882,0,-24.1886:95:PASS:84:269:1156:0:0:0:8:4 | 0/0:0,-8.12547,-100.298:81:PASS:82:379:288:2:0:0:27:0 | 0/0:0,-12.9388,-157.794:129:PASS:155:620:451:2:0:0:43:0 | 0/0:0,-10.8321,-129.595:108:PASS:109:479:345:2:0:0:36:0 | 0/0:0,-7.5229,-89.8971:75:PASS:128:689:1575:1:0:0:25:0 | 0/0:0,-6.92151,-84.3978:69:PASS:196:652:1690:1:0:0:23:0 | 0/0:0,-5.41696,-66.5984:54:PASS:69:345:807:1:0:0:18:0

I have a few more examples, wondering if they are actually supposed to be removed 

`> setdiff(dm2.ids, dm1.ids)`
` [1] "chr2-159097292"                  "chr5-110032976"                 
 [3] "chr5-144206781"                  "chr12-56546969"                 
 [5] "chr13-77015268"                  "chr15-101122294"                
 [7] "chr19-31246669"                  "chr19-33226154"                 
 [9] "chrX-121348166"                  "chrX-136877632"                 
[11] "chrUn_KN707645v1_decoy-621"      "chrUn_KN707967v1_decoy-4191"    
[13] "chrUn_JTFH01000013v1_decoy-33"   "chrUn_JTFH01000225v1_decoy-1336"
[15] "chrUn_JTFH01000225v1_decoy-1683" "chrUn_JTFH01000981v1_decoy-2507"
[17] "chrUn_JTFH01001084v1_decoy-16"  `

Commands used:
1) Somatic SV calling
` delly call -x $exc_list -o $output_dir/$tumour_id.bcf -g $reference $tumour_bam $normal_bam`

2) Somatic pre-filtering
`delly filter -f somatic -o $tumour_id.pre.bcf -s $tumour_id.tsv $tumour_id.bcf`

3) Genotype pre-filtered somatic sites across a larger panel of control samples 
 to efficiently filter false postives and germline SVs
`delly call -g $reference -v $tumour_id.pre.bcf -o $tumour_id.geno.bcf $tumour_bam ${normal_bams[@]}`

4) Post-filter for somatic SVs using all control samples.
`cd $delly_dir/
mkdir -p $output_dir
cat *.tsv > $output_dir/samples.tsv
delly filter -f somatic -o $output_dir/$tumour_id.somatic.bcf -s $output_dir/samples.tsv $tumour_id.geno.bcf
bcftools view $output_dir/$tumour_id.somatic.bcf > $output_dir/$tumour_id.somatic.vcf `

**Comment by tobiasrausch** [comment]
Hi,

There can be indeed also very few differences outside the excluded regions because this exclude map affects all steps of delly. For instance, when delly estimates the insert size parameters, median coverage, etc. this relies on the entire BAM (without -x) or the filtered BAM (with -x) and thus, the cutoffs might be slightly different. Also be aware that the delly IDs are arbitrary so for these kind of SV call set comparisons you should rely on the coordinates of the SVs.

Best, Tobias

**Comment by john-alexander** [comment]
Thanks Tobias. Safe to say we can rely on the filtering then!
