### ISSUE TITLE
Inquiry about -x excl file and option

### ISSUE THREAD

**Issue by OZTaekOppa** [dellytools/delly#266]
Hi all,

I am trying to use Delly for Illumina PE reads (reference genome is Arabidopsis).
It looks like the latest version has updated a few parameters and options. 
And, I am not fully sure about the hg19.excl. 

After reading this https://groups.google.com/g/delly-users/c/OdSpU3-XcME, I have done as below.
And,  I have used all the latest versions for the below steps. 

Mapping and Bam: HiSat2 & Samtools (generated sorted.bam file)
Bed: Bedtools (bedtools bamtobed -i AtAn1HS.sorted.bam -bedpe > AtAn1HS.sorted.bedpe)
It looks like this:
AtCh1   7822    7923    AtCh1   7822    7923    HWI-ST863:142:D0WUCACXX:1:2205:20330:30143_R    0       +       +
AtCh1   8186    8287    AtCh1   8186    8287    HWI-ST863:142:D0WUCACXX:1:2206:13752:89705_F    0       -       -
AtCh1   8618    101858  AtCh1   8618    101860  HWI-ST863:142:D0WUCACXX:1:2107:14351:81918_R    0       +       +

Excl: From this link https://groups.google.com/g/delly-users/c/OdSpU3-XcME, I have renamed the AtAn1HS.sorted.bedpe as AtAn1HS.sorted.excl.

However, my AtAn1HS.sorted.bedpe file does not look like the example file (https://github.com/dellytools/delly/blob/main/excludeTemplates/human.hg19.excl.tsv).

Run Delly (v.0.8.7): delly call -x /work/AtAn1HS.sorted.excl -o delly_AtAn-1PE.bcf -g /work/At10.1_RefRN.fasta /work/AtAn1HS.sorted.bam

BCF to VCF: bcftools (bcftools view delly_AtAn-1PE.bcf > delly_AtAn-1PE.vcf)
It looks like this:
##reference=/work/At10.1_RefRN.fasta
##contig=<ID=AtCh1,length=30427671>
##contig=<ID=AtCh2,length=19698289>
##contig=<ID=AtCh3,length=23459830>
##contig=<ID=AtCh4,length=18585056>
##contig=<ID=AtCh5,length=26975502>
##contig=<ID=AtMt,length=367808>
##contig=<ID=AtCp,length=154478>
##bcftools_viewVersion=1.13+htslib-1.13
##bcftools_viewCommand=view delly_AtAn-1PE.bcf; Date=Thu Oct 14 15:56:24 2021
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  aln-peAtAn1HS.sorted

There was nothing else after #CHROM line. 

If I understood correctly, the .excl file is required to run Delly. 

Q1: Did I miss something from my steps? 
Q2: How can I make the proper .excl file for running Delly. 

Any suggestion would be really appreciated. 

Cheers,

Taek

**Comment by tobiasrausch** [comment]
The TAIR genome assembly is "only" 135Mbp. I think that should work without any exclude file.
