### ISSUE TITLE
Error of Delly Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by pabloangulo7** [dellytools/delly#267]
Hello 

I have an error using delly. When I try to run the CNV Germline, I have an error: Segmentation fault (core dumped). I don't think that it is an installation error because I use the docker version, and the bam files I use were valid for other programs but with delly I have this error.

![delly_error](https://user-images.githubusercontent.com/70705390/138739628-3e852e30-1693-43e4-a551-84899bb78f8c.png)

Thanks

**Comment by TrinidadMartin** [comment]
Hello Tobias!
I think I need a bit of help here... I have done this call for delly

`./src/delly call -q 40 -g /mnt/d/Pooled_linkage_analysis/S288C_genome.fasta -o delly7B.bcf /mnt/server/trini_tonterias/Pool
ed_linkage_analysis/files4_SNPanalysis/7B_bwa_mem_S288c_alignment.sorted.markedDuplicates.AddReadGroups.bam /mnt/server/trini_tonterias/Pooled_linkage_analysis/files4_SNPanalysis/7B
_control_bwa_mem_S288c_alignment.sorted.markedDuplicates.AddReadGroups.bam`

I have two bam files aligned with BWA, sorted and duplicates marked with picard tools. As you can see I am trying to compare them as one is control and the other is mutant lets say.

After hours of running, I got the same error:

`[2021-Dec-16 17:08:47] Paired-end and split-read scanning

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-Dec-16 18:24:34] Split-read clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-Dec-16 18:24:42] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-Dec-16 18:25:03] Split-read assembly

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-Dec-16 20:51:37] Generate REF and ALT probes

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2021-Dec-16 20:51:37] SV annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[E::bcf_hdr_add_sample_len] Duplicated sample name '20'
[2021-Dec-16 23:03:54] Genotyping

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*Segmentation fault (core dumped)
trini@Wavemaster:/mnt/d/Pooled_linkage_analysis/SV/delly$`

Any ideas??

Thanks a lot!!
Trini

**Comment by tobiasrausch** [comment]
The 2 bam files use the same sample name. That's not good and causes the crash. The BAM files should always have unique sample names and I now added a sanity check for this to the code.

**Comment by TrinidadMartin** [comment]
> 

Hello!!

Thanks for the super fast answer!!
They do not have the same name, the first one is 7B and the second one 7B_control, so I guess that's not the problem ;)

Thanks again!!
T

**Comment by tobiasrausch** [comment]
What matters is the sample name inside the BAM file and that appears to be "Duplicated sample name '20'"

**Comment by TrinidadMartin** [comment]
Could you tell me how to check that?? It is weird... They always had different names before the alignment...

Thanks!
T

**Comment by tobiasrausch** [comment]
samtools view -H input.bam | grep --color "SM:"

**Comment by TrinidadMartin** [comment]
Thanks a lot!! I changed the SM and it worked
