### ISSUE TITLE
Multithreading with Conda version

### ISSUE THREAD

**Issue by astulaaa** [dellytools/delly#268]
Hello,

I installed Delly Conda version and among the parameters offered I do not see anything for multithreading.
Is it possible to do multithreading  using Delly from Conda using Solar grid engine? Could you suggest any way to parallelize the work?

Thank you,
Asta

**Comment by tobiasrausch** [comment]
I think the conda version is indeed single-threaded. You can compile from source for multi-threading but delly only parallelizes on the sample level. For single-sample SV calling the single-threaded version is as good as it gets at the moment for delly.

**Comment by fgvieira** [comment]
I've made a [PR](https://github.com/bioconda/bioconda-recipes/pull/32786#issue-1125619695) and changed Delly Conda version to parallel (setting the flag `PARALEL=1`) but, when running it with 8 sample, it seems it still uses only one thread.

**Comment by tobiasrausch** [comment]
Should be fine.
