### ISSUE TITLE
Mappability map for T2T CHM13

### ISSUE THREAD

**Issue by davidebolo1993** [dellytools/delly#269]
Hi all, hi @tobiasrausch

I hope you are doing well. This is not an issue at all, just a quick question on delly for [CNV detection](https://github.com/dellytools/delly#read-depth-profiles). This requires a mappability map but, for human data, [those available through gear](https://gear.embl.de/data/delly/) are limited to hg19/hg38. I'm interested in calling cnv with the new T2T CHM13. Any suggestions on how to produce comparable mappability maps for this reference ?
Also, I remember I tried the old "coral" (which I'm assuming is now part of delly) with short reads. Is this CNV detection strategy compatible with long reads as well?

Thanks,

Davide

**Comment by davidebolo1993** [comment]
Just saw that the first question is answered in the [FAQs](https://github.com/dellytools/delly#faq). Feel free to ignore that part. 

Thanks

**Comment by tobiasrausch** [comment]
Hi Davide, 

The CNV detection is for short reads only because all the mappability maps have been generated using paired-end illumina data. I did not compute a mappability map for CHM13 so far.

Best regards, Tobias

**Comment by davidebolo1993** [comment]
Hi Tobias, 

thanks. I'm closing the issue. 

Best,

Davide
