### ISSUE TITLE
Unexpected genotyping and filtering results

### ISSUE THREAD

**Issue by MathijsSanders** [dellytools/delly#270]
Dear Tobias,

Thank you for providing and maintaining Delly. I have compiled Delly from this GitHub page to ensure working with the latest iteration (v0.8.7).

I am calling (semi-)somatic SVs by comparing the tumour sample to a batch of unmatched germline controls. However, today I noticed the lack of a somatic BND known to be present and observable in IGV. Command for calling:

delly call -t BND -r15 -c20 -d 2016-2584.gz -o ./2016-2584_unmatched.bcf -g /genomes/homo_sapiens/hg19/bwa2/hg19.fa 2016-2584_markdup.bam ./germline/2838-germline_markdup.bam ./germline/2899-germline_markdup.bam ./germline/3060-germline_markdup.bam ./germline/3085-germline_markdup.bam ./germline/T07763-germline_markdup.bam ./germline/T07979-germline_markdup.bam ./germline/T08127-germline_markdup.bam ./germline/T08457-germline_markdup.bam

The resultant VCF file highlights the presence of HQ variant pairs in 2 germline controls:

chr20   38466029        BND00000330     A       ]chr14:106056553]A      224     PASS    IMPRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.7;END=38466030;CHR2=chr14;POS2=106056553;PE=5;MAPQ=54;CT=5to3;CIPOS=-308,308;CIEND=-308,308        GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-20.5938,0,-4.20087:42:PASS:507:1151:644:2:1:5:0:0  0/0:0,-1.92287,-26.5157:19:PASS:0:0:0:-1:7:0:0:0        0/1:-4.55333,0,-15.3949:46:PASS:0:0:0:-1:4:1:0:0        0/0:0,-1.50515,-30:15:PASS:0:0:0:-1:5:0:0:0     0/0:0,-1.20411,-22.8:12:LowQual:0:0:0:-1:4:0:0:0        0/0:0,-0.903089,-18:10:LowQual:0:0:0:-1:3:0:0:0 0/0:0,-0.579727,-6.57767:7:LowQual:0:0:0:-1:2:0:0:0     0/0:0,-1.50515,-30:15:PASS:0:0:0:-1:5:0:0:0     0/1:-4.49512,0,-17.6949:45:PASS:0:108:108:2:4:1:0:0

However, looking at the SV data dump reveals that the 2 germline cases have mate-pairs that do not fit the 'imprecise' junction. While in both cases one read aligns close to 1 of the 2 BND breakpoints, the other mate aligns on an entirely different chromosome than the junction of interest or far away from the second breakpoint (300+ kb). **Did I do something wrong? Is this expected behavior?** See below (2016-2584: sample of interest, other: germline controls):

BND00000330	2016-2584_markdup.bam	M07024:108:000000000-K4588:1:1109:22153:11300	chr20	38466028	chr14	106055992	60	PE
BND00000330	2016-2584_markdup.bam	M07024:108:000000000-K4588:1:1110:26018:14111	chr20	38466028	chr14	106056205	60	PE
BND00000330	2016-2584_markdup.bam	M07024:108:000000000-K4588:1:2104:22674:22403	chr20	38466028	chr14	106056461	60	PE
BND00000330	2016-2584_markdup.bam	M07024:108:000000000-K4588:1:1108:20673:16484	chr20	38466067	chr14	106056432	60	PE
BND00000330	2016-2584_markdup.bam	M07024:108:000000000-K4588:1:2114:24970:19295	chr20	38466290	chr14	106056431	60	PE
BND00000330	./germline/2899-germline_markdup.bam	M07024:103:000000000-K3C26:1:1103:20208:20252	chr14	106056451	chr2	242500778	60	PE
BND00000330	./germline/T08457-germline_markdup.bam	M07024:103:000000000-K3C26:1:1113:6921:26057	chr20	38466389	chr14	106399801	60	PE

**Taking out 2899-germline and T08457-germline solves the problem. Leaving either germline control in results in the BND being filtered out.**

**Comment by tobiasrausch** [comment]
Dear Mathijs,

Many thanks for reporting this bug! I rewrote the paired-end genotyping because the BND index jumps were quite I/O intensive and I am a bit puzzled I forgot to take care of this. Very embarrassing but it should be fixed now. Can you please check again with the latest code? I am very sorry that I overlooked this.

Best, Tobias

**Comment by MathijsSanders** [comment]
Dear Tobias,

No problem at all! Thank you for the fast reply and fix!

Recompiled the code and rerun Delly using the same calls and parameter settings. All is working fine now! The genotype calls in all germline controls are set to 0/0 as expected and the SV previously missed is now present in the final filtered output.

Thanks again for the great help.

Best,

Mathijs

**Comment by tobiasrausch** [comment]
Great, thanks for letting me know. I also released a new version now with this bug fix.
