### ISSUE TITLE
Germline SV calling Whole exome sequence

### ISSUE THREAD

**Issue by smkumaran** [dellytools/delly#275]
Hi,

Can delly be used for SV calling in WES (whole exome sequence) for a single sample? what is the minimum samples required for doing SV-calling in WES?

Thank you

**Comment by tobiasrausch** [comment]
Delly was designed for WGS data and I wouldn't recommend doing SV calling with WES data. The cnv mode works reasonably good with WES data but you need to input the target regions using `delly cnv -b targets.bed ...`.

**Comment by smkumaran** [comment]
Ok. Thanks for your suggestion and input file information for WES.
