### ISSUE TITLE
symbol lookup error with bioconda delly 0.9.1

### ISSUE THREAD

**Issue by jdm204** [dellytools/delly#276]
After installing Delly through bioconda with 

```
conda install -c bioconda -c conda-forge -n delly delly=0.9.1
```
and running a `delly call` command, I get the error

```
delly: symbol lookup error: delly: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE
```

I've tried explicitly adding boost to the environment by appending `boost=1.7.4` to the conda install command but I still get the error. The static binary from the release page seems to work, but for reproducibility and automation reasons (part of a snakemake pipeline) I would prefer to install through a conda environment.

**Comment by tobiasrausch** [comment]
I think this should work now, can you please try again?

**Comment by jdm204** [comment]
> I think this should work now, can you please try again?

Yep working, many thanks!
