### ISSUE TITLE
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GENEDECODERS** [dellytools/delly#277]
when I running dell call, I got the error information:
delly: error while loading shared libraries: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory, 
Is there any solution to this?

**Comment by tobiasrausch** [comment]
Looks like you linked the code against a boost library that is not available at runtime. You can search for boost:

`find /usr/ -name "libboost_iostreams.so*" -print`

and then add the directory to the `LD_LIBRARY_PATH` environment variable.

**Comment by GENEDECODERS** [comment]
I added by "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.71.0:$LD_LIBRARY_PATH" in the by "vi vi ~/.bashrc", the error is still there. I checked the lib directory. The directory has "libboost_iostreams.so.1.71.0", but delly ask for "libboost_filesystem.so.1.67.0". I copied "libboost_iostreams.so.1.71.0" with the name of "libboost_filesystem.so.1.67.0". It still didn't work.

**Comment by tobiasrausch** [comment]
You compiled against v1.67.0 but your system apparently has v1.71.0. This cannot work, please use the static binaries of delly from the [release page](https://github.com/dellytools/delly/releases).

**Comment by tobiasrausch** [comment]
Good, the static binary is working then, just use delly_v0.9.1_linux_x86_64bit
