### ISSUE TITLE
Interpretation of Delly SV Call output

### ISSUE THREAD

**Issue by vivekruhela** [dellytools/delly#278]
Hello,

I am trying to interpret structural variants obtained using delly. I am getting the following header in the output file:

`
Specimen_ID | SVTYPE | CHROM | POS | ID | REF | CHR2 | ENDPOSSV | CIPOS | MAPQ | PE | SR | SRQ | CE | CT | IMPRECISE | PRECISE | HOMLEN | RDRATIO | LENSV | RGENUPS_ENSG | RGENUPS_HUGO | RGENUPS_Distance | RGENUPS_Strand | RGENISEC_ENSG | RGENISEC_HUGO | RGENISEC_Distance | RGENISEC_Strand | RGENDNS_ENSG | RGENDNS_HUGO | RGENDNS_Distance | RGENDNS_Strand | LGENUPS_ENSG | LGENUPS_HUGO | LGENUPS_Distance | LGENUPS_Strand | LGENISEC_ENSG | LGENISEC_HUGO | LGENISEC_Distance | LGENISEC_Strand | LGENDNS_ENSG | LGENDNS_HUGO | LGENDNS_Distance | LGENDNS_Strand | NORMAL_GT | TUMOR_GT | NORMAL_GL_RR | TUMOR_GL_RR | NORMAL_GL_RA | TUMOR_GL_RA | NORMAL_GL_AA | TUMOR_GL_AA | NORMAL_GQ | TUMOR_GQ | NORMAL_FT | TUMOR_FT | NORMAL_RC | TUMOR_RC | NORMAL_RCL | TUMOR_RCL | NORMAL_RCR | TUMOR_RCR | NORMAL_CN | TUMOR_CN | NORMAL_DR | TUMOR_DR | NORMAL_DV | TUMOR_DV | NORMAL_RR | TUMOR_RR | NORMAL_RV | TUMOR_RV | NORMAL_RCALT | TUMOR_RCALT | NORMAL_RDISTDISC1 | TUMOR_RDISTDISC1 | NORMAL_RDISTDISC2 | TUMOR_RDISTDISC2 | NORMAL_RCDIS1 | TUMOR_RCDIS1 | NORMAL_RCDIS2 | TUMOR_RCDIS2 | CONSENSUS | isBalTra | dupBalTraToRemove`

I didn't find any documentation that explain the meaning of these terms. Can you suggest the meaning of these terms or link of the proper documentation. Thanks

**Comment by tobiasrausch** [comment]
That's not a delly sv output header. Looks like somebody has post-processed delly SV calls and I am of course not familiar with this. Delly does not output *HUGO*, *RCDIS*, *LGEN* ...
