### ISSUE TITLE
Speed Issue Delly

### ISSUE THREAD

**Issue by skose82** [dellytools/delly#280]
Hi there,

I know the -n option is now default to ignore small Indels and other default options have been placed for speed. However, I am still experiencing lag time. Run time is currently at ~24 hours. I realise the annotation step will take a while. How long is the expected time Delly requires to run 1 WGS sample in germline mode? Is there a way to speed this up?

Any help would be greatly appreciated.

command run: delly call -g hg38.fa -o s1.bcf -x hg38.excl sample1.bam

Paired-end and split-read scanning

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

[2022-Apr-07 11:17:50] Split-read clustering

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

[2022-Apr-07 11:18:18] Paired-end clustering

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

[2022-Apr-07 11:18:21] Split-read assembly

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

[2022-Apr-07 12:18:55] Generate REF and ALT probes

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

[2022-Apr-07 12:22:46] SV annotation

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|
*

**Comment by tobiasrausch** [comment]
For germline SVs, most are mainly interested in deletions and insertions (long reads) but not in interchromosomal SVs (BND SV type). So you can parallelize by chromosome and optionally only do DEL and INS.
