### ISSUE TITLE
DELLY with conda

### ISSUE THREAD

**Issue by josiejenyne** [dellytools/delly#281]
I am trying to use germline SV call but when I do so through conda, I get this error. When I install with conda, it install version 0.8.1 with boost v1.67.0 and HTSlib v1.9. I tried forcing condda to install 0.9.1 but there were some incompatibility errors. What can I do?
```
dyld[9275]: missing symbol called
zsh: abort      delly call -g hg19.fa -o s1.bcf subj1_dnaseq_markdup.bam
```

**Comment by tobiasrausch** [comment]
For conda, this should work for the latest delly version (v1.0.3):

`cd /tmp`
`wget 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh'`
`bash Miniconda3-latest-Linux-x86_64.sh -b -p /tmp/conda`
`export PATH=/tmp/conda/bin:${PATH}`
`conda install -y -n base -c conda-forge -c bioconda mamba`
`source activate base`
`mamba install -y -c conda-forge -c bioconda delly=1.0.3`
`delly --version`

**Comment by tobiasrausch** [comment]
Of course, you can change the `tmp` directory to any other directory for installation.
