### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [dellytools/delly#284]
Hi developer, 

I am trying to install Delly with 'make all' and encountered the following issue:

g++ -isystem /lustre/scratch/scratch/ucnvlw0/bioinfo_tools/Delly/delly/src/htslib/ -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive -DNOPENMP -O3 -fno-tree-vectorize -DNDEBUG src/delly.cpp src/edlib.cpp -o src/delly -L/lustre/scratch/scratch/ucnvlw0/bioinfo_tools/Delly/delly/src/htslib/ -L/lustre/scratch/scratch/ucnvlw0/bioinfo_tools/Delly/delly/src/htslib//lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time  -lhts -lz -llzma -lbz2 -Wl,-rpath,/lustre/scratch/scratch/ucnvlw0/bioinfo_tools/Delly/delly/src/htslib/
In file included from src/delly.cpp:17:0:
src/delly.h:8:42: fatal error: boost/graph/adjacency_list.hpp: No such file or directory
 #include <boost/graph/adjacency_list.hpp>
                                          ^
compilation terminated.
src/edlib.cpp:1191:36: warning: use of C++11 long long integer constant [-Wlong-long]
     long long alignmentDataSize = (2ll * sizeof(Word) + sizeof(int)) * maxNumBlocks * targetLength
                                    ^
src/edlib.cpp:1192:11: warning: use of C++11 long long integer constant [-Wlong-long]
         + 2ll * sizeof(int) * targetLength;
           ^
src/edlib.cpp: In function ‘int obtainAlignment(const unsigned char*, const unsigned char*, int, const unsigned char*, const unsigned char*, int, const EqualityDefinition&, int, int, unsigned char**, int*)’:
src/edlib.cpp:1191:10: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
     long long alignmentDataSize = (2ll * sizeof(Word) + sizeof(int)) * maxNumBlocks * targetLength
          ^
make: *** [src/delly] Error 1

I have also tried to install Dellyl with conda, however got an error like this 'error while loading shared libraries: libboost_iostreams.so.1.67.0: ca'. I then followed issue#277 to search for boost 'find /usr/ -name "libboost_iostreams.so*" -print'.
This is what I got:
find: ‘/usr/libexec/initscripts/legacy-actions/auditd’: Permission denied
/usr/lib64/libboost_iostreams.so.1.53.0

Please could you help that out? 
Many thanks!

**Comment by tobiasrausch** [comment]
The compilation error is due to a missing boost library. You need to install boost on your system to compile from source. Conda should work and I suspect your conda environment is corrupted. I would suggest to install an isolated conda environment using miniconda, e.g. using the `tmp` directory:

`cd /tmp`
`wget 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh'`
`bash Miniconda3-latest-Linux-x86_64.sh -b -p /tmp/conda`
`export PATH=/tmp/conda/bin:${PATH}`
`conda install -y -n base -c conda-forge -c bioconda mamba`
`source activate base`
`mamba install -y -c conda-forge -c bioconda delly=1.0.3`
`delly --version`

**Comment by CLAIRE-cuhk** [comment]
Great thanks for your reply!

This environment works fine.
(base) $delly --version
Delly version: v1.0.3
 using Boost: v1.74.0
 using HTSlib: v1.15.1

Does the germline and somatic variants calling modes work for ONT reads?

Claire

**Comment by tobiasrausch** [comment]
Yes, germline and somatic filtering should work. Long-read cancer genome data is still very scarce, so please let me know if you run into any problems.

**Comment by CLAIRE-cuhk** [comment]
Yes, I found there wasn't a benchmarked pipeline help distinguish germline and somatic SV for ONT reads. I tried several SV callers originally designed for short reads SV calling and they don't seem to give consist results for long reads. I will try Delly and let you know if there is any problem. 
Thank you again for your help!
