### ISSUE TITLE
Delly output to stdout

### ISSUE THREAD

**Issue by fgvieira** [dellytools/delly#286]
Is it possible to have delly output to `stdout`?
It would sometimes be nice to pipe directly to `bcftools` ot other tools.

**Comment by tobiasrausch** [comment]
In principle a good suggestion. What has prevented me from doing this so far is that I then have to redirect the status messages from delly to stderr (like bwa for example). A few years ago, HPC employees advised me against it. Delly also occasionally prints warnings to stderr, which may then be lost. I'm honestly a little undecided.

**Comment by fgvieira** [comment]
Personally, I don't think it is a problem to redirect status messages to stderr, as long as they are clearly labeled (e.g. as log, warning or error).

Not sure what why you say warning messages may be lost though.

**Comment by tobiasrausch** [comment]
Sorry for the delay. Delly output is now on stdout by default, e.g.:

`delly call -g ref.fasta input.bam > out.vcf`

or equivalently:

`delly call -g ref.fasta -o - input.bam > out.vcf`

Anything other than `-` outputs a BCF file.

`delly call -o out.bcf -g ref.fasta input.bam`

Status messages are now on stderr and progress display was dropped (deprecated in boost).

Does this work for snakemake?

**Comment by fgvieira** [comment]
That sounds perfect! I'll give it a try.
Thanks,

**Comment by tobiasrausch** [comment]
Thanks. If there is a problem with the output to stdout please open a new issue. It should work with delly v1.1.3.
