### ISSUE TITLE
interpretation of direction values not matching known logic

### ISSUE THREAD

**Issue by abhatta-bbi** [dellytools/delly#289]
While reading code I found following logics not matching my understanding of inversion and other sv events:

Inversion:	   Same chr, different direction, agreeing soft-clips

If that direction is representing whether a read is reverse complement to map to reference or not then it should be Same chr, same direction, agreeing soft-clips.

For Duplication, Deletion it should be Same chr, different direction, opposing soft-clips

Could you please check and confirm why this logic is just opposite inside junction.h file?

**Comment by abhatta-bbi** [comment]
Tested with some in silico SV samples. It is working with current sv rules

**Comment by tobiasrausch** [comment]
Thanks for confirming.
