### ISSUE TITLE
SR query

### ISSUE THREAD

**Issue by hannahgoldswain** [dellytools/delly#290]
Hiya!

What does SR in the output stand for and mean? Are there any sensible cut offs for this value? I can't find this information- thanks in advance!

BW,
Hannah

**Comment by tobiasrausch** [comment]
Hi,

I think there is a lot of information about SR (and DV and RV) in the [delly-user group](http://groups.google.com/d/forum/delly-users) which is searchable. In short, SR is the split-read support for an SV.

Best, Tobias
