### ISSUE TITLE
All runs stuck at 50% Split-read assembly

### ISSUE THREAD

**Issue by andreaswallberg** [dellytools/delly#292]
Dear all,

I am running delly on 12 samples of a non-model organism with a large, complex and relatively fragmented genome assembly (a couple of hundred thousands contigs). All runs process data up until a certain point and then seem to get stuck and stop printing any log messages, while still burning 100% CPU. I have adjusted parameters to avoid translocations.

Below is a typical log (edited to retract organism etc for now).

Any ideas about what might be going on at this stage and how I can parameterize delly to sidestep this issue?

```
[2022-May-28 23:56:31] delly call -s 15 -r 200 -q 5 -g <REFERENCE> -o <OUTPUT> <INPUT.BAM> 
[2022-May-28 23:56:42] Paired-end and split-read scanning

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2022-May-29 00:55:25] Split-read clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2022-May-29 09:12:11] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2022-May-29 09:13:11] Split-read assembly

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************
```

**Comment by tobiasrausch** [comment]
Hi,

Basically, when Delly is stuck in the assembly step, it is a sign of a large set of candidate SVs. That would fit to a fragmented genome assembly. I would suggest to exclude first all small contigs (<10kbp) from the BAM and then run delly by SV type, i.e.:

`delly call -g genome.fa -t INV -q 5 -s 15 -z 5 input.bam`

**Comment by tobiasrausch** [comment]
I am not sure if the above worked. Feel free to re-open this issue if you still have problems.
