### ISSUE TITLE
Difference between germline SV vs germline CNV?

### ISSUE THREAD

**Issue by kvn95ss** [dellytools/delly#293]
We have 20+ whole genome samples (affected with rare disorders) and would like to try the germline filtering.

There are two options for doing this -

```delly call``` for germline SV calling

```delly cnv``` for germline CNV calling

Since we are interested in finding all structural rearrangements, we are leaning towards germline SV, but wanted to know the differences between them.

**Comment by tobiasrausch** [comment]
Structural variant calling relies on paired-end and split-reads. CNV calling relies on read-depth.

For structural rearrangements you indeed want to use SV calling: `delly call`

**Comment by kvn95ss** [comment]
So would it be correct to assume Structural variant via ```delly call``` _doesn't_ rely on read-depth?

**Comment by tobiasrausch** [comment]
Exactly, `delly call` does not use read-depth.
