### ISSUE TITLE
core dumped with delly merge

### ISSUE THREAD

**Issue by chenlu-Liu** [dellytools/delly#298]
Hello, I used conda to install and run delly v1.1.3, but there was a problem in delly merge.

The enviroment:
$delly --version
Delly version: v1.1.3
 using Boost: v1.71.0
 using HTSlib: v1.15.1

The command I used as below:
delly merge -o SV_merge_delly.bcf sample1_delly.bcf sample2_delly.bcf

Error:
[2022-Aug-23 11:10:44] delly merge -o SV_merge_delly.bcf sample1_delly.bcf sample2_delly.bcf
terminate called after throwing an instance of 'boost::wrapexcept<boost::uuids::entropy_error>'
  what():  getrandom

Could you please help me with this problem?
Thank you.

**Comment by Br1anChou** [comment]
I have encountered the same issue, is there any solution?

**Comment by tobiasrausch** [comment]
The Boost library uses a getrandom system call that appeared in the Linux 3.17 kernel. Can you find out what kernel version you are using with `uname -r`?

**Comment by chenlu-Liu** [comment]
> The Boost library uses a getrandom system call that appeared in the Linux 3.17 kernel. Can you find out what kernel version you are using with `uname -r`?

$uname -r
3.10.0-514.el7.x86_64

I'm not sure how to to deal with this issue. Could you please give me some advice? 
Thank you!

**Comment by tobiasrausch** [comment]
Using now POSIX getrandom, I hope that works. Can you please try the new version, delly v1.1.5? It will take ~1 day until that's available from bioconda or you can immediately try the static binary of delly:

 `wget https://github.com/dellytools/delly/releases/download/v1.1.5/delly_v1.1.5_linux_x86_64bit`
 `mv delly_v1.1.5_linux_x86_64bit delly`
 `chmod a+x delly` 
 `./delly -v`

**Comment by tobiasrausch** [comment]
v1.1.5 is now also on bioconda. I hope this is fixed. Please re-open if that's not the case. Thanks.

**Comment by chenlu-Liu** [comment]
> 
It works.
Thank you!
