### ISSUE TITLE
There is a big difference between PE,SR and DV,RV. Why?

### ISSUE THREAD

**Issue by hhzhongchn** [dellytools/delly#299]
Hello，Use delly(0.7.9) for somatic SV caller,  I found a big difference between PE,SR and DV,RV,  below：

![image](https://user-images.githubusercontent.com/72648321/186381271-f46d4ed4-5478-471e-bae4-c91f399bb99f.png)
![image](https://user-images.githubusercontent.com/72648321/186381308-9c56badf-cdf9-4635-86ff-70fc0fa5292e.png)

Can you tell me why?

**Comment by tobiasrausch** [comment]
Hi,
I think this has been answered before in the [delly-users group](https://groups.google.com/g/delly-users/). In short, Delly's SV discovery step (INFO fields) is not exhaustive. As soon as delly has enough evidence for an SV it stops aggregating paired-ends and split-reads for performance reasons. The SV genotyping is exhaustive but also more stringent in the REF and ALT haplotype alignments. In most cases, you will thus see DV >= PE and RV >= SR, except for SVs where the ALT and REF alignments are very similar (potential false positive SVs).
Best, Tobias

**Comment by hhzhongchn** [comment]
I manually counted the number of supporting SV-reads(delly call -d options), it is always similar to PE. 
Can I understand that the evidence in the gzipped output file for SV-reads is incomplete?

**Comment by tobiasrausch** [comment]
For the dump option `-d` please use the latest delly version v1.1.3. If I remember correctly there was a minor bug with that option in prior versions.
