### ISSUE TITLE
About SV detection of Pacbio Hifi

### ISSUE THREAD

**Issue by ClarenceHsiang** [dellytools/delly#300]
Dear delly team:

In our case, we have resequencing data of mutant and Pacbio Hifi sequencing data of the wild type.
I used the "pbmm2 align ref.fa movie1.Q20.fastq ref.movie1.bam --sort --preset CCS --sample sample1 --rg '@RG\tID:movie1'" (https://github.com/PacificBiosciences/pbsv) to get the long-reads mapping bam file.
Then, I used Delly "Somatic SV calling" for calling SV variants between wildtype.bam (PacbioHiFi) and mutant.bam (resequencing).
Is it correct? Because the program has run for almost one month.

May Delly team give me some suggestion about the SV analysis by using the dataset of PacbioHifi long reads and short-reads resequencing ?? 

Thank you so much.

**Comment by tobiasrausch** [comment]
For long reads, you need to use `delly lr`.

**Comment by tobiasrausch** [comment]
The speed issues should be solved in delly v1.1.3 (`delly -v`) but please re-open if you still have issues.
