### ISSUE TITLE
Feature request: option to use multiple types at once

### ISSUE THREAD

**Issue by nvnieuwk** [dellytools/delly#301]
Hi, 

Currently it is only possible to specify one type at a time when using `delly call` with the `-t` option. I think it would be a great addition to allow users to specify multiple comma-seperated types (like `-t DEL,DUP,INV`) and get a BCF with all variants from these types instead of having to run the tool multiple times and merging the BCFs afterwards.

Is this something that's possible to add? 

Thanks!

**Comment by tobiasrausch** [comment]
Thanks for the suggestions. That's now possible with `-t DEL,DUP,INV` for instance (without any spaces).

**Comment by nvnieuwk** [comment]
Great! Thanks for adding this!
