### ISSUE TITLE
Strange distribution of QUAL values 

### ISSUE THREAD

**Issue by miyakokodama** [dellytools/delly#302]
Hi,

I am running the latest version of Delly on a GIAB sample (HG002), and have noticed that the distribution of QUAL values for detected SVs looks a little strange - there are many SVS of QUAL = 180, 240, 300, 360, 420...etc (please see attached the figure). Do you happen to know why there are many SVs of such QUAL values?

![Delly_QUAL_values](https://user-images.githubusercontent.com/23519532/188839511-2e2c5457-3836-4415-8cc4-2adf1bd9540d.png)

**Comment by tobiasrausch** [comment]
Delly uses the read mapping qualities for estimating genotype qualities and the overall QUAL. If you plot MAPQ, you will notice similar issues (depending on the mapper) with many reads having MAPQ=0 or MAPQ=60 and this basically propagates into Delly QUAL values.
