### ISSUE TITLE
Delly bcf output annotation

### ISSUE THREAD

**Issue by jiaren-zhang** [dellytools/delly#303]
Hi just wondering, what kind of annotation tool suitable for SV annotation (gene name annotation is fine) as Delly's output is bcf format.

**Comment by tobiasrausch** [comment]
I think [VEP](https://www.ensembl.org/info/docs/tools/vep/index.html) and [SnpEff](http://pcingola.github.io/SnpEff/) support SVs increasingly better but you may have to adapt delly's output format to their required input. [Delly-sansa](https://github.com/dellytools/sansa) should work directly on delly's output file.
