### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by HeejunJang** [dellytools/delly#304]
Hello,

here's my error log

g++ -std=c++11 -isystem /work/setup/delly/src/htslib/ -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive -DNOPENMP -O3 -fno-tree-vectorize -DNDEBUG src/delly.cpp src/edlib.cpp -o src/delly -L/work/setup/delly/src/htslib/ -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time  -lhts -lz -llzma -lbz2 -Wl,-rpath,/work/setup/delly/src/htslib/
In file included from src/delly.cpp:20:0:
src/merge.h: In function ‘void torali::mergeBCFs(torali::MergeConfig&, const std::vector<boost::filesystem::path>&)’:
src/merge.h:813:38: warning: ignoring return value of ‘int bcf_write(htsFile*, bcf_hdr_t*, bcf1_t*)’, declared with attribute warn_unused_result [-Wunused-result]
     bcf_write1(fp, hdr_out, rec[idx]);
                                      ^
In file included from src/delly.cpp:24:0:
src/dpe.h: In function ‘int torali::dpeRun(const torali::DoublePEConfig&)’:
src/dpe.h:251:37: warning: ignoring return value of ‘int bcf_write(htsFile*, bcf_hdr_t*, bcf1_t*)’, declared with attribute warn_unused_result [-Wunused-result]
        bcf_write1(ofile, hdr_out, r);
                                     ^
/usr/bin/ld: cannot find -lboost_iostreams
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_program_options
/usr/bin/ld: cannot find -lboost_date_time
collect2: error: ld returned 1 exit status

please help

**Comment by tobiasrausch** [comment]
You need to install the boost libraries, e.g., for ubuntu:

`apt-get install -y libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev`

**Comment by HeejunJang** [comment]
> You need to install the boost libraries, e.g., for ubuntu:
> 
> `apt-get install -y libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev`

Thank you, It works.
