### ISSUE TITLE
"Alignment file is missing" error when the input bam file is compressed using PetaGene

### ISSUE THREAD

**Issue by ilavidas** [dellytools/delly#308]
Hello,
Delly complains that the `Alignment file is missing: <input.bam>` when the input .bam file is compressed using PetaGene's technology ([link to PetaGene](https://www.petagene.com/)).

There is a `is_regular_file()` check here: https://github.com/dellytools/delly/blob/ac488c9dd45d8dde9d6920172776d28530133f4e/src/coral.h#L614
which is probably relevant to my issue.
Removing this check resulted in a new error: `Fail to open index for <input.bam>`

I'm a bit reluctant to further modify the source code due to possible negative side-effects.
It would be great if you considered supporting PetaGene-compressed .bam files.

Please let me know if you need any further information.

Thank you.

**Comment by tobiasrausch** [comment]
Are PetaGene-compressed BAM files supported by HTSlib? Delly relies on that library for parsing BAM files.

**Comment by ilavidas** [comment]
Apologies for the radio silence. The problem is probably not on your side.
Still looking into it. Feel free to close the issue.
Thank you.
