### ISSUE TITLE
Redirecting temporary directory

### ISSUE THREAD

**Issue by kimin0402** [dellytools/delly#309]
Does delly support specifying temporary directory?

I'm currently working on calling somatic sv. First, I used `delly call` on one tumor sample and one normal sample, and then filtered it using `delly filter -f somatic`. Now I'm genotyping (annotating) a panel of 30 normal bam files on filtered sites. I'm not parallelizing the genotyping process explicitly, so my command goes like `delly call -g {reference} -v {input.filtered.vcf} -o {output.filtered.annotated.vcf} {bam1} {bam2} ... {bam30}`. But I'm using delly-parallel docker version, and the job seems to work fine with amount of threads I specified with `OMP_NUM_THREADS` variable. Seeing that there are no intermediate files created in the output directory, I'm wondering if annotating a large number of bam files would cause problems taking too much space in temporary directory in the future. 

Besides, since `delly call` with specified vcf is a process of annotating, do I need to include `-x` option? I used exclude bed option in the first step of `delly call` but not in the later step of `delly call`. The job is taking some time, and I thought this was because I was annotating 30 bam files. But in the example given in the README file, annotating step also specified `-x` option, so I'm curious whether this has a large impact on the computation time.

Thank you.

**Comment by tobiasrausch** [comment]
Delly does not require temporary files. The genotyping you can parallelize by sample as described [here](https://github.com/dellytools/delly#germline-sv-calling). For genotyping you do not need to specify `-x`.

**Comment by kimin0402** [comment]
Thank you @tobiasrausch !
