### ISSUE TITLE
How to call and genotype only with split reads?

### ISSUE THREAD

**Issue by FrankFeng2022** [dellytools/delly#312]
Hi Tobias,

I am using delly to detect a large (~21Kb) homozygous germline deletion from amplicon data. The depth of my data is high (~2000X). The breakpoints are very clear, with ~1000X hard-clipped reads at the start and ~1000X soft-clipped reads at the end. The below IGV screenshot shows the end point. However, there are no spanning read pairs supporting this deletion, which is in expectation because we use a pair of primers to target only the breakpoint, and with NGS amplicon data, all the reads from an amplicon align at the same start position. 

![deletion_end_point_at_amplicon](https://user-images.githubusercontent.com/116613293/203285235-f9113102-566f-4102-b627-549dda112d5d.png)

Delly calls this 21Kb deletion, with a wrong `0/0` genotype and a low number of SR (**SR=20**):

```
chr7    117498308       DEL00000000     T       <DEL>   1320    PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv1.1.6;END=117519389;PE=2;MAPQ=60;CT=3to5;CIPOS=-6,6;CIEND=-6,6;SRMAPQ=60;INSLEN=0;HOMLEN=5;SR=20;SRQ=1;CONSENSUS=GTCCCTTGGTAAAATTAAGCCTCATGAACAATTAACTCAAATATACACAAGGCTTGTCTTTTACCCTGCCAAAAGCAAAATCTTAAACTTTTGCTTTAGTATATAAGCCAGCATTCATTGTATCCTATGATGG;CE=1.91837     GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/0:0,-71.4331,-926.076:10000:PASS:0:1928:1638:2:670:2:249:1
```

I used Delly (v1.1.6) with the default parameters `delly call --svtype DEL -g $hg38 bam > $bcf_out`.

I got two questions:

1. Why dose Delly only use 20 split reads? 

2. Is that possible to make delly only use or mainly use split reads to call and genotype this deletion?

Thanks!

Regards,
Frank

**Comment by tobiasrausch** [comment]
The discovery module of delly simply stops searching for more split-reads once it has found enough evidence for a structural variant. Delly's genotyping, however, can be run exhaustively for all aligned reads. Just set -a to something like 100,000:

`delly call -a 100000 ...`

The genotyping fields RR and RV show the reference and alternative read support. For low frequency (sub-clonal) variants, you can get a 0/0 genotype with RV > 0.

**Comment by FrankFeng2022** [comment]
It worked! Thanks Tobias!

Just let you know that the `-a` option is NOT in the help message:

```
$delly call --help

Usage: delly call [OPTIONS] -g <ref.fa> <sample1.sort.bam> <sample2.sort.bam> ...

Generic options:
  -? [ --help ]                      show help message
  -t [ --svtype ] arg (=ALL)         SV type to compute [DEL, INS, DUP, INV, 
                                     BND, ALL]
  -g [ --genome ] arg                genome fasta file
  -x [ --exclude ] arg               file with regions to exclude
  -o [ --outfile ] arg               BCF output file

Discovery options:
  -q [ --map-qual ] arg (=1)         min. paired-end (PE) mapping quality
  -r [ --qual-tra ] arg (=20)        min. PE quality for translocation
  -s [ --mad-cutoff ] arg (=9)       insert size cutoff, median+s*MAD 
                                     (deletions only)
  -c [ --minclip ] arg (=25)         min. clipping length
  -z [ --min-clique-size ] arg (=2)  min. PE/SR clique size
  -m [ --minrefsep ] arg (=25)       min. reference separation
  -n [ --maxreadsep ] arg (=40)      max. read separation

Genotyping options:
  -v [ --vcffile ] arg               input VCF/BCF file for genotyping
  -u [ --geno-qual ] arg (=5)        min. mapping quality for genotyping
  -d [ --dump ] arg                  gzipped output file for SV-reads 
                                     (optional)
```

**Comment by FrankFeng2022** [comment]
One more question:

Would this deletion still get called, if there is strong split-read support (i.e. `SR=20` ) and completely no paired-end support (i.e. `PE=0` ) ? 

Thanks, Tobias!

**Comment by tobiasrausch** [comment]
Yes. Since many years delly performs paired-end mapping and split-read calling independently otherwise long-read SV calling wouldn't work.
