### ISSUE TITLE
Understanding DELLY (Version: 0.9.1) output VCF file for BND

### ISSUE THREAD

**Issue by tanbiswas** [dellytools/delly#314]
Hi 

I have used DELLY to identify SVs from tumor-normal paired end WES data. Below is one line from the filtered output VCF as BND:

CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | Tumor | Normal

chr3 | 128308120 | BND00003688 | G | [chr2:27257943[G | 960 | PASS | PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.9.1;END=128308121;CHR2=chr2;POS2=27257943;PE=5;MAPQ=60;CT=5to5;CIPOS=-5,5;CIEND=-5,5;SRMAPQ=60;INSLEN=0;HOMLEN=6;SR=11;SRQ=1;CONSENSUS=TAAGAGCAGAGCTACGGCCAAGCTTGGCCTCCAGCCTCTTCTGAGACCCACTCCTGGGTCTGAATGACAGAGACTGAGGTCACTGCTGAGAGCACCATGGCACCCCCCTCGATGTGGTAGTCGCTGTGCAGCAGGCGGACGAAGGCCAGGTACAGGAGGATGCCAGTGACCATCCAGAGGGAGA;CE=1.96048;RDRATIO=1;SOMATIC | GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV | 0/1:-8.96696,0,-422.948:90:PASS:890:2781:1891:2:102:5:134:15 | 0/0:0,-46.0223,-504.165:10000:PASS:729:1371:642:2:102:0:153:0

If I take it as a  reciprocal translocation, then there should be 4 different locations in the file. 2 for CHR1 (here chr3) and 2 for CHR2 (here chr2). But the file is only having 3 positions. Start position of CHR2 is missing. Then how will I understand that from where and what length of segment is being translocated to the 2nd chromosome (here chr 2). How will I plot these translocation events in circos plot? Also, "[chr2:27257943[G" if this position is the start position of CHR2 then that means only a single base is being translocated, right? How will I find out the length and sequence of the translocated sequence? Is it the "CONSENSUS" sequence is being translocated?

Thanks.

Regards,
Tanay

**Comment by lingchenL** [comment]
Hi,

Can I also ask a question regarding to the above output?

This is the result from columns **Tumor | Normal**
"0/1:-8.96696,0,-422.948:90:PASS:890:2781:1891:2:102:5:134:15 | 0/0:0,-46.0223,-504.165:10000:PASS:729:1371:642:2:102:0:153:0"

Could you please help me to clarify what does the "0/1" and "0/0" means? 

Thanks in advance,
Ling

**Comment by tobiasrausch** [comment]
These are genotypes: 0/0 is hom. reference and 0/1 heterozygous. Please see the [VCF specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf)
