### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by xiekunwhy** [dellytools/delly#315]
Hi,

delly (v1.1.6, conda verson as well as delly_v1.1.6_linux_x86_64bit) always tell me 
FATAL: kernel too old
Aborted

here is my system version (SGE cluster), is there a version which can run normally on eld linux system?
Linux version 2.6.32-696.30.1.el6.x86_64 (mockbuild\@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) \#1 SMP Tue May 22 03:28:18 UTC 2018

Best,
Kun

**Comment by tobiasrausch** [comment]
Hi Kun,
For old kernels, it's usually easiest to take one of the containerized delly versions, i.e. the singularity or docker container.
Best, Tobias
