### ISSUE TITLE
Short insert size

### ISSUE THREAD

**Issue by oghzzang** [dellytools/delly#320]
My data was obtained from very old FFPE samples. So, their insert size is 120 bp.. but we performed 151 bp paired-end sequencing. So our paired end reads are composed of overlapping paired reads.

From your previous response, it seems that there may be issues with paired-end mapping in my situation. If there are truly structural variants in my data, would it be possible to call them using evidence from split reads?

And if a structural variation is observed in an overlapping read pair, does delly annotate the number of split reads as 2 in the VCF or 1?

Many Thanks.!

**Comment by tobiasrausch** [comment]
Split-read calling of SVs would still work in your situation. For SV breakpoints within the overlapping region of a paired-end, delly would indeed assign a support of 2.

**Comment by oghzzang** [comment]
Thank you. I would like to ask for your advice on something.
I have WGS DNA data with an insert size of 120 and 151 bp paired end sequencing data. Which of the following methods would be suitable for your tool?

Option1. Trim the forward and reverse reads by about 50 bp each ➞ map them ➞ and call BNDs with delly2.
Option2. Use the current version of bam files with overlapping read pairs ➞ and call BNDs.

Please let me know which method would be more appropriate for your tool.

Many Thanks!!

**Comment by tobiasrausch** [comment]
Option 2 would be my first choice because you can filter afterwards for PRECISE SVs with single-nucleotide resolution. Option 1 can be useful for inter-chromosomal translocations if these are not aligned properly using split-reads.

**Comment by oghzzang** [comment]
Many thanks. 
I'll try it! thank you @tobiasrausch
