### ISSUE TITLE
How to identify exact break points of the BNDs (interchromosomal translications)?

### ISSUE THREAD

**Issue by MehmetGoktay** [dellytools/delly#322]
Hi, 

I have been searching here also in the delly-users group but I could not find the exact answer. That is why I created another issue here. 

Currently I am interested in identification of translocations (BNDs). Apparently Delly only outputs interchromosomal translocations as BNDs and rest (intrachromosomal translocations) are labelled as Deletions, Insertions, Inversions, Duplications etc. Which is fine. 

But the BNDs that I have identified are always 1bp apart in the reference chromosome. Like this below.

Chr4    5895842 BND00000040     A       A]Chr2:517126]  14      LowQual PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv1.1.6;END=5895843;CHR2=Chr2;POS2=517126;PE=0;MAPQ=0;CT=3to3;CIPOS=-20,20;CIEND=-20,20;SRMAPQ=8;INSLEN=0;HOMLEN=20;SR=2;SRQ=0.957447;CONSENSUS=CCATTATCGTGCTTATATT
TAATTTCAAATTCATTTAGTTACTAAAACTATACATGAATTTGTTTGTTTTCATTCTTTTACGCAATATATAATGT;CE=1.72648 GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-0.496965,0,-3.19748:6:LowQual:891:1413:522:2:0:0:1:2

Chr4: (5895842,5895843 ) and Chr2: (517126,517126 ) Is it an intended behaviour? How to find the start and stop position of the translocation from the reference chromosome (Like on the Chr4 here)? Should I basically add the length of the consensus sequences (for precise ones) to the end of the translocation position? 

Best,
Mehmet

**Comment by tobiasrausch** [comment]
One SV breakpoint is at chr4:5895842 and the other breakpoint is at chr2:517126. I am not sure what the question is?

**Comment by MehmetGoktay** [comment]
Hi Tobias,
thank you for your quick answer. I am trying to find the length of the translocated sequence. As you said one breakpoint is chr4:5895842 and the other breakpoint is at chr2:517126. But how can I get the length of this translocation? 

Best,
Mehmet

**Comment by MehmetGoktay** [comment]
Hi Tobias,

I am closing the issue. Now I have better understanding and the question that I asked somehow cleared in the previous closed issue. https://github.com/dellytools/delly/issues/314

The key sentences here : Delly does not attempt to reconstruct complex rearrangements. Each record in the output of delly is a single structural variant breakpoint.

Thank you,
Mehmet
