### ISSUE TITLE
apply delly on RNA sequencing data

### ISSUE THREAD

**Issue by asaki1986** [dellytools/delly#330]
Hi all,

Delly had been widely approved on DNA sequencing data to find the structural variants/Fusions.

Can I use Delly to find the fusions on RNA sequencing data? For example, which ref.fa should I used, taking input.bam aligned from STAR or bowtie?

Best,
Junfeng

**Comment by tobiasrausch** [comment]
Delly is not suitable for RNA sequencing data.
