### ISSUE TITLE
BAM files have different number of chromosomes!

### ISSUE THREAD

**Issue by nash5202** [dellytools/delly#332]
Hi all, 

I am trying to run delly on some WGS data and am getting that the "BAM files have different number of chromosomes!". Is there a way to get around it and run delly without realigning the data?

Thank you.

Best,
Nash

**Comment by tobiasrausch** [comment]
You need to use the same reference genome with delly that you used for alignment.

**Comment by nash5202** [comment]
Thanks! Indeed that was the case.
