### ISSUE TITLE
calling results for SR and RR/RV

### ISSUE THREAD

**Issue by asaki1986** [dellytools/delly#333]
Hi,

I am using Delly (Version: 1.1.6) to discover the structural variants for target sequencing data.

It was mentioned in the issue that the AF should be calculated with RV/(RV+RR) for precise variants, while DV/(DV+DR) for imprecise ones. 

In the delly.txt, a BND variant was called as follows,

14      106113173       BND00000353     C       C[3:187463411[  10000   PASS    PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv1.1.6;END=106113174;CHR2=3;POS2=187463411;PE=0;MAPQ=0;CT=3to5;CIPOS=-3,3;CIEND=-3,3;SRMAPQ=60;INSLEN=0;HOMLEN=2;**SR=230**;SRQ=0.98855;CONSENSUS=CCTACTCTTCCTGCCCCCACCAGCCCCTGTTCACCTTCAGATGCCCTCCCCTGGTCCCCTGAAGTCCCAGAGCTGCCCCCTGTTCCTCCTGCCTCCCACCAGCCCGAGCTCACCTGCCACTTCGAGGTCCTCATAAGCAGAGCGTCTCGGATTTGGAGGTTCCGGTTCGAGGCTCGAGGGGCCTGAAGGTGGCTCTCCCTCCCCGGGCCCAAGACGATGGTATGGCCTGCTCCGCCACCATCACGTGGGCTCCTCCTCTGTG;CE=1.88875       GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/0:0,-75.2067,-837.549:10000:PASS:598193:840369:242176:2:**0:0:250:0**

It should be the breakpoint I am looking for, however, the SR=230 while the RV=0 and DV=0.

My question is

1. Is this a true SV?
2. Which should I used to calculate the AF?
3. Is there any parameter that I can tuned to refine this result?

Best,
Junfeng

**Comment by tobiasrausch** [comment]
Delly is for WGS data. To make targeted data somehow work with delly, you need to randomly down-sample your BAM to ~60x coverage. You can do this with samtools, i.e., to select 10% of all reads:

`samtools view -s 0.1 -b input.bam > subsample.bam`

**Comment by asaki1986** [comment]
> 106113173

Works!

Best,
Junfeng
