### ISSUE TITLE
`BAM` file type

### ISSUE THREAD

**Issue by bounlu** [dellytools/delly#338]
Hi,

The doc says duplicate marked `BAM` file is needed as the input.

How about duplicated removed (deduplicatede) `BAM` file? Will it work in the same with Delly?

**Comment by tobiasrausch** [comment]
Should be the same if both reads of a pair are removed.

**Comment by bounlu** [comment]
Thanks for the info.

Related to this, does [base quality score recalibration](https://gatk.broadinstitute.org/hc/en-us/articles/360035890531-Base-Quality-Score-Recalibration-BQSR-) affect the way `delly` works? How are the base quality scores used in `delly`? Do you suggest to input recalibrated `BAM` files?

**Comment by tobiasrausch** [comment]
Delly uses mapping qualities, base qualities are not used.
