### ISSUE TITLE
About the output format

### ISSUE THREAD

**Issue by ClarenceHsiang** [dellytools/delly#343]
Dear Delly team,

When I did SV annotation by snpEff, only INS can not be detected by the software.
I am modifying the vcf format, May I ask  
CONSENSUS=XXXXXXX, Is it he insersion sequence in the INFO column?

Thank you so much 

Clarence

**Comment by tobiasrausch** [comment]
The inserted sequence is in the ALT column. INFO/CONSENSUS is a local assembly of the SV allele, i.e., it contains the insertion but also surrounding sequence.

**Comment by ClarenceHsiang** [comment]
![image](https://github.com/dellytools/delly/assets/57841470/6081c917-8514-48c9-a85a-8bcd246ccb20)
Sorry, maybe there is something wrong in my result.  The ALT column showed only <INS>, it seems more details in INFO
For example:
PRECISE;SVTYPE=INS;SVMETHOD=EMBL.DELLYv1.1.3;END=82257;SVLEN=30;PE=0;MAPQ=0;CT=NtoN;CIPOS=-6,6;CIEND=-6,6;SRMAPQ=60;INSLEN=30;HOMLEN=6;SR=20;SRQ=0.991071;CONSENSUS=CCATCGTCGAGGCGAGGGCAAACTGCCGAGGACTCTGCTTCCAGGGCCGCTGGAAAAAGGCCAATAACAGTGGATCTCGACGCGGAGCCGGTGTCGAAGAACGGGCGGCAGACGGAGGTGCCGAGGGCTATCCTTGTTGCCGAAGATGATGACAGCCCTACCGATCCCATCACCATCGCATGTCCATCGAAGACGGTT;CE=1.95842;RDRATIO=1
