### ISSUE TITLE
how to merge the SV into genome

### ISSUE THREAD

**Issue by tinyfallen** [dellytools/delly#346]
Dear developer,

Thanks for the great tools!

My reseach goal is to distinguish the metabolism difference among several subgroups in my populations. I would like to start with the sequence difference among these subgroups. The challenge for me is to dig out the variants which are shared by subgroups in my poplations, while there are 10 to 30 individuals in each subgroup. My first idea is to apply the subgroup-specific SVs, as well as SNPs and InDels, into the reference genome to get a subgroup-specific genome by **bcftools consensus**, so that I could obtain the subgroup-specific genomes for direct comparison.

However, I am confused about the output VCF of delly as it differs from the style of GATK or DeepVariant which records sequence informations of SNPs or InDels. Delly's VCF seems not to record the sequence information for each site. Could you please give me some advices on how to perform **bcftools consensus** using the SVs?

Best regards!

**Comment by tobiasrausch** [comment]
Delly can only report the sequence information for precise SVs, i.e., SVs that can be locally assembled. You thus have to select the SVs that do not use symbolic ALTs (<DEL>, <INV>, ...) but sequences.

**Comment by tinyfallen** [comment]
已收到您发送的邮件！

**Comment by tinyfallen** [comment]
Thanks for your reply! I would have a try soon~
