### ISSUE TITLE
Why SRs are reported when no PEs are indicated

### ISSUE THREAD

**Issue by AriadnaColmeneroCobo** [dellytools/delly#347]
Hello,

I am currently using Delly 1.1.6 for tumor samples via a targeted panel without a normal counterpart. In the results, I observe that some of the BNDs are shown to have SR with a high SRMAPQ (reaching up to 60), while having no PE (PE=0 and consequently, MAPQ=0). I am confused as to why SRs are reported when no PEs are indicated. I was under the impression that it was a sequential process, where PEs were first considered and then SRs were examined to confirm a PRECISE call (precision in breakpoint definition).

Thank you so much,

Ariadna

**Comment by tobiasrausch** [comment]
Hi Ariadna,
Delly nowadays does SV discovery from paired-ends and split-reads independently, which was not the case at the time of the delly manuscript. Thus, you can have SV calls with split-read support only.
Best, Tobias
