### ISSUE TITLE
How to calculate the Fusion mutation frequency from the known information in VCF?

### ISSUE THREAD

**Issue by RADIOMUMM** [dellytools/delly#348]
Hi Delly team,

I would like to know how to calculate the frequency of Fusion variation based on the known information in VCF?
Is there any other information about RR and RV? (I want to find out what they are)?
<img width="953" alt="image" src="https://github.com/dellytools/delly/assets/67082848/5338e0b9-1450-4c03-8574-7f8b51d59cac">

best!

**Comment by tobiasrausch** [comment]
See issue https://github.com/dellytools/delly/issues/146
