### ISSUE TITLE
Two INV just differ by only 1 base

### ISSUE THREAD

**Issue by jackzhong1995** [dellytools/delly#349]
![image](https://github.com/dellytools/delly/assets/101613672/70f2a589-0a46-4fc2-b993-77ffbec5cad5)
The two SV seem like to be just one INV，why delly report the two？

**Comment by tobiasrausch** [comment]
Sure because these inversion-type SV calls are complementary with INFO/CT=3to3 and INFO/CT=5to5. These left- and right-breakpoint spanning paired-ends and split-reads are explained in the delly paper.

**Comment by jackzhong1995** [comment]
@tobiasrausch Thanks for your quickly reply!

**Comment by jackzhong1995** [comment]
Is there any easy way for downstream analysis to filter these record? I just want keep only 1 sv result.

**Comment by tobiasrausch** [comment]
Well, you can filter for INFO/CT=3to3 if you want to get only one type of inversion spanning paired-ends or split-reads.
