### ISSUE TITLE
One SV with two records

### ISSUE THREAD

**Issue by jackzhong1995** [dellytools/delly#350]
Dear Author!
I want to know is there any easy way to filter the two SV record for downstream analysis? I just want keep only 1 sv result.
![image](https://github.com/dellytools/delly/assets/101613672/5ec13580-9b8b-4d95-b5cd-5a1c2690b753)

**Comment by tobiasrausch** [comment]
These are 2 different SV breakpoints (INFO/CT values differ) and that's why delly reports 2 records for such an inversion.
