### ISSUE TITLE
MAPQ quality threshold

### ISSUE THREAD

**Issue by AriadnaColmeneroCobo** [dellytools/delly#352]
Hello!

You mentioned that Delly now handles PE and SR discovery independently rather than as a sequential process. Given this, I have another question. 

In some papers, variants were selected if they had a MAPQ=60, which, as I understand, refers to the PE quality. Consequently, would it be appropriate to establish a threshold based on either MAPQ=60 or SRMAPQ=60, given that these are processes which, as you informed me, are now independent? 

Thank you in advance.

_Originally posted by @tobiasrausch in https://github.com/dellytools/delly/issues/347#issuecomment-1680549757_

**Comment by tobiasrausch** [comment]
Sure, that's fine.
