### ISSUE TITLE
Delly call on WGS data

### ISSUE THREAD

**Issue by Ceonham** [dellytools/delly#355]
Hi Tobias, I'm working on plant genomes and tried to use the germline analysis pipeline you gave to call SVs of 10× resequencing data of a panel of over 200 diverse samples. I first used delly call on each sample in parellel and conbined them to generate a sites.bcf using delly merge. However, when I used delly call to genotype all samples, the following error occured:  **Error: Delly genotyping requires local SV assembly (INFO/CONSENSUS) and breakpoint (INFO/CONSBP) introduced in delly v1.1.7!**

Does the germline pipeline fit with my data? Or I have to use delly call to generate the final vcf with a single thread directly (I failed to configure the multi-threading mode so I installed delly via conda)? Looking forward to your reply. Thank you!

**Comment by tobiasrausch** [comment]
Sorry, this was a bug in delly v1.1.7. I released a new version today (v1.1.8) and now delly merge should keep INFO/CONSBP for genotyping.

**Comment by tobiasrausch** [comment]
👍
