### ISSUE TITLE
merging vcfs of various SV types (delly or bcftools?)

### ISSUE THREAD

**Issue by shaghayeghsoudi** [dellytools/delly#361]
Hello delly developers. 
Thanks for the amazing tool. Recently I started using delly for calling structural variants in "three" Sarcoma cell lines which we obtained from Illumina short read sequencing.
To shorten the run time, I ran delly on each SV type separately and got a separate bcf file for each SV type:

`delly call -t ${name} -o ${OUT_DIR}/${SAMPLE_ID}_${name}_delly.bcf -g ${FASTA} ${INPUT_DIR}/${SAMPLE_ID}.rmdup1.bam  `

I am now trying to merge the vcfs all SV types into one for each cell line (get one concatenated vcf per cell line that contains all SV types INS, DEL, etc).

First I tried delly merge by running `delly merge GCT.*delly.bcf` but I noticed it does not produce the results. 
I tried `bcftools merge ` and obviously it generated the vcf that I want.
I want to ask is this the right approach for merging the vcfs of various SV types into one for each sample? or do you recommend using a different approach for that?
Thank you in advance

**Comment by tobiasrausch** [comment]
`bcftools merge` is for non-overlapping sample sets. If I understand your question correctly you want to merge different SV types for the same sample, which would be `bcftools concat -a ...`

**Comment by shaghayeghsoudi** [comment]
Thanks @tobiasrausch. Yes .. as you said I want to merge different SV types for the same sample. Thanks so much for the suggestion. I am closing this issue as it is resolved now.
