### ISSUE TITLE
min and max SV size

### ISSUE THREAD

**Issue by skeremaydin** [dellytools/delly#362]
Hi, how can I set the min sv size output? delly lr outputs min sv size = 15, I want to add option to get sv size min 50.  
-p [ --max-reads ] arg (=15)          max. reads for consensus computation (from delly lr --help). Is this our option to change?

**Comment by tobiasrausch** [comment]
There is currently no delly option for this but you can easily filter the BCF output using [BCFtools](https://github.com/samtools/bcftools/). For instance, to get deletions greater or equal 50bp:

`bcftools filter -i '((INFO/END - POS) >= 50) && (INFO/SVTYPE=="DEL")' delly.bcf`

**Comment by skeremaydin** [comment]
Thanks. I have seen this code in one of the issues. I will try it now.

**Comment by skeremaydin** [comment]
bcftools filter -i '(INFO/SVLEN == "." || INFO/SVLEN >= 50)' delly/delly_tumor.vcf > delly/dellyfilteredmeta_tumor.vcf
then;
bcftools filter -i '((INFO/SVTYPE="DEL" && INFO/END - POS >= 50) || INFO/SVTYPE!="DEL")' delly/dellyfilteredmeta_tumor.vcf > delly/dellyfiltered_tumor.vcf
you can copy this if someone asks, too
