### ISSUE TITLE
somatic pre filtering issue

### ISSUE THREAD

**Issue by NidhiAgrawal27** [dellytools/delly#363]
Hello,

I am using Delly version: v1.2.6 on Ubuntu.

I ran the following command for somatic SV calling:

TUM_BAM=../data/bam_vcf_files/tumour/orig/tumour.bam
NORM_BAM=../data/bam_vcf_files/control/orig/control.bam
OUT_FILE=../data/bam_vcf_files/sv_vcf/delly_conda_output.bcf
HG38_EXCL=../data/hg38/human.hg38.excl.tsv
CORES=8
REF=../data/GRCh83_d1_vd1/GRCh38.d1.vd1.fa
delly call -x $HG38_EXCL -o $OUT_FILE -g $REF $TUM_BAM $NORM_BAM

It generated output files delly_conda_output.bcf and delly_conda_output.bcf.csi

The header in delly_conda_output.bcf file is:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TCGA-A2-A0YL-01A-21D-A744-36	TCGA-A2-A0YL-10A-01D-A723-36

My delly_samples.tsv file looks like (tab delimited):
TCGA-A2-A0YL-01A-21D-A744-36    tumour
TCGA-A2-A0YL-10A-01D-A723-36    control

I did dos2unix delly_samples.tsv to convert it to unix format.

Now I am running Somatic pre-filtering with command:
IN_FILE=../data/bam_vcf_files/sv_vcf/delly_conda_output.bcf
OUT_FILE=../data/bam_vcf_files/sv_vcf/delly.pre.bcf
SAMP_TSV=delly_samples.tsv
REF=../data/GRCh83_d1_vd1/GRCh38.d1.vd1.fa

delly filter -f somatic -o $OUT_FILE -s $SAMP_TSV  $IN_FILE

It gave me error:
Sample type for TCGA-A2-A0YL-01A-21D-A744-36 is neither tumor nor control

I also tried following command as suggested by you in another similar issue:
delly filter -f somatic -o $OUT_FILE -s $SAMP_TSV -g $REF -m 0 -a 0.05 -r 0.1  $IN_FILE

This gave me error:
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::unknown_option>'
  what():  unrecognised option '-g'
/var/spool/slurm/job3785860/slurm_script: line 19: 738313 Aborted                 (core dumped) delly filter -f somatic -o $OUT_FILE -s $SAMP_TSV -g $REF -m 0 -a 0.05 -r 0.1 $IN_FILE

Kindly help me resolve this issue.

Thank you in advance!

Best
Nidhi

**Comment by yashcrux** [comment]
Hello Nidhi

I was just having a look at the your issue.
I also faced something similar and dos2unix helped with it!.

In your case I can see that there is  typo. It should be "tumor" in delly_samples.tsv.
I think it will solve it.

**Comment by NidhiAgrawal27** [comment]
Hey!

Thank you so much for going through the issue and pointing that out!! It worked.

Spelling of 'tumor' was the issue :) 

Best
Nidhi
