### ISSUE TITLE
GATK error parsing DELLY2 VCF

### ISSUE THREAD

**Issue by bbimber** [dellytools/delly#37]
Hello,

The DELLY VCFs write per-sample genotypes roughly like the following for no-call samples:

./.:.,.,.:0:LowQual:0:0:0:-1:0:0:0:0

note the ".,.,." for genotype likelihoods.  GATK chokes on this with a parse error saying "." is not an integer.  In similar no-call situations GATK writes these as 0,0,0.  I can see an argument that "." ought to be acceptable, but it would be helpful if DELLY conformed to GATK to allow their variant manipulation tools to work.  I fixed my outputs w/ sed for now.

Thanks,
Ben

**Comment by tobiasrausch** [comment]
Hi Ben,

Thanks for pointing this out. Unfortunately, there seem to be tools that require just a '.' for unknown genotypes and others that require './.' (or maybe even './.:0,0,0') and all notations seem to "validate" using vcf-validator. I am not sure how to find a "consensus" here.

Best, Tobias

**Comment by tobiasrausch** [comment]
Delly is using by now HTSlib to set missing genotypes so I guess that's working fine with GATK. If not please re-open that issue. Thanks, Tobias
