### ISSUE TITLE
Question about delly's selectInversions() function in short-read call

### ISSUE THREAD

**Issue by q-wind** [dellytools/delly#372]
Hello,
I'm reading the Delly's source code, and I am confused about the way the `selectInversions()` function identifies inversion in `shortpe.h line426`.
In my understanding, the `selectInversions()` function in `junction.h` iterates over each `JunctionVector` in `readBp`. In the previous processing, each `JunctionVector` corresponds to the junctions of a certain read, and the `forward` field in these `Junction` structures is set to have the same alignment direction as the `rec` in the `_insertJunction()`. 
So, in `selectInversions() junction.h line195` how can we got two `Junction` with different `forward`? I haven't understood this part yet. I hope to get your help. 
Thank you so much!
Qingwen

**Comment by tobiasrausch** [comment]
Yes, that's right.

**Comment by q-wind** [comment]
Thanks for your help!
