### ISSUE TITLE
Segmentation Fault : core dump occurred

### ISSUE THREAD

**Issue by BIOJHK** [dellytools/delly#381]
Hi Tobias, I'm working on human genome, and some problems are occurred and have no idea for solving.

I used Delly 0.9.1 version. 

1> Different human genome mapping bam occurred segmentation fault
I had two bam file type, which mapped with hg38 (with no "chr") and 
hg38(with "chr" annotation), and want to get merged sv sites.bcf but it doesn't work well.

After germline SV / CNV pipline proceeding seperately, 
when I check final combined result with manipulating data( to change "nochr" to "chr"), missing information
S1-S3 ("no chr") / S4-S6 ("chr")
S1 S2 S3 S4 S5 S6
./.:.:.:. ./.:.:.:. ./.:.:.:. ./.:-998,32.PASS:1. ./.:-998,32.PASS:1. ./.:-998,32.PASS:1.
./.:-998,32.PASS:1. ./.:-998,32.PASS:1. ./.:-998,32.PASS:1. ./.:.:.:. ./.:.:.:. ./.:.:.:.  

How do I solve this segementation fault?
I cannot modifying the mapping genome and bam file, so I would like to know how to use delly in this case.

2> Could I ask the using other CNV tools results with merge sites for CNV delly process? When I do CNV delly process with CANVAS results, it omits segementation fault:core dump error.

**Comment by tobiasrausch** [comment]
SV and CNV tools use many custom INFO fields in the VCF spec and this makes merging CNVs across tools very difficult. For renaming chromosome names in VCF files, bcftools may work:

`bcftools annotate --rename-chrs ...`

**Comment by BIOJHK** [comment]
Thank you for your response. 
However, the solution provided does not seem to be effective on me. Upon testing, I found that the chr1(or 1) and chrMT(or M) data performed as expected, but the data for chr2-22, X, and Y did not yield the same results with segmentation fault.

I initially identified a sorting error, prompting me to test the data using the bcftools option and reheader. Upon review, I noted the order of the hg38 dataset without "chr" prefixes was as follows: 1, 10, 11, 12, ..., 2, 21, 22, 3, 4, 5, ..., M, X, Y. Conversely, the order for the hg38 dataset with "chr" prefixes was: chr1, chr2, chr3, chr4, ..., chrX, chrY, chrMT.

After manipulating the data in both formats like header information matching, the merge process completed without errors. However, during the genotype extraction process, a segmentation error occurred. 
Could you please advise on any additional steps or processes I might undertake to successfully complete the entire pipeline?
