### ISSUE TITLE
cannot create mappability map

### ISSUE THREAD

**Issue by Brodieson** [dellytools/delly#386]
Hi There, 

I have been fruitlessly trying to make a mappability map for Susscrofa11.1 so that i can call CNVs using delly and nothing is working.  I do not have fastq files, I am only working with bam files.  I have a reference genome, can anyone please advise?

cheers
Nicole

**Comment by tobiasrausch** [comment]
Dear Nicole,

I created a susScr11 mappability map: [https://gear-genomics.embl.de/data/delly/](https://gear-genomics.embl.de/data/delly/)

Best, Tobias

**Comment by Brodieson** [comment]
Thank you so very much!

Kind Regards,
Nicole Lewis
________________________________
