### ISSUE TITLE
How to generate map file for new reference genome

### ISSUE THREAD

**Issue by MenakaRaj12** [dellytools/delly#387]
for my reference genome, which is bos taurus. I couldnt find any map file for this reference genome in the data of delly repository for mappability maps. So, I tried to generate the map file using mapdamage which is not work to generate the cnv files in delly tool. So, now i found the another tool called gemtools, i am not this can help for my case. Could you please any idea regarding this?

**Comment by tobiasrausch** [comment]
Please see the [FAQ](https://github.com/dellytools/delly#faq) section, it has a paragraph on how to generate mappability maps for `delly cnv`.

I have also added pre-computed bos taurus maps (bosTau9) to the download directory: [https://gear-genomics.embl.de/data/delly/](https://gear-genomics.embl.de/data/delly/)

**Comment by MenakaRaj12** [comment]
It is more helpful for me. Thanks a lot for your response. I will work with your comments
