### ISSUE TITLE
delly cnv ERROR ：unexpected "N" at line 1

### ISSUE THREAD

**Issue by Jerry-Wang-Dog** [dellytools/delly#395]
command line：
delly cnv -g genome.fa -o cnv_sample1.bcf -m genome.fa.map sample1.markdup.bam
↓↓↓
[E::fai_build_core] Format error, unexpected "N" at line 1
Segmentation fault (core dumped)

 A series of N is in the reference sequence, but this is unavoidable, when using ”delly call“ sv will not report this error, why does it report an error when calling cnv, how to solve this?

**Comment by tobiasrausch** [comment]
Does this work?

`samtools faidx genome.fa`

**Comment by Jerry-Wang-Dog** [comment]
Of course，and I have already generated the file 'genome.fa.fai'

**Comment by tobiasrausch** [comment]
Then it's probably the mappability map. You can try

```
bgzip  genome.fa.map
samtools faidx genome.fa.map.gz
```

**Comment by tobiasrausch** [comment]
Please see the [FAQ](https://github.com/dellytools/delly?tab=readme-ov-file#faq) to how to compute a mappability map.

**Comment by Jerry-Wang-Dog** [comment]
Wow！It Works！Thanks very much！
It‘s my fault that I’ve ignored the construction of mappability map.

**Another question about the output file :**
1.  What does  "./." in FORMAT=GT mean ?
2.  Does "0" in   FORMAT=CN mean deletion  and "1" mean only one copy (the same as genome?) and "more than 1" mean that copy number of this sample is more than the referance genome  ?

**Comment by tobiasrausch** [comment]
I am closing this issue because it's fixed and opened a new one for your question.

**Comment by Jerry-Wang-Dog** [comment]
![delly-map](https://github.com/user-attachments/assets/bd88ca80-8e6e-4f3b-aeb0-8821ce1b3b76)
Is my map file strange？  I followed the FAQ exactly.
