### ISSUE TITLE
Format GT/CN question

### ISSUE THREAD

**Issue by tobiasrausch** [dellytools/delly#396]
Wow！It Works！Thanks very much！
It‘s my fault that I’ve ignored the construction of mappability map.

**Another question about the output file :**
1.  What does  "./." in FORMAT=GT mean ?
2.  Does "0" in   FORMAT=CN mean deletion  and "1" mean only one copy (the same as genome?) and "more than 1" mean that copy number of this sample is more than the referance genome  ?

_Originally posted by @Jerry-Wang-Dog in https://github.com/dellytools/delly/issues/395#issuecomment-2552564996_

**Comment by tobiasrausch** [comment]
For the cnv subcommand, delly does not output bi-allelic genotypes but copy-number estimates in the FORMAT/CN field. For an autosomal chromosome in a diploid organism CN=1 would be a heterozygous deletion and CN=0 a homozygous deletion.

**Comment by Jerry-Wang-Dog** [comment]
How to explain this CN is 4 ?
chr2     16994340        CNV00000033     N       <CNV>   31      PASS    IMPRECISE;SVTYPE=CNV;SVMETHOD=EMBL.DELLYv1.3.1;END=16999591;CIPOS=-421,28;
CIEND=-99,101;MP=0.747573     GT:CN       ./.:4
