### ISSUE TITLE
Deviation from vcf spec

### ISSUE THREAD

**Issue by rernst** [dellytools/delly#59]
Hello,

According to the header Delly (we are using v0.7.2) follows the VCFv4.1 format. Unfortunately delly seems not to follow the vcf specs on some points, this makes downstream analysis of delly results difficult. 
### SVTYPE

TRA is not a valid svtype according to the vcf-spec.
Delly: Values: DEL, DUP, INV, **TRA**, INS.
VCF-spec: `##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
Value should be one of DEL, INS, DUP, INV, CNV, BND.`
### Translocations / breakends

Translocations / breakends should be using the following format according to the vcf spec.

```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO
2   321681  bnd W   G   G]17:198982]    6   PASS    SVTYPE=BND
17  198982  bnd Y   A   A]2:321681] 6   PASS    SVTYPE=BND
```

It would be very useful if Delly would output these variants according to the vcf specifications.

**Comment by tobiasrausch** [comment]
When I wrote Delly there was no breakend notation but I might adopt this in the future. The only problem is that the breakend notation is very non-intuitive and thus, many SV callers do not support it but rather follow the paradigm that one VCF record should be one SV instead of breaking it up into two records (or even 4 for a simple inversion). In addition, Delly would then need to duplicate all genotypes which is again rather awkward for large population studies. 

This seems to be a rather general limitation of a fixed-field format such as VCF and a line-delimited JSON format would fit translocations and complex SVs in general way better but it's probably to late for a VCF/BCF replacement given how widespread it is already used.

I will flag this as an enhancement. Will try to provide at least a converter to breakend notation in the future, the default Delly output will probably remain as it is because of the genotyping issue.

**Comment by rernst** [comment]
Thanks for your anwser. I do understand that specifications change, but I don't think that one should say to follow one, while not doing so. This is in general a problem with sv callers and very annoying if one want to compare callers and/or store the results in a similar way.

Furthermore, for most cases it is perfectly fine (according to the vcf specs) to have 1 record per variant, also for inversions, see page 15 (http://samtools.github.io/hts-specs/VCFv4.1.pdf). The only problem are translocations, which should be described by breakends instead off a single record. It would be great if you could provide a solution for them.

**Comment by tobiasrausch** [comment]
Well, there seem to be some open issues with that VCF spec that exactly reflect my point of view (https://github.com/samtools/hts-specs/issues/89#issuecomment-112119514):

"I believe breakends are better for describing the kinds of structural rearrangements one finds in cancer genomes. Our lab focuses more on complex common SVs, such as 17q21.31 and similar sorts of situations where we might want to represent shared haplotypes in the population but may not have the level of specificity implicit in or required by the breakend notation.

I'm not suggesting any specific changes to the spec, just that we don't add language that would make a VCF invalid if it contains a new symbolic allele (although all symbolic alleles SHOULD be defined in the header)."

That's pretty much exactly what I do with "TRA". It's defined in the header and in it's current form it allows me to represent shared GTs in a population.

**Comment by tobiasrausch** [comment]
The spec actually also explicitly states for SVTYPE that "This key can be derived from the REF/ALT fields." so any vcf-validator should except ALT=<TRA> and INFO:SVTYPE=TRA, I believe.

**Comment by rernst** [comment]
It also says (line in front of your quote): "Value should be one of DEL, INS, DUP, INV, CNV, BND." If I look at the example of page 15 Alts can have other values but SVtype is restricted to these. 

I discussed a bit with a colleague who is currently writing a sv caller for nanopore data and he would represent your calls in the following manner to be compatible with vcf spec while not adding more rows per variant. 

### Delly line:
```
1	815679	TRA00000088	N	<TRA>	.	PASS	CHR2=Y;CIEND=-537,537;CIPOS=-537,537;CT=3to5;END=9972601;IMPRECISE;INSLEN=0;MAPQ=23;PE=341;SVMETHOD=EMBL.DELLYv0.7.2;SVTYPE=TRA
```
### New proposed output:
```
1	815679	TRA00000088	N	N[Y:9972601[	.	PASS	CHR2=Y;CIEND=-537,537;CIPOS=-537,537;CT=3to5;END=9972601;IMPRECISE;INSLEN=0;MAPQ=23;PE=341;SVMETHOD=EMBL.DELLYv0.7.2;SVTYPE=BND
```

**Comment by tobiasrausch** [comment]
Thanks, that looks more promising. If I can encode all 4 possible connection types (INFO:CT) in such an ALT tag I am fine to switch in a future Delly release. I will check.

**Comment by tobiasrausch** [comment]
Delly is using now the BND format for interchromosomal translocations.

**Comment by rernst** [comment]
Awesome thanks! Any eta on release?

**Comment by tobiasrausch** [comment]
I hope within ~2 weeks.
