### ISSUE TITLE
IUPAC ambiguity codes in reference allele

### ISSUE THREAD

**Issue by d-cameron** [dellytools/delly#65]
DELLY does not produce VCF compliant output when run on hs37d5 as the decoy sequence contains IUPAC ambiguity codes. As a result, delly produces results such as (note the K base in the reference allele):

del.vcf:hs37d5  31649505   DEL00034991  GNNNNNNNNNNNNNNNNNNNNACCACCCCCATTATCACCACCCTGATTATCAACACCACCACCATCACCATCATAATTGTTACAGGGTGGATTCCCCAGGAACTTGATCCTGAGATGGAGATTAGCAGGGAGGTGTTTA**K**TTGGGAATGTTCCTGGGATCAGCACCTATGGAAGGGGGTTAAGAAACCAGGATTGGGCAGAGGGAGGAGACAGGATGCAGTGTAGTCCCAACAAAGGCTTCGGTCAACACCATGGGGAGCTCTAACTCAGATGGTCCCTCCAAGTTGTCCTGCACTGGGGCCTCTATCACTTACAACC        G       .       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.6;CHR2=hs37d5;END=31649823;PE=0;MAPQ=70;CT=3to5;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=10;SRQ=0.972868;CONSENSUS=ATTCTATGACTTGCAACGTACAAGGCACCTAGCATGTAGTAAATGGTCAAGATATATTAGCTGTAATTTATATTATATTTACATCTATTTCCATACAAATCAGTTATGCAATTCAGGGTAATTCACTTAGCAACTTAGAGAAACAGATTTGCCTCTAGTATCATGACTGTTCTAAAACTCAAATTTATTATTGGATTTCTGAATTACAAATGAGTGAATTTAGGTAAAGCAGCTTCAGTATAATAAGATCATTTCAA;CE=1.88072        GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-98.5164,0,-171.916:10000:PASS:13812:33400:23409:2:0:0:52:33

The specifications state:
`REF - reference base(s): Each base must be one of A,C,G,T,N (case insensitive).`

As of VCFv4.3, the following clarification was made:
```
If the reference sequence contains IUPAC ambiguity codes not allowed by this specification (such as R = A/G),
the ambiguous reference base must be reduced to a concrete base by using the one that is first alphabetically
(thus R as a reference base is converted to A in VCF.)
```

As a result, DELLY is incompatable with programs such as Picard tools SortVcf as the output from DELLY is not valid VCF.

**Comment by tobiasrausch** [comment]
I agree this should be fixed. I will work on it.

**Comment by tobiasrausch** [comment]
Sorry for the delay, IUPAC codes are now replaced by the alphabetically first nucleotide.
