### ISSUE TITLE
Improved usability

### ISSUE THREAD

**Issue by henrikstranneheim** [dellytools/delly#66]
I am trying to write a wrapper around delly, which is quite complicated since you have to call each delly command five time if you want to catch all SV types.

Do you have any plans to modify Delly internally to read the bam once and then calculate all the desired SV-types after acquiring the read info and then output 1 single vcf containing all variants for a single sample. That would really improve usability a lot.

**Comment by tobiasrausch** [comment]
I fully agree this would be good but it would require a major re-write of Delly. It's definitely planned but this will require some time on my end.

**Comment by henrikstranneheim** [comment]
Sounds great!

**Comment by tobiasrausch** [comment]
Sorry for the long delay but the latest code now calls all SV types in one go.

**Comment by henrikstranneheim** [comment]
Fantastic! Look forward to using it
