### ISSUE TITLE
Could not open input bam file: call

### ISSUE THREAD

**Issue by Arisaak** [dellytools/delly#67]
Hi,
I have received the error, 
`Could not open input bam file: call`
The command I used is  
`delly  call -t DEL -g hg19_ref.fa -o ${prefix}_DEL.bcf ${prefix}.bam` 
I do not why I received this error. I have indexed bam file in the same directory as the input bam file.

Thank you.

**Comment by tobiasrausch** [comment]
Are you using the latest version of Delly? Just type delly without any arguments and then it should print the version.

**Comment by Arisaak** [comment]
Thank you for your reply.
I didn't use the latest version of Delly.
I download the latest version and it worked.
Thank you so much.
