### ISSUE TITLE
Exclude template for GRCh37

### ISSUE THREAD

**Issue by raunaqsbg** [dellytools/delly#68]
Hi
Is there an exclude template for GRCh37 which contains the additional contigs : NC_007605 (Human herpesvirus 4 type 1) and hs37d5 (BAC+Huref+NA12878+Fosmid clones), and also different nomenclature for the chromosomes. Would it be okay to go ahead with stripping "chr" from hg19.excl file. 

thanks!

**Comment by tobiasrausch** [comment]
These are already in the hg19.excl file, just scroll to the bottom.

-Tobias

**Comment by raunaqsbg** [comment]
Great, so I can use the same file as hg19, and delly will take care of the
naming differences between two versions. Thanks a lot for your help!

--
“This email may contain confidential information. Please take care in the
storage and transmission of this information. If you are not this message’s
intended recipient, please destroy it.”



Raunaq Malhotra, Ph.D
Bioinformatics Scientist
Seven Bridges Genomics Inc.
One Main Street, Suite 500
Cambridge, MA, 02142
www.sevenbridges.com
