### ISSUE TITLE
No output file written if no translocations are found

### ISSUE THREAD

**Issue by johanneskoester** [dellytools/delly#69]
If I run delly with `TRA`, and nothing is found, it does not create the bcf file and exits with status 0. However, correct would be to create an empty bcf (only header).

**Comment by tobiasrausch** [comment]
Thanks, delly is writing now an empty BCF if no SVs are found.

**Comment by johanneskoester** [comment]
Thanks! When is the next release planned? I'm asking because we need this in a large project and I'd like to use a properly released version (via bioconda) to conduct the analysis.

**Comment by tobiasrausch** [comment]
I see. There are some minor issues left. I could try mid March for the next release, is that fine for you?

**Comment by johanneskoester** [comment]
I think that should work. Thanks a lot, Tobias!

**Comment by johanneskoester** [comment]
@tobiasrausch, may I ask for a new release?

**Comment by tobiasrausch** [comment]
@johanneskoester Sorry for the delay, just released the new version. May I ask you to add this new version to Bioconda or shall I take care of this?

**Comment by johanneskoester** [comment]
Thanks! I'll take case of the release.
