### ISSUE TITLE
 Delly install with bootstrap.sh error

### ISSUE THREAD

**Issue by qingjian1991** [dellytools/delly#71]
Hi: 

when I install the delly, then make report a error:

[*@wuserver delly]$ make
cd src/modular-boost && ./bootstrap.sh --prefix=/public1/users/qingjian/Software/Delly2/delly/src/modular-boost --without-icu --with-libraries=iostreams,filesystem,system,program_options,date_time && ./b2 && ./b2 headers && cd ../../ && touch .boost
./bootstrap.sh: line 188: ./tools/build/src/engine/build.sh: No such file or directory
Building Boost.Build engine with toolset ...
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [.boost] Error 1

[*@wuserver modular-boost]$ less -S bootstrap.log
[*@wuserver modular-boost]$ more bootstrap.log
./bootstrap.sh: line 218: cd: ./tools/build/src/engine: No such file or directory

it seemed the bootstrap.sh cannot find the files:  ./tools/build/src/engine , but I donnot know how to skip such error. Any suggestions? Thank you

Jerry

**Comment by tobiasrausch** [comment]
Looks like the submodules have not been completely cloned from github.
Maybe the download was interrupted. Can you do

git submodule update --init --recursive

in the main delly directory and then make again?

Thanks, Tobias

**Comment by tobiasrausch** [comment]
Is this problem solved by now? There are also automated docker builds of delly: https://hub.docker.com/r/dellytools/delly/

**Comment by qingjian1991** [comment]
Thanks,Tobias:
I skipped the error by your suggestions:  "git submodule update --init --recursive" and installed delly correctly.
