### ISSUE TITLE
Intrachromosomal translocation

### ISSUE THREAD

**Issue by karthigayini** [dellytools/delly#72]
Hi

I am trying to identify intra-chromosomal translocation from Delly results. From the Delly user groups, I understood that "Translocation" reports only inter chromosomal. Intra chromosomal can be of different SV types and they can be found with other variant types like deletion, tandem duplication or inversion files. I address files because, every structural variant was called separately with CALL option and then filtered for somatic variants. 

I have a particular question. Is there a specific way to identify intra-chromosomal **translocation** from the variant files?

Examining CT (strand orientation) or the INSLEN (insertion length) did not help. 

Thanks for helping.

**Comment by tobiasrausch** [comment]
As I wrote in the delly-user mailing list, intra-chromosomal rearrangements are part of the DEL, DUP and INV output. After the somatic filtering, we usually visualize these rearrangements on top of read-depth plots as for instance in this [Figure 3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3332216/figure/F3/). There is no specific filter code to get only complex rearrangements.

Feel free to reopen this issue if you have further questions.
