### ISSUE TITLE
bcfTools 1.4 will not install properly

### ISSUE THREAD

**Issue by balasink** [dellytools/delly#73]
Hi all,

I've downloded cygwin-32 on windows 10, installed all the relevant packages and managed to get samtools1.4 to install properly using make and make install. Now I need bcftools to work, but it just will not install properly and I've been at this for two days.

I get the same error message every time, and being a beginner to coding and cygwin, I don't understand the error message at all. Searches online have given some solutions that I've tried but don't appear to work with the latest version of bcftools, since my makefile is different from the solutions.
Below is the error:

GTsubset.c
version.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*  version.c -- report version numbers for plugins.
 ^
plugins/GTsubset.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*  plugins/GTsubset.c -- output only positions where the selected samples exclusively
 ^
/tmp/ccJpLTpZ.o: In function `version':
/cygdrive/home/bcftools-1.4/version.c:35: undefined reference to `hts_version'
/tmp/ccsW0sJc.o: In function `init':
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:102: undefined reference to `hts_readlist'
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:116: undefined reference to `bcf_hdr_dup'
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:127: undefined reference to `bcf_hdr_id2int'
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:147: undefined reference to `bcf_hdr_id2int'
/tmp/ccsW0sJc.o: In function `process':
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:161: undefined reference to `bcf_unpack'
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:164: undefined reference to `bcf_get_format_values'
/tmp/ccsW0sJc.o: In function `destroy':
/cygdrive/home/bcftools-1.4/plugins/GTsubset.c:263: undefined reference to `bcf_hdr_destroy'
collect2: error: ld returned 1 exit status
make: *** [plugins/GTsubset.mk:2: plugins/GTsubset.so] Error 1

Any help would be appreciated! I just really don't understand this error...
Thank you all.

**Comment by tobiasrausch** [comment]
This error seems to relate to bcftools so maybe you want to bring up this issue at http://samtools.github.io/bcftools/

In general, I would not recommend using Delly on Windows using cygwin. If you want a full packaged version you might want to consider using the automatic docker builds of delly.

https://hub.docker.com/r/dellytools/delly/

As far as I know the Docker Toolbox is supported on Windows 64bit.
