### ISSUE TITLE
Dump supporting reads

### ISSUE THREAD

**Issue by johnmous** [dellytools/delly#74]
I noticed there are hidden arguments to dump the supporting reads, per SV detected:
-p for the discordant pairs and
-r for the split reads

Is the above correct? Do you plan to officially support this option in one of the next releases? It is a very useful option if one wants to do some further filtering on the SVs detected using custom scripts.

**Comment by tobiasrausch** [comment]
Yes, these 2 options are already fully supported in the latest delly version:

delly -t DEL -p pedump.gz -r srdump.gz -g ref.fa ...

They are just hidden from the help screen because the gzipped dump files can get very large for deep-coverage data.
