### ISSUE TITLE
Segmentation fault after long execution due to incorrect output path

### ISSUE THREAD

**Issue by arnikz** [dellytools/delly#76]
Hello,

I've experimented with DELLY (v0.7.7) on tumor-normal sample pair but (accidentally) used a non-existing output path (`-o  /errpath/delly.bcf file`). After a couple of hours, the execution failed with segmentation fault (core dump) incl. this error msg

`E::hts_open_format] fail to open file '/home/arnikz/delly-2/delly-DUP.bcf'`

I would suggest to check the existence of i/o paths prior to analysis. Could you pls have a look at it?
Thanks.

**Comment by tobiasrausch** [comment]
Thanks, that is a good suggestion. I just added some code to check the output file at the beginning of a Delly run.

Thanks, Tobias
