### ISSUE TITLE
Joint calling

### ISSUE THREAD

**Issue by woodoo46** [dellytools/delly#78]
Hi Delly developers,

I am wondering if delly supports joint calling on multiple samples. If you have said this somewhere, I may have missed.

Thanks.

George

**Comment by tobiasrausch** [comment]
Hi George,

You can pass multiple BAM files to Delly, this triggers joint calling of SVs on these samples. This makes sense for multiple samples from the same individual such as multiple tumor locations from the same tumor specimen.

Best, Tobias
