### ISSUE TITLE
somatic filtering python scripts

### ISSUE THREAD

**Issue by fyousif** [dellytools/delly#8]
Hi, I have been able to run the latest version successfully on our data set. The latest update seems to have fixed the segmentation issue I was running into as well. I am trying now to run the python somatic filtering scripts but I am running into some issues installing the required python modules specifically (vcf and re):

import argparse
import vcf
import numpy
import re
import banyan

any help would be appreciated,

Thanks,
Fouad

**Comment by WinterLi1993** [comment]
@fyousif  
 could you share your somatic filter scripts with me ?
thank you in advance !
