### ISSUE TITLE
Error: Unknown read group: DefaultLib; troubleshooting

### ISSUE THREAD

**Issue by evanbiederstedt** [dellytools/delly#80]
Hi 

I'm running into the checks written into Delly on July 18 commit, i.e. 
https://github.com/dellytools/delly/commit/593c702a744ea78c4fa7d327ad7170debb6ee8d2

Here's the error I get:

```
Error: Unknown read group: DefaultLib
Library parameters could not be estimated!
```
I guess that means the functions in `util.h` weren't able to find the read groups in the bams, first in line 480 

```
if (!rgPresent) params.insert(std::make_pair("DefaultLib", LibraryParams(maxNumAlignments, minNumAlignments)));
```

However, read groups do exist in both the tumor and normal bams. What else could be going wrong? 

I suppose it's possible that the `RG` are of the wrong format? Perhaps these read groups are of a type which isn't being parsed correctly:

```
@RG	ID:0	
@RG	ID:0.2	
@RG	ID:0.6	
@RG	ID:0.3	
@RG	ID:0.4	
@RG	ID:0.1	
@RG	ID:0.5
```

In other samples with `@RG` as strings, I don't see this issue

**Comment by evanbiederstedt** [comment]
After trying to replace the above read groups with Picard's AddOrReplaceReadGroups, the same error remains.

**Comment by tobiasrausch** [comment]
I suspect that some of your reads lack the RG tag or have an RG tag not defined in the header. Delly accepts BAMs without any read group or if read groups are defined then every single read needs to have a matching RG tag.

**Comment by evanbiederstedt** [comment]
I believe you are correct. After removing the RG tags in the header and re-adding RG's with picard, it appears to be working now. Issue closed, thanks.

For future users, simply remove all RG's from the BAM header with 

`samtools view -H your.bam | grep -v "^@RG" | samtools reheader - your.bam > your.new.bam`

and then try `AddOrReplaceReadGroups`
http://broadinstitute.github.io/picard/command-line-overview.html#AddOrReplaceReadGroups

**Comment by tobiasrausch** [comment]
Thanks for getting back to me, that's good to know.

**Comment by evanbiederstedt** [comment]
> Delly accepts BAMs without any read group

I did try running a pair with no read groups. I appear to get the following error 

`Error: Unknown read group: 0`

**Comment by tobiasrausch** [comment]
That means one of your reads still has a read-group in the optional tags (RG:Z:). It's not sufficient to just remove @RG from the SAM header.

**Comment by evanbiederstedt** [comment]
Thanks for the response. 
> That means one of your reads still has a read-group in the optional tags (RG:Z:). It's not sufficient to just remove @rg from the SAM header.

I suspect you're correct. However, in this case I have tried using Picard's `AddOrReplaceReadGroups` and I still run into issues---I think that should solve the issue of reads with a read group in `RG:Z:`. 

Are there other methods used by users to solve this issue?

**Comment by evanbiederstedt** [comment]
> I suspect you're correct. However, in this case I have tried using Picard's AddOrReplaceReadGroups and I still run into issues---I think that should solve the issue of reads with a read group in RG:Z:.

It looks like the following might work. The extra `sed` command should remove the optional tags:

    samtools view -h original.bam | grep -v "^@RG" | sed "s/\tRG:Z:[^\t]*//" | samtools view -bo new.bam -

**Comment by tobiasrausch** [comment]
Yes, that looks good to me. Thanks for posting this fix.
