### ISSUE TITLE
Tool to covert the embl-delly VCF format to standard VCF format

### ISSUE THREAD

**Issue by biotech25** [dellytools/delly#81]
Hi 

I am studying and analyzing embl-delly VCF files. I like to covert the embl-delly VCF format to standard VCF format in ALT column (N[Y:9972601[).  I wonder if  the tool would be available.  If available, could you tell me where I can download..?

Thank you, 
Sanghoon

**Comment by tobiasrausch** [comment]
The latest delly version outputs the breakend notation for translocations. All other SV types are part of the VCF spec and there are on-going discussions to also possibly add the former TRA type. I don't have a converter from TRA to BND, sorry.

**Comment by biotech25** [comment]
Thank you for your answer.  Sanghoon

**Comment by biotech25** [comment]
Tobias, may I ask one more question?  I wonder if you have a manual or document for the current file format. In particular I need to know how they define the left side or right side of the breakpoints which are involved in the rearrangements. 

Thank you, 
Sanghoon
