### ISSUE TITLE
 Manual or document for the current file format

### ISSUE THREAD

**Issue by biotech25** [dellytools/delly#82]
Tobias, may I ask one more question? I wonder if you have a manual or document for the current file format. In particular I need to know how they define the left side or right side of the breakpoints which are involved in the rearrangements.

Thank you,
Sanghoon

**Comment by tobiasrausch** [comment]
CHR:POS is the left side of the breakpoint and INFO:CHR2 and INFO:END is the right breakpoint. Please note that there is a [delly-users](https://groups.google.com/d/forum/delly-users) mailing list which answers many usage questions. There is also a [Cancer Genomics Tutorial](https://www.gitbook.com/book/tobiasrausch/tutorial-delly/details) available.
