### ISSUE TITLE
Delly on trio analysis

### ISSUE THREAD

**Issue by woodoo46** [dellytools/delly#83]
HI, Delly developers,

I am just wondering if we can use Delly for trio analysis, eg for joint calling on mother/father/child?

Thanks.

George

**Comment by tobiasrausch** [comment]
Hi George,

Yes, you can use Delly for trios. We have recently done this in the context of the Human Genome Structural Variation Consortium (3 trios). The Delly calls on these trios are publicly available:

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20160930_pre_ashg_calls/20161002_delly_illumina/hgsvc.delly.svs.GRCh38.20160931.high_coverage.vcf.gz

Best, Tobias
