### ISSUE TITLE
DELLY sv Size + cnvClassifier

### ISSUE THREAD

**Issue by mehar-GIT** [dellytools/delly#85]
Dear Tobias,

Sorry for the very long email. I have run DELLY on my cohort ~100 non-human samples and merged the sites and re-genotyped merged duplication sites following the DELLY protocol. I have a couple of queries regarding cnvClassifier and Size of SVs from DELLY.

######################cnvClassifier.py#############
The re-genotyped sites #157466 were filtered using cnvClassifier filter with the below parameters:

cnvClassifier.py -v Duplications_merged.17.11.vcf -o Duplications_merged.17.11.filtered.vcf -f -q 0.6

This resulted in #369 calls.

Also filtered only for PASS by removing -q 0.6 form the above command:

cnvClassifier.py -v Duplications_merged.17.11.vcf -o Duplications_merged.17.11.filteredPASS.vcf -f

This resulted in the same number of calls #369. 

Surprisingly, despite of applying -f filter there are still calls with FILTER=LowQual among the 369 calls. Why does this happen?

However when manually filtered for only FILTER==PASS, gave very high number of calls:

 grep -v "##" Duplications_DELLY_merged.17.11.vcf | awk -F "\t" '$7=="PASS"'| wc -l
44944
 
Could you let us know what does the script do differently from the grep command to give different number of calls with FILTER=PASS?

Would be worth to know the best practices to filter the DUP calls from DELLY as the above filters are producing different results.

######SIZE#########################

Also there are SVs which are >1 Mb and > 10MB in both the filtered and unfiltered DUP calls.

#### DUPs > 1MB in 157466  unfiltered calls###
$ less Duplications_DELLY_merged.17.11.tsv | awk -F "\t" '$6>10000000' | wc -l
19619
#### DUPs > 10MB in 157466  unfiltered calls ###
$ less Duplications_DELLY_merged.17.11.tsv | awk -F "\t" '$6>100000000' | wc -l
282

#### DUPs > 1MB in 369 filtered calls###
$  less Duplications_DELLY_merged.17.11.filteredPASS.tsv | awk -F "\t" '$6>10000000' | wc -l
36

A couple of calls from svprops output are shown below which span almost form the begining of chr1:

`chr start chr2 end id size vac vaf singleton missingrate svtype ct precise ci inslen refgq altgq gqsum rdratio medianrc refratio altratio maxaltratio PEsupport SRsupport supportsum

chr1 6860 chr1 24204031 DUP00000075 24197172 15 0.0477707 NA 0 DUP 5to3 0 366 0 10000 10000 1.57e+06 0.581517 82 0.0186217 0.199393 0.286977 135560 111 8055304

chr1 11636 chr1 60403768 DUP00000133 60392133 164 0.525641 NA 0.00636943 DUP 5to3 1 418 0 5 43 27199 1.74185 1322 0 0.666667 0.875 48708 969 1466

chr1 11643 chr1 60403764 DUP00000140 60392122 14 0.044586 NA 0 DUP 5to3 1 422 0 24 78 4678 2.40408 34 0 0.444444 0.727273 915 64 1382`

How could we trust the calls based on size? Please give some insights to retain a reliable call set.

**Comment by tobiasrausch** [comment]
The python scripts were deprecated almost 2 years ago. I would suggest to use the new germline SV filter in Delly.

delly filter -f germline -o germline.bcf merged.bcf
