### ISSUE TITLE
[feature request] support for long reads or contig(corrected pacbio reads)

### ISSUE THREAD

**Issue by wangyugui** [dellytools/delly#87]
Hi.

Can we add the support for long reads or contig such as corrected pacbio reads.

minimap2 and blasr can map these corrected long reads into bam file.
Can delly2 use this bam file and output DEL, INV, BND, INS ?

raw pacbio reads have many small error, so there is no needs to support it directly.
we can use canu or others to correct these reads and then use the corrected reads.

we can mapping draft genome contig to reference genome too. in this case, there will be no coverage info.

a test data set:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20170514_validation_bacs/

Best Regards

**Comment by tobiasrausch** [comment]
Thanks. I am afraid Delly will not support long reads any time soon and I suppose this will most likely require a different algorithm (at least partly assembly-based) to call SVs.

**Comment by wangyugui** [comment]
Sniffles support it.

Let's close this ticket.
