### ISSUE TITLE
Issues with Delly v0.7.7 filter results

### ISSUE THREAD

**Issue by mej54** [dellytools/delly#91]
Hi, we've been testing the latest release of Delly (v0.7.7) and are having some issues with the results of the new filtering. 

We are running Delly (v0.7.7) on the HCC1954 cell line to test for recall, with the truth set coming from COSMIC v70 (same analysis as used by the authors of Manta for testing doi:10.1093/bioinformatics/btv710). After running 'delly call' (v0.7.7), we have tried both 'delly filter' (v0.7.7) and the old stand-alone Delly filter script (v0.6.1) on this Delly callset. 

We found that running the v0.7.7 filter with default parameters and less stringent parameters (-r 0 -v 0) have a maximum recall of 135/310. On the other hand, running the v0.6.1 filter script with the same settings achieved its highest recall of 182/310.

To test precision, we ran 'delly call' (v0.7.7) on a normal sample against itself as a tumor-normal pair. We would expect no somatic SVs to be called in this case. We found that the Delly v0.7.7 filter called hundreds of translocations. The Delly v0.6.1 filter script also called many false translocations, until we used the translocation window option provided in the v0.6.1 script. 

I've attached images of both the recall and precision analyses for reference. We are wondering if you have any suggestions on how to run v0.7.7 filtering to maximize recall and minimize the false positives? We would like to use the latest filter script, but as of now it seems that the old filter script (v0.6.1) does a better job. 

For reference, these are the parameters we have tried with both filter scripts:

**v0.7.7**

default
- altaf = 0.200000003
- minsize = 500
- maxsize = 500000000
- ratiogeno = 0.75
- coverage = 10 

less stringent
- altaf = 0.200000003
- minsize = 500
- maxsize = 500000000
- ratiogeno = 0
- coverage = 0

**v0.6.1**

- altAF = 0.200000003
- minSize = 500
- maxSize = 500000000
- traWindow = 5000
- ratioGeno = 0

Thanks in advance. 

![delly2recall](https://user-images.githubusercontent.com/10553651/34783949-eb21ec2c-f5fa-11e7-8165-dc91f3c01292.png)
![delly2falsepositives](https://user-images.githubusercontent.com/10553651/34783950-eca5e33c-f5fa-11e7-8050-d10e89a80ed6.png)

**Comment by tobiasrausch** [comment]
Thanks for sharing these comprehensive results. The most important parameter for maximizing recall for somatic SVs is usually the ALT allele frequency, the required coverage and of course the SV size. Could you try for less stringent:
-a 0.1 (or even -a 0.05 to include sub-clonal somatic SVs)
-v 5 (coverage)
-c 0.01 (or -c 0.05 in case the normal is contaminated slightly with tumor material)
-m 0 (to include small InDels)

For precision, this looks fine to me for all SV types, except for translocations. The main reason why I removed the window cutoff for translocations that was present in v0.6.1 are reciprocal translocation and complex rearrangements where sometimes multiple translocations are in close neighborhood. To be honest what you should consider doing is filtering somatic SVs by a panel of normal genomes as discussed on the [delly mailing list](https://groups.google.com/forum/#!searchin/delly-users/panel$20of$20normals%7Csort:date/delly-users/OHQzSHCIdJQ/Unbis7nQAwAJ).
