### ISSUE TITLE
Delly merge of more than 1000 bcfs

### ISSUE THREAD

**Issue by jjfarrell** [dellytools/delly#94]
Delly generates an error when trying to merge more than 1000 bcfs.  My workaround is to merge groups of 500 bcfs into bcfs and then merge those bcfs into once bcf. My suspicion is that the problem is related to the cmdline length.  

A new argument option for this situation may be helpful for merging large number of files.  Something like
delly merge -f project.bcf.list where project.bcf.list  is a complete list of bcf filenames.

**Comment by holtgrewe** [comment]
Also consider the limit of open files. Might be 1024 on your machine.

**Comment by jjfarrell** [comment]
Thanks! Yes, that was the issue. The soft limit was 1024. I was able to increase the limit to 2048 (which is the hard limit) with ulimit -n 2048.  However, there is  4800 files so I will still need to workaround the Max open file limit.  

So it would be helpful to have the program to check the number of files against this limit to provide a better error message. In this case, it complained about not being able to load an index file.  Or maybe modify the program to only open max number of files at a time.

**Comment by tobiasrausch** [comment]
I had the same issue recently with bcftools merge. I agree Delly could first merge groups of files into temporary files and then merge the temporary files (as your current workaround). Thanks for suggesting this enhancement.

**Comment by tobiasrausch** [comment]
For more than 500 BCF files `delly merge` now starts to chunk the data. It first merges groups of BCF files (<=500 files) and then it merges the intermediate merged files.
