### ISSUE TITLE
Issues With Threading/CPUs

### ISSUE THREAD

**Issue by nate422** [dellytools/delly#96]
When I run Delly, it appears as if I can launch multiple threads, however, these threads are stuck in a suspended state because they are trying to run on a single CPU.  Is there a way to ensure these threads run on multiple CPUs?  Have I just built the program incorrectly?

**Comment by holtgrewe** [comment]
Read the README. Delly parallelizes on the sample level. If you have one sample, Delly will only use one thread.

As the "delly 2" best practiced workflows pass single samples to Delly, it is only ran single-threaded.

You can use workflow management tools such as Snakemake for parallelizing your overall workflow.

That said, given a sufficiently large set of genomes, your problem will always be I/O.

**Comment by tobiasrausch** [comment]
I agree, for a large set of genomes the main issue is always I/O and Delly v0.7.8 should do a lot better on this compared to previous versions. I will close this issue for the time being but please re-open if further issues arise.
