### ISSUE TITLE
Delly error with bowtie2 generated BAM

### ISSUE THREAD

**Issue by alishka1988** [dellytools/delly#97]
Hello, 

I've been running Delly on some whole genome sequencing BAM files but keep getting this error:

Error: One library has a non-default paired-end layout! Read-group: 4
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.

My data is paired-end and was generated with bowtie2 v 2.0.6. I kept mostly default settings for alignment except I'm allowing clipped reads (--local option). After first getting the error with Delly, I filtered my BAM files to only include paired alignments (using samtools view -f 1), since bowtie2 allows unpaired alignments by default. This didn't solve the problem and I still got the same error. Is there anything else I can do to filter my bowtie2 BAM file to work with Delly? I understand that it was initially designed for files generated with bwa mem but I was hoping to stick with bowtie2.

Thanks in advance, 

Alina

**Comment by tobiasrausch** [comment]
Hi Alina,

Bowtie2 is fine and it's not an issue of paired and unpaired alignments. One of your read-groups (RG tag, read-group 4) has a non-default paired-end orientation. This is for instance the case for a mate-pair library or a library that failed on the sequencer. I would suggest to remove all reads from this read-group. You can do so by using one of the later samtools versions. You just need to create a file with all the other read groups (except read group 4) and then

`samtools view -b -R rg.txt input.bam  >  output.bam `

If you want to dig deeper into this issue you can run [alfred](https://github.com/tobiasrausch/alfred). It supports read-group aware QC statistics and hence, you get an insert size distribution for every read group which should hopefully indicate what's wrong with read-group 4.

**Comment by tobiasrausch** [comment]
Hi Alina,

I changed this error message in Delly to a warning and Delly will simply ignore such a read-group in the future (then there is no need to remove the read-group from the BAM file). Can you try if it works like that for you? It is of course still useful to investigate why this read-group has an unexpected insert size distribution.

Thanks, Tobias

**Comment by alishka1988** [comment]
Hi Tobias, 

Actually I only have one read group in the BAM file, so I can't remove those reads. I believe the issue has to do with the presence RF oriented reads. About half of my samples were prepped with Nextera mate pair libraries, which can contain a mixture of FR and RF reads. I searched through the delly users group earlier and saw that it's necessary to run Nxtrim on the fastqs prior to running Delly 0.7.8. I was able to get Delly 0.7.7 to work on my BAMs with no errors without running Nxtrim and re-aligning. Would not running the trimming software affect the accuracy of the results?

Thanks, 
Alina

**Comment by tobiasrausch** [comment]
Hi Alina,

Yes, for mate-pair libraries you need to flip the read pair orientations since Delly v0.7.8. If you use [NxTrim](https://github.com/sequencing/NxTrim) for adapter trimming and finding the junction adapter then this should be fine because it indeed flips the read pair orientations. You can always use [Alfred](https://github.com/tobiasrausch/alfred) to plot the insert size distribution and read pair orientations to double-check the final BAM file used for Delly.

Best, Tobias

**Comment by maribuon** [comment]
Hi! I am having the same warning, all my reads are from the same read-group so removing them is not an option. Also, my library is not mate-paired. What can have caused the problem and how can I solve it?
