### ISSUE TITLE
The result of delly(bcf)

### ISSUE THREAD

**Issue by lkalbert001** [dellytools/delly#98]
Hello, Author. I am a new user of delly. Today I got the result from delly, but I don't know what the meaning of "_**A]chr1:17371411]**_" or "_**A[chr1:43805042[**_". Can you give some explanation for this. Thank you very much.
<img width="553" alt="2018-03-06 16 09 21" src="https://user-images.githubusercontent.com/34129931/37021251-e70ddeb8-2159-11e8-98b5-19c18f9acf52.png">

**Comment by tobiasrausch** [comment]
Please have a look at the [VCF Specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf). For inter-chromosomal translocations Delly uses the breakend notation.

**Comment by lkalbert001** [comment]
Thanks again.
