### ISSUE TITLE
how to use CIPOS and CIEND ?

### ISSUE THREAD

**Issue by WinterLi1993** [dellytools/delly#99]
HI,
 @tobiasrausch 
   I got these records ： 
A:     chr6    117642092       BND00000000  C[chr1:154142762[              CIPOS=-1,1;CIEND=-1,1; 
B:      chr6    117642093       BND00000001   ]chr1:154142761]T              CIPOS=-1,1;CIEND=-1,1

so for A record ,,, I should got the first  breakpoint position is :  chr6:117642092-1, and the second breakpoint is : chr1:154142762+1  ????

thank you !

**Comment by tobiasrausch** [comment]
CIPOS and CIEND are the confidence intervals around the breakpoint. In your case this seems to be a precise translocations from chr6:117642092 to chr1:154142762. The confidence intervals are calculated for precise breakpoints based on breakpoint homologies at edit distance 1. In other words, if the breakpoints are unique you get +/-1bp.
